### ISSUE TITLE
Gridlist not updating 

### ISSUE THREAD

**Issue by erangeles** [adobe/react-spectrum#6801] opened 2024-07-30 23:05 UTC
### Provide a general summary of the issue here

Gridlist doesn't seem to re-render/update when `items` change while using react suspense queries, this happens under 2 scenarios 
```
   <GridList
        disabledBehavior="selection"
      >
        {items.map((item) => (
          <GridListItem textValue={item.key}  key={item.key} data-test-id="list-item">
          ....
          )}
     </GridList>
```
and
```
   <GridList
        disabledBehavior="selection"
        items={items)
      >
        {(item) =>
          <GridListItem textValue={item.key}  key={item.key} data-test-id="list-item">
          ....
          )}
     </GridList>
```
Works in `1.2.1` but not in `1.3.1`, could this be related to the virtualization/collection changes?

### 🤔 Expected Behavior?

For Gridlist to re-render when items change

### 😯 Current Behavior

Gridlist is not re-rendering/updating even when items change

### 🖥️ Steps to Reproduce

https://stackblitz.com/edit/github-dnkquu?file=src%2FApp.tsx

### Version

1.3.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

OSX

### 🧢 Your Company/Team

LD

**Comment by erangeles** [comment] 2024-07-30 23:38
I wanted to mention that I am using react suspense to fetch items in this case, potentially related to https://github.com/adobe/react-spectrum/issues/6182

**Comment by snowystinger** [comment] 2024-07-31 02:15
I'm not sure what exactly the issue is, but I corrected for the possible/likely duplicate keys and I'm not able to reproduce
https://codesandbox.io/p/sandbox/interesting-microservice-vw5zm4?file=%2Fsrc%2FApp.js%3A16%2C19

**Comment by erangeles** [comment] 2024-07-31 14:04
Hey @snowystinger the issue is react suspense queries and gridlist, when we don't use suspense gridlist works as intended. I'm going to redo my minimal repro.

**Comment by erangeles** [comment] 2024-07-31 14:11
@snowystinger here is the new repro: https://stackblitz.com/edit/github-dnkquu?file=src%2FApp.tsx

**Comment by Niznikr** [comment] 2024-07-31 17:35
Looks like setting a `key` (in our case one tied to url search params since we're using `useSuspenseQuery `) on the `Suspense` boundary itself results in the `GridList` re-rendering properly. Wonder what regressed from `1.2` that caused this behavior to change?

**Comment by snowystinger** [comment] 2024-07-31 21:55
Thanks for coming back with a new repro. Given how close it is to https://github.com/adobe/react-spectrum/issues/6182 I'm going to close this issue and we can continue the conversation over there.
Thanks again

**Closed by snowystinger** 2024-07-31 21:55 UTC
