### ISSUE TITLE
FocusScope throws error

### ISSUE THREAD

**Issue by lienas** [adobe/react-spectrum#3552] opened 2022-09-25 14:15 UTC
# 🐛 Bug Report 

Using FocusScope in a Popover-Component throws the following error:
`FocusScope.tsx:466 Uncaught TypeError: Cannot set properties of undefined (setting 'nodeToRestore')
    at FocusScope.tsx:466:1
    at commitHookEffectListMount (react-dom.development.js:23158:1)
    at invokeLayoutEffectMountInDEV (react-dom.development.js:25126:1)
    at invokeEffectsInDev (react-dom.development.js:27357:1)
    at commitDoubleInvokeEffectsInDEV (react-dom.development.js:27333:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27064:1)
    at flushPassiveEffects (react-dom.development.js:26989:1)
    at commitRootImpl (react-dom.development.js:26941:1)
    at commitRoot (react-dom.development.js:26688:1)
    at performSyncWorkOnRoot (react-dom.development.js:26122:1)`

## 🤔 Expected Behavior

Throw no error

## 😯 Current Behavior

throws error, see bug report

## 🔦 Context

I tried to implement the example, documented for ComboBox with ChakraUI from here:
[https://codesandbox.io/s/dreamy-burnell-3i2jy?file=/src/App.tsx](https://codesandbox.io/s/dreamy-burnell-3i2jy?file=/src/App.tsx)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.19.0
| Browser          | chrome
| Operating System | mac-os

**Comment by snowystinger** [comment] 2022-09-25 17:04
Hey, sorry to hear that, we don't currently support StrictMode. It's on our list of things to do. You can find more info in the dupe of this https://github.com/adobe/react-spectrum/issues/3458. I'll be closing this one as a dupe.

**Closed by snowystinger** 2022-09-25 17:04 UTC
