### ISSUE TITLE
ComboBox Popover doesn't close if there is no button rendered in the ComboBox's children

### ISSUE THREAD

**Issue by nkalpak** [adobe/react-spectrum#6155] opened 2024-04-05 09:17 UTC
### Provide a general summary of the issue here

When rendering a `ComboBox` from `react-aria-components`, you must provide a `Button` element (even with `display: none`) somewhere in the `ComboBox` children tree, else the `Popover` will not close when clicking outside it.

### 🤔 Expected Behavior?

The `Popover` should close even without a `Button` being present, or this behavior should be specified in the `ComboBox` documentation.

### 😯 Current Behavior

The `Popover` doesn't close when a `Button` is not rendered. There is no mention of this in the documentation, so omitting the button causes an issue which is difficult to pinpoint.

### 🖥️ Steps to Reproduce

[Sandbox](https://codesandbox.io/p/sandbox/cocky-fire-65glf5?file=%2Fsrc%2FAutocomplete.tsx%3A17%2C31)

To observe the issue:
1. Focus the input
2. Type "a"
3. Click outside the input

To see how the button's presence fixes the issue, uncomment the `Button` in `Autocomplete.tsx`. Even if the button had a `display: none` style, it would still fix the issue.

### Version

1.1.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

Ubuntu

**Comment by sookmax** [comment] 2024-04-05 15:16
Interesting.. I was unable to reproduce this in my local dev environment, so I forked your sandbox and updated the dependency `"react-aria-components"` to `"1.1.2-nightly.4539"` and it seems to work now.

[1.1.2-nightly.4539 sandbox](https://codesandbox.io/p/sandbox/cocky-fire-forked-s3zl85?file=%2Fsrc%2FAutocomplete.tsx%3A17%2C31&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clumsgidq00073b6hc47ca6pq%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clumsgidp00033b6h6ibct42m%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clumsgidp00043b6hoxvvwo9x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clumsgidp00063b6hx5gwrhzs%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clumsgidp00033b6h6ibct42m%2522%253A%257B%2522id%2522%253A%2522clumsgidp00033b6h6ibct42m%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clumsznh900023b6h072dwfy2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A17%252C%2522startColumn%2522%253A31%252C%2522endLineNumber%2522%253A17%252C%2522endColumn%2522%253A31%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FAutocomplete.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clumsznh900023b6h072dwfy2%2522%257D%252C%2522clumsgidp00063b6hx5gwrhzs%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clumsgidp00053b6hbohuzaba%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clumsgidp00063b6hx5gwrhzs%2522%252C%2522activeTabId%2522%253A%2522clumsgidp00053b6hbohuzaba%2522%257D%252C%2522clumsgidp00043b6hoxvvwo9x%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clumsgidp00043b6hoxvvwo9x%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by yihuiliao** [comment] 2024-04-05 17:48
Closing as fixed. Thanks for looking at it @sookmax. We will hopefully be releasing by the end of the month but in the meantime, you can use the nightly. Feel free to reopen if there’s still any issues

**Closed by yihuiliao** 2024-04-05 17:48 UTC

**Comment by nkalpak** [comment] 2024-04-07 08:07
Thanks for the help, I'll keep using the display: none hack until the next release, cheers!
