### ISSUE TITLE
[RAC] Link onPress handler not triggered on pseudo element.

### ISSUE THREAD

**Issue by adriantrunzo** [adobe/react-spectrum#6484] opened 2024-06-03 17:21 UTC
### Provide a general summary of the issue here

When using a pseudo element to expand the hit area of an `<a>` rendered with Link, the `onPress` handler is not called when clicking the pseudo element even though the `data-pressed` attribute is applied and the href is followed. `onPress` is only called when the click target is the `<a>` itself. `onPressStart` and `onPressEnd` work as expected, though.

### 🤔 Expected Behavior?

The `onPress` handler should be called when clicking on the `<a>` pseudo element.

### 😯 Current Behavior

The `onPress` handler is not called when clicking on the `<a>` pseudo element.

### 💁 Possible Solution

Workaround is to use `onPressStart` or `onPressEnd`.

### 🔦 Context

Expanding the target area of a link is a common way to implement Cards with a link, where the entire Card activates the link: https://kittygiraudel.com/2022/04/02/accessible-cards/.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/ecstatic-wescoff-8fkkc3

In this sandbox, the Link has a `::before` element that covers the parent `div` of the Link. Clicking on the `a` element itself increments the counter as expected. Clicking anywhere else in the bordered area triggers the `data-pressed` CSS state, but does not increment the counter as expected.

https://github.com/adobe/react-spectrum/assets/1218900/dd28fc48-1d59-4704-a845-544bafd80101

### Version

1.2.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

mac OS 14.3

**Comment by reidbarber** [comment] 2024-06-03 17:23
Looks like a duplicate of https://github.com/adobe/react-spectrum/issues/2506

**Comment by adriantrunzo** [comment] 2024-06-03 17:26
Yes, very likely a duplicate as the event handling is shared in https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/usePress.ts (I think). Sorry I didn't find that other issue. I was limiting my search to include "link".

**Comment by reidbarber** [comment] 2024-06-03 17:33
No worries, I'll close this a duplicate of https://github.com/adobe/react-spectrum/issues/2506

**Closed by reidbarber** 2024-06-03 17:33 UTC
