### ISSUE TITLE
Controlled RAC `Tabs` : cannot keep the `selectedKey` empty

### ISSUE THREAD

**Issue by rlebosse** [adobe/react-spectrum#5700] opened 2024-01-16 09:43 UTC
### Provide a general summary of the issue here

I am using the controlled RAC component `TabList` initiated with `selectedKey = null` but as soon as the component is rendered, `onSelectionChange` is called with the first `Tab` `id` found.

### 🤔 Expected Behavior?

I was expecting that `selectedKey` would stay `null` until I intentionnally click or focus one of the `Tab` elements.

### 😯 Current Behavior

`onSelectionChange` is called with the first `Tab` `id` found.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/peaceful-darkness-gqg7g8?file=%2Fsrc%2FApp.js%3A2%2C70

### Version

3.31.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by reidbarber** [comment] 2024-01-16 15:56
This is the expected behavior currently:

https://github.com/adobe/react-spectrum/blob/4ae2831f9487958511c88b9ebe672b5650042d7e/packages/%40react-stately/tabs/src/useTabListState.ts#L67-L82

and it seems intentional:

https://github.com/adobe/react-spectrum/blob/4ae2831f9487958511c88b9ebe672b5650042d7e/packages/%40react-stately/tabs/src/useTabListState.ts#L44

Even if this is a valid use case, I think this may be considered a breaking change so it definitely needs more discussion by the team.

**Comment by snowystinger** [comment] 2024-01-17 01:28
Yes, this is intentional. There must be a tab selected. We followed this pattern to implement our `Tabs` https://www.w3.org/WAI/ARIA/apg/patterns/tabs/
which says
> When a tabbed interface is initialized, one tab panel is displayed and its associated tab is styled to indicate that it is active.

**Comment by reidbarber** [comment] 2024-01-23 16:48
Closing since it is behaving as intended.

**Closed by reidbarber** 2024-01-23 16:48 UTC
