### ISSUE TITLE
ListView Items height not scales after changing the item content

### ISSUE THREAD

**Issue by narendra-sabale** [adobe/react-spectrum#3312] opened 2022-07-15 13:11 UTC
# 🐛 Bug Report 
ListView Items height not changing after changing the content of listView item.

## 🤔 Expected Behavior
By changing the content of item, it need to auto resize.

## 😯 Current Behavior
Trying to modify the content of listView items or conditionally rendering different component inside listView items, if content size is different then its hidden. 

## 💁 Possible Solution
height calculation need to happen on change in items.

## 🔦 Context
I was trying to use the <ListView> component to render the list of items. When I try to render the different content on click of items (changing the content inside <Item> component), facing issue with item height. seems like item height is calculated only on initial render or window resizing.

## 💻 Code Sample
[Codesandbox link](https://codesandbox.io/s/listview-item-height-test-gmbcns?file=/src/App.js)

## 🌍 Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | ^3.18.0 / 3.0.0-beta.0 (for listView)
| Browser          | Chrome 102.0.5005.61
| Operating System | macOS

## 🧢 Your Company/Team
Adobe/DX

**Comment by ktabors** [comment] 2022-07-15 17:02
This is a duplicate of #2092. The relevant codesandbox example of was added there with additional details.

**Closed by ktabors** 2022-07-15 17:02 UTC
Labels: duplicate
