### ISSUE TITLE
Cannot use react-spectrum in Next.js without returning "Syntax Error: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by deepkmal** [adobe/react-spectrum#4672] opened 2023-06-16 09:57 UTC
# 🐛 Bug Report 

I'm building a rangeCalendar in my Next.js application using React-Aria and @internationalized/date. I am currently unable to import the required modules from these libraries without an error being thrown. 

## 🤔 Expected Behavior

Import should work as normal. 

## 😯 Current Behavior

I am using Next.js and the page is server-side rendered.

When importing these libraries into my project, the following error is thrown:
```
*absolute-path-to-project*/node_modules/@internationalized/message/node_modules/intl-messageformat/lib/index.js:6
import { IntlMessageFormat } from './src/core';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15) {
  page: '/explore'
```
## 🔦 Context

I am attempting to build a rangeCalendar for an accomodation marketplace application. This calendar would go in the list of available accomodation and the range calendar would allow users to search for the homes that matches their travel dates.  

## 💻 Code Sample

The problematic import statements seem to be:
```
import { useRef, useEffect } from "react"
import { useRangeCalendarState } from "react-stately"
import { useRangeCalendar } from "react-aria"
import { useRouter } from "next/router"
// import { useLocale } from "react-aria"
import { createCalendar } from "@internationalized/date"
import HorizontalCalendarGrid from "./HorizontalCalendarGrid"
import CalendarHeader from "./CalendarHeader"
import { useStore } from "@/store/store"
import { shallow } from "zustand/shallow"
import { TbPlusMinus } from 'react-icons/tb
```

## 🌍 Your Environment

Version of each package being used are: 
next: 13.2.4
react-aria: ^3.25.0
@internationalized/date: ^3.2.0 

It might be worth mentioning that I am using the Page Router not the App Router, and thus am not using React Server Components. 

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser: Google Chrome (Version 114.0.5735.134)          |
| Operating System: Windows 11 Home (OS Build: 22621.1848) |

**Comment by snowystinger** [comment] 2023-06-16 15:05
https://github.com/adobe/react-spectrum/discussions/4653#discussioncomment-6190591

**Comment by deepkmal** [comment] 2023-06-17 01:57
> [#4653 (comment)](https://github.com/adobe/react-spectrum/discussions/4653#discussioncomment-6190591)

None of these helped sorry. I am attempting to reproduce it in a codesanbox, will post here soon

**Comment by snowystinger** [comment] 2023-06-17 02:36
Thank you, that will help a lot. Sorry those other tickets weren't able to help.

**Comment by ktabors** [comment] 2024-04-11 21:30
Were you able to reproduce this in a codesandbox? Since Next.js is currently v14, are you able to upgrade and does that resolve the issue? Closing and if it's still a problem we can reopen.

**Closed by ktabors** 2024-04-11 21:30 UTC
Labels: waiting
