### ISSUE TITLE
[RSP] Components cannot read CSS vars when rendered inside a portal

### ISSUE THREAD

**Issue by evargast** [adobe/react-spectrum#1697] opened 2021-03-12 18:26 UTC
# 🐛 Bug Report 

If V3 components are rendered using ReactDOM.createPortal, the components don't seem to be able to access the CSS variables. 

![Screen Shot 2021-03-12 at 12 14 32 PM](https://user-images.githubusercontent.com/52969178/110981249-82ba9e00-832c-11eb-936e-a4676d9890c5.png)

## 🤔 Expected Behavior

Components should look and feel the same whether they were rendered using ReactDOM.render or ReactDOM.createPortal

## 😯 Current Behavior

Components are rendered using browser default styling instead, [see codesandbox example](https://codesandbox.io/s/rsp-portal-example-l6n23?file=/src/App.tsx)

## 💁 Possible Solution

Not 100% sure :/ 

## 🔦 Context

We were trying to render an RSP v3 component within another part of the website that is outside of our react environment / component tree. 

## 💻 Code Sample

[codesandbox example](https://codesandbox.io/s/rsp-portal-example-l6n23?file=/src/App.tsx)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.8.0 | 
| Browser          | Chrome Version 89.0.4389.82 (Official Build) (x86_64) | 
| Operating System | MacOS Big Sur 11.1 | 

## 🧢 Your Company/Team

Adobe / Commerce Cloud

**Comment by devongovett** [comment] 2021-03-12 19:25
It should work if you nest a Provider inside your portal I think?

**Comment by evargast** [comment] 2021-03-12 19:31
unfortunately it doesnt :( that was the third example of the codesandbox / screenshot above

**Comment by so99ynoodles** [comment] 2021-03-13 02:21
It seems like `Provider` inside the portal doesn't render `ProviderWrapper`.

```tsx
if (!prevContext || props.locale || theme !== prevContext.theme || colorScheme !== prevContext.colorScheme || scale !== prevContext.scale || Object.keys(domProps).length > 0 || otherProps.UNSAFE_className || Object.keys(styleProps.style).length > 0) {
    contents = (
      <ProviderWrapper {...props} UNSAFE_style={{isolation: !prevContext ? 'isolate' : undefined, ...styleProps.style}} ref={ref}>
        {contents}
      </ProviderWrapper>
    );
  }
```

As you can see, changing the theme of lower-level `Provider` will work properly.

![image](https://user-images.githubusercontent.com/46433895/111015621-2cf9fa80-83ed-11eb-9b11-acbe3c4776c4.png)

Possible solutions might be like: 
- Add props like `isPortal` to `Provider` so it could render `ProviderWrapper`.
- Inject CSS variables `ProviderWrapper` has to `body` tag.

**Comment by snowystinger** [comment] 2021-04-14 23:25
`isPortal` (name pending) seems like a good way to go

**Comment by dannify** [comment] 2021-12-22 19:55
Out of curiosity @evargast, if you add an arbitrary prop to Provider such as `data-test-id="foo"`, does it solve your problem?

**Comment by dsmmcken** [comment] 2023-08-16 18:31
> Out of curiosity @evargast, if you add an arbitrary prop to Provider such as data-test-id="foo", does it solve your problem?

Old thread, but looks like `isPortal` PR stalled. I can confirm that adding an arbitrary data-prop does trigger the expected output. Wrapping the `Provider` with a component that accepts isPortal to set a useId as a unique prop on the Provider is an okay work-around.

**Comment by snowystinger** [comment] 2024-05-02 21:30
Closing as there is an acceptable workaround which is very close to the proposed PR. You can specify `data-isPortal` on the Provider.

**Closed by snowystinger** 2024-05-02 21:30 UTC
Labels: good first issue
