### ISSUE TITLE
Submenu doesn't open on arrow key when using typeahead to select it if keypresses are made once it's already been focussed

### ISSUE THREAD

**Issue by RobHannay** [adobe/react-spectrum#6704] opened 2024-07-15 10:06 UTC
### Provide a general summary of the issue here

Once a submenu trigger item is focussed, pressing any further keys cause it to no longer act as a submenu as the right arrow instead jumps focus to the top of the menu.

For example, let's imagine using typehead on a menu with "Hello" and "Helicopter".
I would need to _minimally type_ "Heli" to jump to the "Helicopter" item.
Then, pressing right arrow opens the submenu.

If instead I typed "Helic", I'm now one key press "more" than I needed. 

Pressing right arrow does not open the submenu, and instead focusses on the first menu item of the current menu.

This same "more than necessary" key press behaviour is true for other interactions, like pressing left on the last menu item, which again causes the right arrow press not to open the submenu, rather to jump focus to the top again.

Equally, keypresses that are not involved in the typeahead functionality whatsoever should be ignored. e.g. in the example below, pressing something like "b" or "-" causes the same behaviour.

https://github.com/user-attachments/assets/f883d5ba-0e02-45d4-a2d9-50c407ab7f96

### 🤔 Expected Behavior?

Regardless of how many "superfluous" typeahead (or other) keypresses I make, the right arrow (for LTR lanugages) should open the submenu.

### 😯 Current Behavior

The right arrow (for LTR lanugages) jumps focus to the first menu item in the current (top level) menu.

### 💁 Possible Solution

For some reason, pressing a key once a menu item is focussed causes it to "forget" that it's on a sub menu item.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/stupefied-wind-vjsgl9

- Open menu
- Type "heli" to focus the "helicopter" item
- Press right arrow key 
- Submenu opens as expected ✅ 

- Open menu
- Type "helic" to focus the "helicopter" item
- Press right arrow key
- Submenu does not open. Instead, focus is given to the "Apple" item

### Version

1.2.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

Mac OS

**Comment by reidbarber** [comment] 2024-07-15 15:38
This definitely looks like a bug, however I pasted this example in our storybook and can't reproduce it there for some reason.

**Comment by reidbarber** [comment] 2024-07-15 16:08
>  I pasted this example in our storybook and can't reproduce it there for some reason

Looks like this is because this issue has been fixed since the latest release. I upgraded the sandbox to use the nightly release, and can no longer reproduce it: https://codesandbox.io/p/devbox/3df8f5

**Comment by RobHannay** [comment] 2024-07-15 16:56
Thanks @reidbarber

**Comment by reidbarber** [comment] 2024-07-15 17:01
Closing, but feel free to re-open if any related issues are found in the nightly build

**Closed by reidbarber** 2024-07-15 17:01 UTC
