### ISSUE TITLE
Missing JPN IME suggestion window for SearchField component

### ISSUE THREAD

**Issue by NataliaBecks** [adobe/react-spectrum#4667] opened 2023-06-14 20:13 UTC
# 🐛 Bug Report 

Test Details: ja-jp, Chrome Version 114.0.5735.91, Windows 10

Steps:
1. Login to Workfront
2. Go to Boards and click on a "Add Board" button and crete a board
3. Click on "..." button near the board name > "Tag Manager"
4. Enable IME input for JPN and enter some text (e.g. "asahi")
5. Observe

Actual result: IME suggestion window is missing while typing and after first press of spacebar
Expected result: IME suggestion window should be present all the time, while IME is enabled and user starts typing

Note: Suggestion window is invoked after second press of spacebar. Works as expected on zh-cn.

## 🤔 Expected Behavior

IME suggestion window is there the moment you start to type

## 😯 Current Behavior

Suggestion window is invoked after second press of spacebar.
Bug exist only on Windows computers, Mac works as expected.

## 🌍 Your Environment

ja-jp, Chrome Version 114.0.5735.91, Windows 10

## 🧢 Your Company/Team

Adobe/Workfront Boards

**Comment by LFDanLu** [comment] 2023-11-17 20:52
Reproduced locally, doesn't reproduce with a native searchfield nor with a basic controlled value TextField. Will dig further to see what is causing the IME suggestion window to not come up

**Comment by LFDanLu** [comment] 2023-11-21 17:22
From feedback on https://bugs.chromium.org/p/chromium/issues/detail?id=1503299, this seems to be a OS specific behavior quirk rather than a specific browser bug. I've filed an issue against Windows, will update once I get any feedback on it.

**Comment by LFDanLu** [comment] 2024-01-12 22:53
Closing for now since there isn't much we can do about this, haven't gotten any feedback from the windows issue I filed.

**Closed** 2024-01-12 22:53 UTC
Labels: OS bug
