### ISSUE TITLE
[Menu/Dialog] Focus resets to top of the page upon exiting dialog.

### ISSUE THREAD

**Issue by fhschan** [adobe/react-spectrum#2616] opened 2021-11-29 23:37 UTC
# 📝 Feedback
When using keyboard navigation with Menu and Dialog components, the focus resets to the top of the page.

## 🔦 Context
For a11y, if user attempts to use only keyboard navigation with a Menu component, where if an item displays a dialog, the focus is reset to the top of the page when exiting out of the dialog.

It would be good to have the focus reset to the action button of the menu prior to showing the menu items so users can resume at where they left off of previously

## 💻 Code Sample
https://codesandbox.io/s/frosty-jasper-8188g 
Please use keyboard navigation to open the menu, select `open` and then press escape to exit dialog. Observe when you exit the dialog and notice that the focus is reset to the top of the page.

![Nov-29-2021 15-35-39](https://user-images.githubusercontent.com/22137751/143959514-6118a29e-ccf1-44bf-ae0d-b833ee9268bd.gif)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| adobe/react-spectrum  | latest 3.15.x
| Browser          |  Chrome
| Operating System | MacOS Big Sur

## 🧢 Your Company/Team
Adobe/AEP

**Comment by devongovett** [comment] 2021-11-29 23:46
This is because the menu item that opened the dialog has unmounted. Duplicate of #2444.

**Closed by devongovett** 2021-11-29 23:46 UTC
