### ISSUE TITLE
useOverlayPosition does not recalculate position on scroll.

### ISSUE THREAD

**Issue by bricejar** [adobe/react-spectrum#3532] opened 2022-09-19 17:43 UTC
# 🙋 Feature Request

useOverlayPosition should recalculte position when the user scrolls.

## 🤔 Expected Behavior

useOverlayPosition should recalculate position when user scrolls and not only when they resize the window.

## 😯 Current Behavior

**useOverlayPosition** does not recalculate position when user scrolls. Only when user resizes window. 
Right now the examples use **useOverlayTrigger** to dimiss the popover when the user scrolls. 

## 💁 Possible Solution

- To not use useOverlayPosition at all, however you stop benefitting from the react-aria ecosystem. 
- To add a new prop to allow the recalculation of useOverlayPosition on scroll.
- To return a function from useOverLayPosition to manually recalculate the position so that you can implement the recaculation trigger yourself without adding the functionality to the hook.

**Comment by snowystinger** [comment] 2022-09-19 18:20
Dupe of https://github.com/adobe/react-spectrum/issues/1852

**Closed by snowystinger** 2022-09-19 18:20 UTC
