### ISSUE TITLE
Duplicate menu open

### ISSUE THREAD

**Issue by ladifire** [adobe/react-spectrum#850] opened 2020-07-28 15:02 UTC
# 🐛 Bug Report 

When fast click two menu triggers, they both displayed.

## 🤔 Expected Behavior
[preview video](https://drive.google.com/file/d/1Q-0qE2NgO_b4c5178ciOy-AQWm60R3nX/preview)

**Comment by devongovett** [comment] 2020-07-29 02:38
Hmm not sure what's going on here. Maybe something transition animation related? Would need to investigate more.

**Comment by snowystinger** [comment] 2020-07-29 23:48
Looking at this, the easiest way to repro it so far is set the Transition timeout to something pretty long, 3500 for instance.
Press on one of the buttons, staying pressed, move to second button. Release. Press second button.
If this is a cold start, repeat once more.

Working on a test for it, general idea is something like this:
```
  it.only('should always close the menu when outside things are clicked', function () {
    let menuTrigger1Ref = React.createRef();
    let button1Ref = React.createRef();
    let menuTrigger2Ref = React.createRef();
    let button2Ref = React.createRef();
    let {getByLabelText, getByRole, getByText} = render(
      <Provider theme={theme}>
        <MenuTrigger ref={menuTrigger1Ref}>
          <Button ref={button1Ref} aria-label="button1"
                  onPressStart={() => console.log('1onPressStart')}
                  onPressEnd={() => console.log('1onPressEnd')}
                  onPress={() => console.log('1onPress')} />
          <Menu items={withSection}>
            {item => (
              <Section key={item.name} items={item.children} title={item.name}>
                {item => <Item key={item.name} childItems={item.children}>{item.name}</Item>}
              </Section>
            )}
          </Menu>
        </MenuTrigger>
        <MenuTrigger ref={menuTrigger2Ref}>
          <Button ref={button2Ref} aria-label="button2"
                  onPressStart={() => console.log('2onPressStart')}
                  onPressEnd={() => console.log('2onPressEnd')}
                  onPress={() => console.log('2onPress')} />
          <Menu aria-label="foo" selectedKeys={['alpha']}>
            <Item key="alpha">Alpha</Item>
            <Item key="bravo">Bravo</Item>
          </Menu>
        </MenuTrigger>
      </Provider>
    );
    let button1 = getByLabelText('button1');
    let button2 = getByLabelText('button2');

    fireEvent.mouseDown(button1);
    fireEvent.mouseMove(button1);
    expect(getByText('Heading 1')).toBeVisible();
    expect(() => getByText('Alpha')).toThrow();
    fireEvent.mouseLeave(button1);
    fireEvent.mouseUp(button2);
    fireEvent.mouseDown(button2);
    fireEvent.mouseMove(button2);
    fireEvent.mouseUp(button2);
    expect(getByText('Alpha')).toBeVisible();
    expect(() => getByText('Heading 1')).toThrow();

    fireEvent.mouseDown(button1);
    fireEvent.mouseMove(button1);
    expect(getByText('Heading 1')).toBeVisible();
    expect(() => getByText('Alpha')).toThrow();
    fireEvent.mouseLeave(button1);
    fireEvent.mouseUp(button2);
    fireEvent.mouseDown(button2);
    fireEvent.mouseMove(button2);
    fireEvent.mouseUp(button2);
    expect(getByText('Alpha')).toBeVisible();
    expect(getByText('Heading 1')).toBeVisible();
```

I haven't quite gotten the right steps though for the test because the events i'm getting are different than the story that I built with the same render code.

**Comment by ladifire** [comment] 2020-07-30 11:38
It should listen for any click outside and close menu immediately.

**Comment by snowystinger** [comment] 2020-07-31 17:34
Update, we've made it further and the general direction we're headed is that onInteractOutside should fire on mouse down, instead of on 'up'.
onInteractOutside should listen for the capture phase of the event so that usePress on a button doesn't prevent the event from reaching onInteractOutside.
Also, we should only pass onInteractOutside prop in useOverlay when it `isOpen`.

Now we have a case where the first click of Menu opens it
second click will then close it (on mouse down from onInteractOutside closes) followed immediately by a new open from the trigger handling the same on mouse down.

Missing event from above test potentially related to missing focus/blur events.

**Comment by ladifire** [comment] 2020-08-12 03:33
![FireShot Capture 260 - MenuTrigger - menu with semantic elements ( static ) ⋅ Storybook - localhost](https://user-images.githubusercontent.com/51266596/89972013-f907fc80-dc86-11ea-8b59-f118e13e4889.png)

It's still duplicate open if we press (Click and hold, don't release mouse button) on 2nd menu button (while 1st menu opened). 
I think it's better handle onPressEnd instate onPressStart event for menu trigger.

**Comment by snowystinger** [comment] 2020-08-13 05:32
I'm unable to reproduce with your instructions, however, I was able to reproduce today with a double Picker. It's much harder now though. We'll keep looking into it, you're welcome to take a go as well :) 
Were you trying with out latest code? or are you using what we've released to npm?

**Comment by ladifire** [comment] 2020-08-13 06:20
@snowystinger  I'm using latest code on github, not npm release version!
It happend when:
Step 1: Click "Menu Button 1" to open menu 1
Step 2: Click and press "Menu Button 2" (Don't mouse up) to open menu 2

**Comment by snowystinger** [comment] 2020-08-13 16:08
Thanks for clarifying the version you're using.
Can you provide more information on the system / browser that you're using? As I'm still unable to reproduce with your method. Right now, my method is a lot of rapid fire clicking, which is not great for trying to chase down the cause of the bug and I'd love to be able to reliably reproduce it with your steps. Also, if you could share your story setup?

**Comment by snowystinger** [comment] 2021-07-19 16:59
Closed by https://github.com/adobe/react-spectrum/pull/1970

**Closed by snowystinger** 2021-07-19 16:59 UTC
Labels: bug
