### ISSUE TITLE
Open Table bugs

### ISSUE THREAD

**Issue by matthewdeutsch** [adobe/react-spectrum#1090] opened 2020-09-23 16:43 UTC
# 🐛 Bug Report 

- [ ] Nested Columns do not read correctly with NVDA - haven’t tested with other screen readers. **Not sure what bit is not announcing correctly. It reads out the column/row numbers**
- [ ] Focusing a cell then holding down arrow causes it to lag and jump while scrolling unlike FF and Safari **Reproduced**
- [ ] When I tab out of Table many rows/columns, it does a page down. When I shift tab back into the table, it does another page down **Reproduced**
- [ ] hiding columns story: if you rapidly change what columns are hidden/displayed, you get a error (might be related to transitions)? **Reproduced**
- [ ] When I focus the checkbox cell and hold the down arrow to scroll down, it becomes very choppy in the scrolling, maybe disable checkbox focus animation? **Reproduced**
- [ ] Table stories from "many columns" onwards don't fit on a mobile screen, prob should refine for testing (DL)
- [ ] From the many column example. When the width of the table is greater than the frame/browser, you can't access the first column on two. In RTL on iphone, there is weird render artifacts or it not rendering correctly on the right. See screen shots. (KT)
- [ ] using Option Tab in /story/table--hideheader will take you through buttons, if you go through a few of them, and then hit the 'up arrow', it'll put focus back above where the last non-Option-tab stop was (RS, Safari MacOS)
- [ ] Table is sometimes blurry on initialization, goes away on scroll, see screenshot (DL, Firefox Windows)
- [ ] When the select all checkbox switches from indeterminate to checked it appears un-emphasized briefly (DG)
- [x] ~~If i’ve scrolled part way down, then leave the table to do something else, come back, grab the scrollbar and try to drag it down, it jumps to the top (RS)~~ **Unable to reproduce, though I find that I am unable to grab the scrollbar without using the mouse to scroll since clicking interacts with the cell underneath the scrollbar**
- [x] ~~Cannot shift+tab back out of the table once you enter it~~ **Unable to reproduce**
- [x] ~~Async Loading button for ‘remove first item’ should probably aggregate removals in time with the table transitions
if you have a mouse plugged in so scroll bars are always visible, there are flashes of scroll bars appearing and disappearing whenever a table is loaded~~ **Can't reproduce**
- [x] ~~Rapidly using arrow keys (down) in table, also holding down throws an error in createTreeWalker~~ **Unable to reproduce**
- [x] ~~CRUD example: If you delete a row in the middle and immediately add another row, the row appears empty”~~ **Unable to reproduce**

## 🧢 Your Company/Team

RSP

**Comment by LFDanLu** [comment] 2020-09-23 20:01
- [x] ~~Cannot shift+tab back out of the table once you enter it~~ **Unable to reproduce**
- [ ] Nested Columns do not read correctly with NVDA - haven’t tested with other screen readers. **Not sure what bit is not announcing correctly. It reads out the column/row numbers**
- [x] ~~Rapidly using arrow keys (down) in table, also holding down throws an error in createTreeWalker~~ **Unable to reproduce**
- [x] ~~CRUD example: If you delete a row in the middle and immediately add another row, the row appears empty”~~ **Unable to reproduce**
- [x] ~~If i’ve scrolled part way down, then leave the table to do something else, come back, grab the scrollbar and try to drag it down, it jumps to the top (RS)~~ **Unable to reproduce, though I find that I am unable to grab the scrollbar without using the mouse to scroll since clicking interacts with the cell underneath the scrollbar**
- [ ] Focusing a cell then holding down arrow causes it to lag and jump while scrolling unlike FF and Safari **Reproduced**
- [ ] When I tab out of Table many rows/columns, it does a page down. When I shift tab back into the table, it does another page down **Reproduced**
- [ ] hiding columns story: if you rapidly change what columns are hidden/displayed, you get a error (might be related to transitions)? **Reproduced**
- [ ] ~~Async Loading button for ‘remove first item’ should probably aggregate removals in time with the table transitions
if you have a mouse plugged in so scroll bars are always visible, there are flashes of scroll bars appearing and disappearing whenever a table is loaded~~ **Can't reproduce**
- [ ] When I focus the checkbox cell and hold the down arrow to scroll down, it becomes very choppy in the scrolling, maybe disable checkbox focus animation? **Reproduced**

**Comment by LFDanLu** [comment] 2020-10-12 23:14
Addition possible issues to discuss from https://github.com/adobe/react-spectrum/pull/1077#pullrequestreview-506844829:
Page down only takes the user to the last page, once on that last page you can't get to to the last item in the table by hitting page down again.
It seems weird that that in row selection or cell selection, the enter/return key can toggle select, but when you select the check box you can't toggle it with return.
It is interesting that the home end keys take the user to the start or end of a row when in cell selection and to the start or end of the table when in row selection. Page up and page down always move by a page of rows.
Should there be a story with long content in a cell and no wrap?
When there are nested columns, using the keyboard, I goto the second or last sub column, goto the parent, then back down to the sub column and I'm not at the first child, I'd expect to return to the child I entered from.

**Comment by LFDanLu** [comment] 2020-10-28 20:42
Closing this ticket in favor of the sub issues I made

**Closed by LFDanLu** 2020-10-28 20:42 UTC
Labels: bug, rsp:Table
