### ISSUE TITLE
Clicking below a DateSegment in a react-aria-components DateField / DatePicker focuses the DateSegment

### ISSUE THREAD

**Issue by schurchleycci** [adobe/react-spectrum#7325] opened 2024-11-05 20:56 UTC
### Provide a general summary of the issue here

When you click below a DateSegment in an unfocused DateField / closed DatePicker focuses the DateSegment, even though you're not clicking directly on anything within the DateField or DatePicker. 

### 🤔 Expected Behavior?

Only directly clicking a DateSegment should focus it.

### 😯 Current Behavior

Clicking anywhere below a DateSegment focuses it.

### 🖥️ Steps to Reproduce

See examples in the [DateField](https://react-spectrum.adobe.com/react-aria/DateField.html) and [DatePicker](https://react-spectrum.adobe.com/react-aria/DatePicker.html) docs. The behaviour is present in Chrome and Safari but not Firefox, which works as expected.

### Version

Appears on both react-aria-components 1.2.1 and 1.4.1

### What browsers are you seeing the problem on?

Chrome, Safari

### What operating system are you using?

macOS 15.0.1

**Comment by reidbarber** [comment] 2024-11-06 16:19
Looks like this is a duplicate of https://github.com/adobe/react-spectrum/issues/3164

**Closed by reidbarber** 2024-11-06 16:19 UTC

**Comment by schurchleycci** [comment] 2024-11-06 16:21
Ah, I did a search but I must not have gone back far enough to find that one. Thanks!
