### ISSUE TITLE
Pinch-zoom on Mac OS with Popover opened

### ISSUE THREAD

**Issue by da230896** [adobe/react-spectrum#2700] opened 2021-12-20 18:25 UTC
# 🐛 Bug Report 
When we try to use macbook's trackpad for zooming in and out, using pinch - in and out, then one can observe movement of popover as shown in the gif below:
![My new video project](https://user-images.githubusercontent.com/8996712/146813741-0fa54011-8af1-4a22-b765-db6331849126.gif)

## 🤔 Expected Behavior
Popover shall remain static 

## 😯 Current Behavior
Popover is moving sometimes vertical sometimes horizontal.

## 💁 Possible Solution
Nothing that I can think of right now.

## 🔦 Context
I was trying to create a popover for grouped actions. On its opening user would choose what it may feel reqd.

## 💻 Code Sample
N/A

## 🌍 Your Environment
Since this video was recorded on documentation site it must be the latest one i.e. [December 16 Release](https://react-spectrum.adobe.com/releases/2021-12-16.html) . I could dig up more and found that video was recorded on 7th December thus it seems to be an issue existing in [November 24 Release](https://react-spectrum.adobe.com/releases/2021-11-24.html).  

## 🧢 Your Company/Team
Adobe

**Comment by reidbarber** [comment] 2021-12-22 16:27
Took an initial look at this. It appears that this doesn't occur within an iframe (i.e. storybook, codesandbox). You can see it on the docs, or if you open a codesandbox render in a new window. It also looks like the pinch-zoom is a mousewheel event with `ctrlKey: true` in Chrome/FF/Edge, or a [GestureEvent](https://developer.mozilla.org/en-US/docs/Web/API/GestureEvent) in Safari.

**Comment by atomiks** [comment] 2022-01-14 04:37
Can I suggest https://floating-ui.com/ for positioning? Positioning overlays is an entire area of dedicated focus which on top of the behavioral logic can make it fall by the wayside. This lib handles all cases imaginable, including this one, in a tiny size. Many component libraries use its predecessor, Popper.

Other issues it handles:

- https://github.com/adobe/react-spectrum/issues/2343
- https://github.com/adobe/react-spectrum/issues/2305
- https://github.com/adobe/react-spectrum/issues/2258

**Comment by clementprdhomme** [comment] 2022-10-10 13:06
I have found a similar issue on mobile (Android) with Firefox and Chrome. You can actually replicate using desktop Chrome and turning on the device simulation.

**Environment:**

- Firefox 105.2.0 (Android 10)
- Chromium 106.0.5249.91 (Ubuntu 22.04) with device simulation

**Reproduction steps:**

1. Open the page https://react-spectrum.adobe.com/react-aria/useOverlayTrigger.html#example on Chrome (desktop)
2. Turn on the device simulation (here Galaxy A51)
3. Click the “Open Popover” button

The popover will appear at the expected position:

<img alt="Popover located above the trigger" src="https://user-images.githubusercontent.com/6073968/194871247-237fb60d-cedf-4ff2-b013-24d7b97e953e.png" height="400" />

4. Zoom in using <kbd>SHIFT</kbd> + clicking and dragging
5. Open the popover again

The popover will not be positioned correctly:

<img alt="Popover located way below the trigger and barely visible" src="https://user-images.githubusercontent.com/6073968/194871320-5e2ee444-0d95-4b92-8cd4-e65777de3582.png" height="400" />

**Comment by LFDanLu** [comment] 2023-11-29 23:24
I can't seem to actually reproduce this on Chrome MacOS or on my Android Chrome with pinch zoom using the following pages: 
https://react-spectrum.adobe.com/react-spectrum/DialogTrigger.html#popover
https://react-spectrum.adobe.com/react-aria/Popover.html#example

https://react-spectrum.adobe.com/react-aria/useOverlayTrigger.html#example does reproduce the issue but that page is out of date. Closing for now, but definitely chime in if it still happens for you

**Comment by mischnic** [comment] 2023-11-30 08:43
It also still happens with Comboxbox: https://github.com/adobe/react-spectrum/issues/3678
https://react-spectrum.adobe.com/react-spectrum/ComboBox.html
That probably shares some logic with OverlayTrigger

**Comment by samulisuomi** [comment] 2023-11-30 10:04
> I can't seem to actually reproduce this on Chrome MacOS or on my Android Chrome

Not sure how the docs differ from other apps consuming this lib but you can see this in the Storybook for instance. Please check out the vids in my PR:

> I played around with this today and came up with https://github.com/adobe/react-spectrum/pull/5205

**Comment by LFDanLu** [comment] 2023-11-30 17:39
Thank you for the additional info, reproduced in the Storybook iframe vs the docs vs Combobox. Reopening so we can dig into the difference in behavior across these various examples.

**Comment by tuananhlai** [comment] 2023-12-19 07:18
Is there any possible workaround for this issue at the moment? 🤔

**Comment by LFDanLu** [comment] 2023-12-19 21:04
A possible fix (untested) would be to change our calculated position values so that they are offset by the visualViewport's offsetX/Y as mentioned here: https://github.com/adobe/react-spectrum/pull/5205#issuecomment-1854794637. A workaround would be to use [patch-package](https://www.npmjs.com/package/patch-package) to modify our calculation of the [container rect](https://github.com/adobe/react-spectrum/blob/125d65cc13bc938a299954c017f9026cf1529b70/packages/%40react-aria/overlays/src/calculatePosition.ts#L106-L125) but it would take some experimentation (I haven't looked too closely yet so no idea what else would need to be changed).

**Comment by tuananhlai** [comment] 2023-12-21 05:34
I've decided to rewrite `useOverlayPosition` and `usePopover` using `computePosition` from `@floating-ui/dom` for my local project. Aside from the async nature of this function, it supports most of the use cases of `useOverlayPosition` (auto flip, offset, cross offset, padding, ...). I think we can consider using this library when fixing this issue.

**Comment by snowystinger** [comment] 2023-12-21 05:48
@tuananhlai we've considered doing just that, but we haven't had enough priority to work on it or try it out ourselves. Feel free to open a PR if you have the change to further the discussion!

**Closed** 2024-02-05 20:17 UTC
Labels: bug
