### ISSUE TITLE
onPress seems to not work when clicking around the borders of button in touch devices

### ISSUE THREAD

**Issue by afzalsayed96** [adobe/react-spectrum#1371] opened 2020-12-12 12:40 UTC
# 🐛 Bug Report 

When using `onPress` event handler, there's an area around the borders of button where press action does not seem to work.

## 🤔 Expected Behavior

The hit area of `onPress` should be similar to that of `onClick`

## 😯 Current Behavior

On pressing on the area around button's edges, in touch devices, we see the `:hover` effect but `onPress` event is  not fired.

On the contrary, `onClick` event does get fired in this case.

## 💻 Code Sample

https://codesandbox.io/s/wispy-leftpad-g53jp?file=/src/App.js

![onPress-bug](https://user-images.githubusercontent.com/14029371/101984087-29978b80-3ca5-11eb-8f8f-1f99d03ab975.gif)

**Comment by snowystinger** [comment] 2020-12-12 21:03
I'm guessing that browsers do some fuzzy matching that we are missing. For example, if you put another button right next to this one, and you repeat what you're doing, the new button will be pressed instead.
I'm guessing the reason ours doesn't quite work has to do with our calculation of isOverTarget. You can tell a little because if you put the center of the touch cursor over the button it will work, but 1px outside and it stops. 

It does seem as though there is a real life issue with this though, which is in iOS Safari. It displays the same issue.
I'll try to debug a bit further on Monday, though that shouldn't stop anyone else from taking a crack at it.
Relevant code for iOS Safari I think is https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/usePress.ts#L382
and https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/usePress.ts#L434


Side notes, this doesn't happen in the Safari responsive mode, they don't use a fuzzy matching cursor. No problems in FF responsive mode, no fuzzy matching cursor.

**Comment by afzalsayed96** [comment] 2020-12-14 09:09
@snowystinger I can see the exact same behaviour in Chrome for Android which confirms this is not a glitch in browser's touch screen emulation.

Another bug I've seem to have caught is when an element inside button transforms and spills out of the boundaries of button. In such cases `onClick` event triggers on clicking the element portion that's outside of the boundaries of button. As opposed to the case with `onPress` where it isn't triggered.

See the second button for repro: https://codesandbox.io/s/wispy-leftpad-g53jp?file=/src/App.js

**Comment by snowystinger** [comment] 2020-12-14 22:29
So this actually appears to be a duplicate of this issue that another team mate reminded me of. https://github.com/adobe/react-spectrum/issues/1061 and has most of the info I think we'd need.
I'm closing this one in favor of 1061. Please feel free to reopen if that's not the case.

**Closed by snowystinger** 2020-12-14 22:29 UTC
Labels: bug
