### ISSUE TITLE
react-aria useSelect broken on iOS and safari 12

### ISSUE THREAD

**Issue by mitchellwarr** [adobe/react-spectrum#2686] opened 2021-12-15 01:03 UTC
# 🐛 Bug Report 

on iOS 12 the overlays and the useSelect do not work. Either they dont open or they close soon after opening.

https://react-spectrum.adobe.com/react-aria/useSelect.html

## 🤔 Expected Behavior

I expect the select box to open

## 😯 Current Behavior

The select box either doesn't open, or opens for a second after closing.

On a local iPad, if you held down you finger for a second or so it did work. Maybe this is due to a scroll event closing the select box?

## 💁 Possible Solution

Maybe this is due to a scroll event closing the select box?

## 🔦 Context

This is happening on the example page of react-aria

## 💻 Code Sample

The example page at https://react-spectrum.adobe.com/react-aria/useSelect.html

## 🌍 Your Environment

BrowserStacks:

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | The example page at https://react-spectrum.adobe.com/react-aria/useSelect.html |
| Browser          | safari |
| Operating System | iOS 12.9 ipad |

Local:

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | The example page at https://react-spectrum.adobe.com/react-aria/useSelect.html |
| Browser          | safari and chrome |
| Operating System | iOS 12.5.5 ipad |

**Comment by reidbarber** [comment] 2021-12-15 17:46
Confirmed on iOS Simulator. Not seeing any warnings or errors in the console.

https://user-images.githubusercontent.com/8961049/146237866-8efc2e9d-fddb-4ea1-acf6-d93786e7bef6.mov

**Comment by snowystinger** [comment] 2021-12-22 20:38
Given that the example in our docs also makes use of useOverlay, I think we can assume these are the same issue. Just one level of indirection.
I'm going to close this one with the same remarks as the linked PR, which is that we'd be happy to accept a fix for this but we won't be picking this up ourselves due to the limited area of effect (only iPad iOS 12) of this bug. If anyone opens a PR for it, I'll reopen. We're also happy to discuss strategy here or in the linked issue, whichever makes more sense.

**Closed by snowystinger** 2021-12-22 20:38 UTC
Labels: bug

**Comment by mitchellwarr** [comment] 2021-12-22 21:08
@snowystinger in that case, the support browsers section of the docs needs to be updated as it states react aria is supported on safari 12+ on iPadOS

**Comment by snowystinger** [comment] 2021-12-22 21:22
Ah, thank you, I'd forgotten about that list. Updating here https://github.com/adobe/react-spectrum/pull/2704
We probably need to update some of those others, but for now I'm just going to do the one that is causing an issue.
