### ISSUE TITLE
Drag-and-drop on Safari prevents Buttons activating

### ISSUE THREAD

**Issue by staticshock** [adobe/react-spectrum#7234] opened 2024-10-23 00:37 UTC
### Provide a general summary of the issue here

RAC Button's onPress handler does not fire the first time a button is pressed after a drag-and-drop action in Safari.

### 🤔 Expected Behavior?

Buttons should not care if a drag-and-drop action was recently performed or not. This is working correctly on Chrome, but is broken on Safari.

### 😯 Current Behavior

The first button press (anywhere on the page) after a drag-and-drop action is completely ignored. The button has to be pressed _again_ in order for the press event to fire.

### 💁 Possible Solution

🤷 I have not investigated the root source

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/condescending-microservice-3vxs67

1. Load this in Safari and open the dev tools
2. Drag something
3. Click da button. Notice a lack of log entry in the console.
4. Click it again. Notice that this time it logs an entry to the console.

### Version

"react-aria-components": "^1.3.2"

### What browsers are you seeing the problem on?

Safari

### What operating system are you using?

macOS Sonoma

**Comment by snowystinger** [comment] 2024-10-23 00:45
Duplicate of https://github.com/adobe/react-spectrum/issues/2322

**Closed by snowystinger** 2024-10-23 00:45 UTC

**Comment by staticshock** [comment] 2024-10-23 14:53
That issue hasn't gotten traction for 3 years...

**Comment by snowystinger** [comment] 2024-10-23 19:08
unfortunately, it's a pretty tough one and workarounds we've tried have had unfortunate side effects because it's safari's bug, feel free to chime in on their bug https://bugs.webkit.org/show_bug.cgi?id=202287

We welcome PRs addressing issues in new ways for discussion. Thank you for your understanding.
