### ISSUE TITLE
TableView maxHeight results in visual bug when rows overflow height

### ISSUE THREAD

**Issue by sirugh** [adobe/react-spectrum#2364] opened 2021-09-21 15:56 UTC
# 🐛 Bug Report 

`TableView` `maxHeight` results in visual bug when table rows overflow max height. Column headers are "behind" table with a few pixels of text showing above the table.

## 🤔 Expected Behavior

Column headers are shown above table at all times.

## 😯 Current Behavior

Empty Table
![image](https://user-images.githubusercontent.com/1278869/134204728-7d9156f9-9dd7-4a87-b3fd-17c22c94315f.png)

One Item
![image](https://user-images.githubusercontent.com/1278869/134204751-1082857e-0b5e-4748-87ff-1fc140edf22c.png)

Many Items
![image](https://user-images.githubusercontent.com/1278869/134204811-161d8933-3223-4025-8659-ecb8aefddba8.png)

As you can see, in the "many items" screen shot, column headers are "behind" table with a few pixels of text showing above the table.

## 🔦 Context

Using min/max height would be a better UX than having a large empty or unfilled table.

## 💻 Code Sample

```jsx
<TableView
    minHeight="size-3000"
    maxHeight="640px"
>
    {/* table view contents */}
</TableView>
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.14.0
| Browser          | Chrome Version 93.0.4577.82 (Official Build) (x86_64)
| Operating System | Mac OSX 11.6 (20G165)

## 🧢 Your Company/Team

Adobe/Commerce Channels

**Comment by snowystinger** [comment] 2021-09-21 20:21
Hey! thanks for the issue.
So part of the issue is that the TableView is a virtualized component, meaning it must have a height and it doesn't change its height in response to adding/removing children. The best thing to do is to allocate space for it beforehand, either by giving it a height explicitly, or by using Flex or Grid. See https://react-spectrum.adobe.com/react-spectrum/TableView.html#layout

**Comment by sirugh** [comment] 2021-09-21 23:00
Interesting - I think the `maxHeight` prop confuses me then. The desired UX we're going for is one where there's an empty state with an image (as in my above screenshot) but then the table grows with the rows until it reaches a maximum height. Looking at the link you provided, it does seem like the flex property should work so I will give that a shot.

**Comment by ktabors** [comment] 2024-04-11 22:16
Closing and we can reopen if it's still a problem.

**Closed by ktabors** 2024-04-11 22:16 UTC
Labels: waiting
