### ISSUE TITLE
[combobox] behavior of Home and End keys

### ISSUE THREAD

**Issue by stefanprobst** [adobe/react-spectrum#1436] opened 2021-01-04 10:27 UTC
# ❔ Question

i'm trying to build a searchbox which accepts arbitrary text input and displays autosuggestions in a listbox popup.
is this a usecase react-spectrum's [`Combobox`](https://react-spectrum.adobe.com/react-spectrum/ComboBox.html) supports? if yes, i have found the behavior of <kbd>Home</kbd> and <kbd>End</kbd> surprising in this case: when the listbox popup is closed, <kbd>Home</kbd> and <kbd>End</kbd> will move the cursor in the `<input>`. however when the popup is open, <kbd>Home</kbd> and <kbd>End</kbd> will *not* move the cursor in the input, but the selection in the popup.

## 🔦 Context

the relevant passages in the [wai-aria](https://www.w3.org/TR/wai-aria-practices-1.2/#combobox-keyboard-interaction) authoring practices are these (i think):

When focus is in the combobox:

- If the combobox is editable, it supports standard single line text editing keys appropriate for the device platform (see note below).

When focus is in a listbox popup:

- Home (Optional): Either moves focus to and selects the first option or, if the combobox is editable, returns focus to the combobox and places the cursor on the first character.
- End (Optional): Either moves focus to the last option or, if the combobox is editable, returns focus to the combobox and places the cursor after the last character.

i'm not 100% sure how to interpret this, but it looks like there should (optionally) be a combobox behavior, where <kbd>Home</kbd> and <kbd>End</kbd> moves the cursor in the `<input>` when the popup is open. this also seems to be the behavior of e.g. the top searchbox here on github.com, or the google search input.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | combobox alpha
| Browser          | Firefox 84
| Operating System | Ubuntu 20.04

**Comment by stefanprobst** [comment] 2021-01-04 11:43
the [material-ui Autocomplete](https://material-ui.com/components/autocomplete/#free-solo) seems to handle this via a separate `handleHomeEndKeys` prop.

**Comment by snowystinger** [comment] 2021-01-04 18:14
I think I need some clarification.

I tried out the material ui component, when the popup list is open, home and end in that example will go to the top and bottom of the list respectively and not adjust cursor position.
When the popup list is closed, home and end scroll the entire page and does not adjust cursor position.

This appears to be the same behavior we have in React Spectrum.

I think your ask is this? According to the notes above, both libraries should have a little bit of handling for when focus is in the text input but the popup is closed, so that home and end move the cursor but don't scroll the page.

**Comment by stefanprobst** [comment] 2021-01-04 19:46
sorry for being so unclear - i'll try to illustrate with the `allowsCustomValue` example from the `ComboBox` storybook:

- when the listbox popup is closed, <kbd>Home</kbd> and <kbd>End</kbd> move the cursor in the text input field. this is expected behavior, matches other combobox implementations, and is refered to in the authoring practices as "supports standard single line text editing keys":

https://user-images.githubusercontent.com/20753323/103571695-a811d280-4ecb-11eb-89c4-b4c094410a13.mp4

- when the listbox popup is open (and the text input has focus), pressing <kbd>Home</kbd> and <kbd>End</kbd> will *not* move the cursor in the textt input. but move the selection in the popup:

https://user-images.githubusercontent.com/20753323/103572012-2e2e1900-4ecc-11eb-907c-1356e40ecf7d.mp4

this behavior matches e.g. the implementation in `reach-ui` combobox, or the default Material UI `Autocomplete` behavior. however the Material UI `Autocomplete` also has a `freeSolo` mode (which maps to `allowsCustomValue` in `react-spectrum`) which defaults to a different behavior: <kbd>Home</kbd> and <kbd>End</kbd> will move the cursor in the text input when the popup is open. see [this codesandbox](https://codesandbox.io/s/materialui-autocomplete-lgx20) for illustration.

this is also the behavior i'm trying to replicate with `react-spectrum`'s `ComboBox` - it's also what other search inputs with autosuggestions on the web do, e.g. google:

https://user-images.githubusercontent.com/20753323/103572755-6124dc80-4ecd-11eb-85a4-ad0acc3a203e.mp4

**Comment by snowystinger** [comment] 2021-01-04 19:53
Ah, thanks for the clarification! I'll start a conversation with the team and design

**Comment by snowystinger** [comment] 2021-01-13 20:37
Hey, so I talked to our team and accessibility expert. Accessibility says "When interacting with the text content of the combobox input field, Home or End should navigate to the start or end of text content, but when interacting with the list box, the Home or End keys should navigate the list."
We've concluded that while the menu is open, a user is interacting with it because it's impossible to know if it's one or the other. As a result, we're working as intended in that regard.
The last piece of the puzzle is the scrolling behavior where the entire container of the combobox will scroll if it's able to on the first press of home/end. This should be fixed so that the scrolling doesn't happen and the cursor moves to the correct spot immediately.

I'm going to close this Issue and open a new one to address the scrolling.

**Closed by snowystinger** 2021-01-13 20:37 UTC
Labels: rsp:ComboBox

**Comment by stefanprobst** [comment] 2021-01-14 09:04
Thanks for asking, and thanks for the info!

To clarify: react-spectrum's Combobox does not plan to support behavior like the google search box. Would you accept a PR to *optionally* toggle such behavior (similar to material-ui's handleHomeEndKeys prop)?
