### ISSUE TITLE
Table with selectionMode multiple doesn't work with styled checkboxes.

### ISSUE THREAD

**Issue by cjevning** [adobe/react-spectrum#4211] opened 2023-03-15 21:03 UTC
# 🐛 Bug Report 

Tables built with useTable in multiple selection mode aren't able to make any selections by clicking custom styled Checkbox components built with useCheckbox.

## 🤔 Expected Behavior

Table selectionMode="multiple" should function as it does [in the docs](https://react-spectrum.adobe.com/react-aria/useTable.html#multiple-selection).

## 😯 Current Behavior

Two separate issues are visible:

1. The "select-all" checkbox seemingly receives no click event & doesn't do anything.
2. All other selection checkboxes toggle on & off immediately and thus can't select anything. Clicking anywhere else in the row selects/unselects as expected.

## 💁 Possible Solution

The select all issue seems to happen because this [preventDefault](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/interactions/src/usePress.ts#L268) call prevents the label from forwarding the event on to the underlying checkbox. The other checkboxes seem like both the checkbox behavior & the row behavior are triggering & toggling the selection twice.

## 🔦 Context

We've currently got a separate workaround in place for each issue. On our selection checkboxes, we're setting `pointer-events: none;` to allow the row to handle all selection toggling. On our select-all checkbox, we're forcing the onChange when the heading is clicked:

```
  <th
    ref={ref}
    {...columnHeaderProps}
    onClick={(e) => {
      checkboxProps.onChange(!checkboxProps.isSelected);
      columnHeaderProps.onClick(e);
    }}
  >
    <Checkbox
      label={checkboxProps["aria-label"]}
      {...checkboxProps}
    />
  </th>
```

## 💻 Code Sample

[This codesandbox](https://codesandbox.io/s/ancient-microservice-nfx094?file=/src/App.js) showcases both issues using the latest [Table](https://react-spectrum.adobe.com/react-aria/useTable.html#example) & [styled Checkbox](https://react-spectrum.adobe.com/react-aria/useCheckbox.html#styling) examples from the docs.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | latest |
| Chrome          | 111.0.5563.64 |
| macOS | 13.1 (22C65) |

**Comment by snowystinger** [comment] 2023-03-15 21:35
closing as a dupe of https://github.com/adobe/react-spectrum/issues/2383

**Closed by snowystinger** 2023-03-15 21:35 UTC
