### ISSUE TITLE
useSelectableCollection unintentionally breaks delegated Escape handling

### ISSUE THREAD

**Issue by Chudesnov** [adobe/react-spectrum#2407] opened 2021-10-01 16:08 UTC
# 🐛 Bug Report 

**useSelectableCollection** provides useful navigation and selection management commands for widgets like context menus, comboboxes, grids, etc. . Most of those commands override some native browser behaviours, therefore `event.preventDefault()` is called when the command is triggered. However, event handling for Escape key specifically is done differently from others and does not check for any props of the hook and calls `event.preventDefault()` unconditionally: 

https://github.com/adobe/react-spectrum/blob/e14523fedd93ac1a4ede355aed70988af572ae74/packages/%40react-aria/selection/src/useSelectableCollection.ts#L230-L235

## 🤔 Expected Behavior

Browser event handling (or any other handling based on [`event.defaultPrevented`](https://developer.mozilla.org/en-US/docs/Web/API/Event/defaultPrevented)) for the Escape key should depend on `disallowEmptySelection` being set to false or any other flag passed to the `useSelectableCollection` hook.

## 😯 Current Behavior

`event.preventDefault()` for Escape presses is called unconditionally.

## 💁 Possible Solution

Change the code above to:

```js
      case 'Escape':
        if (!disallowEmptySelection) {
          e.preventDefault();
          manager.clearSelection();
        }
        break;
```

Another (and probably better) way to fix it would be to check for both `manager.isEmpty` and `disallowEmptySelection`, so that any Escape handlers outside of the collection container could still kick in after everything is deselected:

```js
      case 'Escape':
        if (!disallowEmptySelection && !manager.isEmpty) {
          e.preventDefault();
          manager.clearSelection();
        }
        break;
```

Adding a different flag as an option for useSelectableCollection and checking it in addition to disallowEmptySelection when handling a common hotkey like Escape is also an option worth considering.

## 🔦 Context

This would be ok in most cases, however, if some code running on the same page outside of React Spectrum relied on `event.defaultPrevented` to trigger some custom behaviour only in case when no other consumer in JS land has handled the event, that code would break. That's exactly our issue. We use a delegated event handler and only run our custom code for Escape when `event.defaultPrevented` is false (and then call `.preventDefault()` ourselves if that code actually did something useful and we don't want to trigger closing the full screen view or something).

## 💻 Code Sample

[Example on CodeSandbox](https://codesandbox.io/s/react-aria-selection-useselectablecollection-and-escape-nspkp?file=/src/App.js)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/selection   | 3.6.0
| Browser          | any
| Operating System | any

## 🧢 Your Company/Team

Not part of Adobe :)

## 🕷 Tracking Issue (optional)

Not available publicly.

**Comment by LFDanLu** [comment] 2021-10-06 18:14
This seems reasonable. Another issue that may arise though is that the keydown event propagation may get stopped at the collection child level if the child has press handlers from `usePress` + `useSelectableItem`. In that case we would want to continue propagation.

**Comment by longzheng** [comment] 2023-06-13 02:41
Just want to give a bump on this issue as we also ran into this when using `useListBox` inside of a popover.

We intentionally set `disallowEmptySelection` on the `useListBox` with the expectation that the "Escape" key would no longer clear the selection.

The popover receives the `Escape` keyboard event however is ignored because it checks `event.defaultPrevented`, which is set to `true` because of `e.preventDefault();` being unconditionally called https://github.com/adobe/react-spectrum/blob/6a858e3663aea1fb2b2a2ca5d2b3fb4ddeae99e4/packages/%40react-aria/selection/src/useSelectableCollection.ts#L231

The proposed solution from OP makes sense to me, however I have limited understanding of how this change might interact with other components that depend on `useSelectableCollection`. It would be much appreciated if this behaviour could be fixed.

In the meantime we had to workaround by manually dispatching a new event.

```tsx
<div
    onKeyDown={(e) => {
        if (e.key === 'Escape' && e.currentTarget.parentElement) {
            e.currentTarget.parentElement.dispatchEvent(
                new KeyboardEvent('keydown', { key: 'Escape', code: 'Escape', bubbles: true }),
            );
        }
    }}
```

**Comment by paroxyzm** [comment] 2024-02-23 15:06
Hello!
We ran into an issue with `preventDefault` when using `<Table>` component from 'react-aria-components' package and `<Tooltip>` from radix-ui. 
Radix-ui seems to be checking the 'defaultPrevented' field on the event, and hence, not closing the `<Tooltip/>` when used inside `<Table/>`. (see [here](https://github.com/radix-ui/primitives/blob/c31c97274ff357aea99afe6c01c1c8c58b6356e0/packages/react/dismissable-layer/src/DismissableLayer.tsx#L108)).

I created a reproducible [scenario](https://codesandbox.io/p/sandbox/blazing-fog-zgsy5w?file=%2Fsrc%2FApp.js%3A52%2C23) 
Steps to reproduce:
1) navigate via keyboard to the buttons inside the `<Table/>`
2) press ESC - the tooltip won't disappear

As a comparison, there is also a tooltip outside the `<Table>` component which is closing without issues.

What would be needed to fix this bug?

Thank you!

**Closed** 2024-03-24 22:06 UTC
Labels: bug
