### ISSUE TITLE
Add `main` as a wrapper for story content in storybook iframe template

### ISSUE THREAD

**Issue by majornista** [adobe/react-spectrum#1268] opened 2020-11-12 19:04 UTC
I think we should add `main` as a wrapper for story content in the storybook iframe template. That way, the iframe page will not throw "no main landmark" error when it is rendered a standalone page outside for storybook.

_Originally posted by @majornista in https://github.com/adobe/react-spectrum/pull/1237#r522321213_

**Comment by lmekala** [comment] 2021-12-09 02:46
@dannify how do I reproduce "no main landmark" error in  storybook?

**Comment by dannify** [comment] 2021-12-10 00:45
If you open a storybook page in it's own page (icon, top right that is label "open canvas in new tab"), you can use aXe dev tools to scan the page. Currently you will see the error mentioned above for all stories.
https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd
@majornista is that correct?

**Comment by lishichengyan** [comment] 2022-03-22 00:51
Do we still want this change? I can pick it up if needed! 🙋‍♂️

**Comment by lishichengyan** [comment] 2022-04-08 07:42
could we close the issue since the pr has been merged? thanks!

**Closed** 2022-04-08 14:31 UTC
Labels: good first issue, storybook
