### ISSUE TITLE
ActionBar bugs

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#2319] opened 2021-09-10 20:50 UTC
# 🐛 Bug Report 

Two potentially related issues seen in ActionBar default story:

- Safari RTL locales are broken, the checkbox is shifted over in the TableView
- Changing locale and then trying to click checkall causes the page to crash with `TypeError: Cannot assign to read only property 'overflow' of object '#<Object>'`

Sometimes hard to reproduce on the branch built version, definitely reproducible on local, and it interferes with debugging other issues.

## 🤔 Expected Behavior

It shouldn't crash and all checkboxes should be aligned in the correct place

## 💁 Possible Solution

- No ideas for the checkbox placement right now.
- Cloning the style object and editing that does fix the issue but defeats the purpose of the cache.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment] 2021-09-10 23:30
Note:
The type error can be reproduced locally in storybook for TableView but not in the built storybook. To reproduce, go to the async loading story -> switch to hebrew locale -> attempt to sort a column.

Preliminary debugging:
The issues seems to happen when attempting to set the overflow style for the 'row-header-column' [here](https://github.com/adobe/react-spectrum/blob/e14523fedd93ac1a4ede355aed70988af572ae74/packages/%40react-spectrum/table/src/TableView.tsx#L119-L122). This specifically happens for the **cached** style object returned by [here](https://github.com/adobe/react-spectrum/blob/e14523fedd93ac1a4ede355aed70988af572ae74/packages/%40react-aria/virtualizer/src/VirtualizerItem.tsx#L54). For some reason the overflow property is readonly even though logging out that property before it is added to the weakmap returns that it is not read only. 

Note that this isn't limited to the 'row-header-column' and the bug still happens if 'selectionMode="none"'

**Comment by reidbarber** [comment] 2022-10-14 21:52
Neither me or @snowystinger could reproduce this. This likely got fixed by something else, or a Safari update since it was opened.

**Closed by reidbarber** 2022-10-14 21:52 UTC
Labels: rsp:ActionBar
