### ISSUE TITLE
Deploy to Netlify failed due to @react-spectrum/meter module CSS syntax error

### ISSUE THREAD

**Issue by luoqiuyun** [adobe/react-spectrum#3044] opened 2022-04-16 21:43 UTC
# 🐛 Bug Report 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by luoqiuyun** [comment] 2022-04-16 22:00
![image](https://user-images.githubusercontent.com/15234447/163692299-b43ba2e8-3bd3-4181-a10f-3c7dce9301dd.png)

Expected: to be able deploy
Current: not able to deploy due to @adobr/react-spectrum CSS bugs
Possible solution: follow the syntax var( <custom-property-name> , <declaration-value>? )
                            the fallback need to be a <declaration-value> not a nested <custom-property-name> with fallback again
An suggested example: var(--foo, red, blue)
not suggested:  var(--foo, var(--another-foo, var(--another-foo-foo,  var(--another-foo-foo-foo, ...) )))

I suggest you to read this: https://developer.mozilla.org/en-US/docs/Web/CSS/var

Please resolve this asap. Thanks

**Comment by snowystinger** [comment] 2022-04-16 22:00
Hey, thanks for the ticket. Any chance you could provide some more information about what's going? Logs, your build config, anything you've tried or changed recently?

**Comment by luoqiuyun** [comment] 2022-04-16 22:11
![image](https://user-images.githubusercontent.com/15234447/163692776-66fd9b12-7e86-43f2-b800-4195b8c808d3.png)

My project (JAMstack) work greatly on local. I try to deploy it on Netlify, but failed due to adobe/react-spectrum CSS bugs. This is the only blocker. You can have a look at my code, for sure not bugs. https://github.com/luoqiuyun/react-dog-breeds-search

**Comment by luoqiuyun** [comment] 2022-04-16 22:28
![image](https://user-images.githubusercontent.com/15234447/163693192-4b738e6d-7ed4-4357-a5fc-33b0bcc299b2.png)

Here is the bug(s)

**Comment by luoqiuyun** [comment] 2022-04-16 22:41
Thanks for getting back to me. As I said my project (JAMstack) work greatly on local.
 I try to deploy it on Netlify, but failed due to adobe/react-spectrum CSS bugs, the only blocker for the deploy.

You can take a look at my code, for sure not bugs. https://github.com/luoqiuyun/react-dog-breeds-search

I've tried many times. I also took the successfully deployed another project as the app base. Still, the same error message connected to Adobe React-Spectrum.

Here is a complete screenshot of the Netlify building log:

[cid:e61b9983-e612-49e6-ba44-9e7c63ac1b5d]

I found the bug in the ***@***.***/meter/dist/main.css

[cid:6a034759-2b53-42fb-b3df-ded211252bae]


Hope it will be resolved asap.

Thanks.

________________________________

**Comment by snowystinger** [comment] 2022-04-18 21:45
So CSS variables are allowed to fallback in the manner we use. Please see https://jsfiddle.net/cnkj5263/1/

This is also detailed here https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#custom_property_fallback_values

I haven't used Netlify before, but does it have a configurable CSS loader? if so, please tell it to only perform the most basic loader on the CSS from node_modules, not transpilation. We've already run a few transpilers on it so it will work in all browsers.

You'll likely need to customize the netlify webpack config to do this.

**Comment by devongovett** [comment] 2022-04-20 14:37
Netlify is just hosting I think. The issue appears to be with `react-scripts`. I can reproduce it with react-scripts v4, but not with react-scripts v5. Have you tried upgrading?

**Comment by luoqiuyun** [comment] 2022-04-20 15:00
I started with react-scripts v5. That was where the issue appeared first. Then I down grade to react-scripts v3.4.1.
Anyways, I picked up a earlier version of adobe/react-spectrum v3.0.0. everything works for react-scripts v3.4.1 + react-spectrum v3.0.0

Yesterday, I start another app from scratch, wanted to see how this time works. I believe some of the libraries has been silently updated. react-spectrum works for the building this time. But this time, "react-image-lightbox" doesn't work with react-spectrum anymore. The lightbox worked perfectly before with react-scripts v5 with my first attempt for this app. I believe this is a new bug with adobe/react-spectrum.

[cid:8a4b2c25-1407-451d-a464-3ffcb88893f9]


When I slightly resize the app window, the lightbox pic shows up

[cid:47cc8ee4-cf71-4c18-bf70-5a3d99419b03]

________________________________

**Comment by Fankhauser-Dominik** [comment] 2022-04-20 18:57
So is it not possible to use React Spectrum with React Scripts v4?

**Comment by devongovett** [comment] 2022-04-21 00:08
The underlying issue is in postcss-custom-properties: https://github.com/postcss/postcss-custom-properties/issues/161. react-scripts v4 depended on a very old version of this, see https://github.com/facebook/create-react-app/issues/10130. v5 upgrades this dependency, so it is fixed there.

I verified that it is possible to work around while still using react-scripts v4 if you use an npm override, or yarn resolution to override the version of postcss-custom-properties that is installed. For npm, add this to your package.json:

```json
"overrides": {
  "postcss-custom-properties": "^12"
}
```

or for yarn, use this:

```json
"resolutions": {
  "postcss-custom-properties": "^12"
}
```

Regardless, this isn't a bug in React Spectrum so I'm going to close this issue.

**Closed by devongovett** 2022-04-21 00:08 UTC

**Comment by luoqiuyun** [comment] 2022-04-21 04:44
ok. will try react-scripts v4. thanks.
________________________________

**Comment by vdua** [comment] 2022-05-10 16:32
@luoqiuyun Were you able to make it work. We are getting the same error but due to a different reason. Created a separate issue for that

https://github.com/adobe/react-spectrum/issues/3115

**Comment by luoqiuyun** [comment] 2022-05-11 00:20
It has been working. no issue.
________________________________

**Comment by luoqiuyun** [comment] 2022-10-11 07:30
1.  Spectrum with react-scripts v3:

React App (react-dog-breeds-search.netlify.app)<https://react-dog-breeds-search.netlify.app/>
React App<https://react-dog-breeds-search.netlify.app/>
Web site created using create-react-app
react-dog-breeds-search.netlify.app


  1.  Spectrum with react-scripts v5:

React App (curious-chimera-8d88fd.netlify.app)<https://curious-chimera-8d88fd.netlify.app/>
React App<https://curious-chimera-8d88fd.netlify.app/>
Web site created using create-react-app
curious-chimera-8d88fd.netlify.app


  1.  Spectrum with react-scripts v4 (not tried)


________________________________

**Comment by luoqiuyun** [comment] 2022-10-11 08:53
Tried it again with "react-image-lightbox". Everything works now!
I was using ***@***.***/table": "^3.1.6". now I'm using ***@***.***/react-spectrum": "^3.16.5" only.
________________________________
