### ISSUE TITLE
RAC Menu usability issue on mobile due to lack of tray feature

### ISSUE THREAD

**Issue by jakubriedl** [adobe/react-spectrum#6691] opened 2024-07-12 03:12 UTC
### Provide a general summary of the feature here

React Aria Components Menu doesn't have Tray functionality which causes usability issue on mobile devices. React Spectrum does have that and even calls it out in documentation

> [Trays](https://react-spectrum.adobe.com/react-spectrum/Menu.html#trays)
On mobile, Menus automatically display in a tray instead of a popover to improve usability.

Would be great if RAC also had this feature so Menus are usable on mobile devices.

### 🤔 Expected Behavior?

It should work the same as in React Spectrum, Menu should automatically render into tray on mobile devices instead of Popover. Or there should be at least a way how to do that manually from user land.

### 😯 Current Behavior

No trays functionality in RAC at all.

### 🔦 Context

Accessibility and usability on all devices are top priority for us, and a reason why we picked RAC as base for our components. Unfortunately without this feature Menus with Submenus fail on 400% zoom.

**Comment by snowystinger** [comment] 2024-07-12 03:14
Thanks for the issue, closing as a duplicate of https://github.com/adobe/react-spectrum/issues/3816

**Closed by snowystinger** 2024-07-12 03:14 UTC
