### ISSUE TITLE
Can't use VisuallyHidden in Next.js

### ISSUE THREAD

**Issue by adelnizamutdinov** [adobe/react-spectrum#788] opened 2020-07-19 10:22 UTC
# 🐛 Bug Report 

Importing 'VisuallyHidden' in Next.js gives the following error: https://github.com/vercel/next.js/blob/master/errors/css-npm.md

## 🤔 Expected Behavior

Other components work just fine, so I expected `VisuallyHidden` to work too

## 😯 Current Behavior

Compilation error with Next.js https://github.com/vercel/next.js/blob/master/errors/css-npm.md

## 💁 Possible Solution

Not very experienced with frontend 😞

## 🔦 Context

Creating custom checkboxes and stuff

## 💻 Code Sample

```jsx
import {VisuallyHidden} from '@react-aria/visually-hidden'
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.0.2
| Browser          | Chromium 84
| Operating System | macos 10.15.5

## 🧢 Your Company/Team

https://listenbox.app/

**Comment by devongovett** [comment] 2020-07-19 16:17
Duplicate of #760.

**Closed** 2020-07-19 16:17 UTC
