### ISSUE TITLE
SSRProvider causes an error when conditionally rendering an Overlay (Next.js)

### ISSUE THREAD

**Issue by christofferbergj** [adobe/react-spectrum#3787] opened 2022-11-24 12:50 UTC
# 🐛 Bug Report 

When wrapping the whole application with `SSRProvider` and then conditionally rendering an `Overlay` or `OverlayContainer` component with the `useOverlayTriggerState` state hook, an Unhandled Runtime Error is thrown. 

```
Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'contains')
```

It doesn't happen when the `SSRProvider` is removed in `_app.tsx`. 

I've tried all sorts of different things like reimplementing a Modal in different ways with react-aria. I've followed the official documentation etc. It all seems to be tied to the `SSRProvider` component somehow. I don't understand the code well enough to find a solution myself. 

## 🤔 Expected Behavior

I expect the `SSRProvider` not to cause unhandled runtime errors when conditionally rendering react-aria components. 

## 😯 Current Behavior

Conditionally rendering the `Overlay` component from `react-aria` causes an Unhandled Runtime Error.

```
Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'contains')

Call Stack
eval
node_modules/@react-aria/overlays/dist/module.js (1102:0)
Array.some
<anonymous>
MutationObserver.eval
node_modules/@react-aria/overlays/dist/module.js (1102:0)
```

## 💻 Code Sample

The code sample is a standard Nextjs setup. 
Relevant files are `components/modal.tsx` and `pages/index.tsx`. 
https://codesandbox.io/p/sandbox/react-aria-conditional-overlay-ssrprovider-7rvohm?file=%2Fpages%2Findex.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.21.0
| react-stately   |  3.19.0
| Browser  | Chrome
| Operating System | Macbook Pro, Ventura 13.0.1

**Comment by reidbarber** [comment] 2022-11-25 17:56
I confirmed this in our [Next.js test app build](https://reactspectrum.blob.core.windows.net/reactspectrum/810579b671791f1593108f62cdc1893de3a220e3/verdaccio/next/index.html) too. You can see it if you open the ComboBox and check the console. Not seeing it in any other React Spectrum overlays interestingly.

We can fix this with a change to `node?.contains` here:

https://github.com/adobe/react-spectrum/blob/168ca5a5cd53589bae6620fba1602e18240efc46/packages/%40react-aria/overlays/src/ariaHideOutside.ts#L97

but we probably need to figure out why that ref is null for a render in the first place.

**Comment by mryechkin** [comment] 2022-11-29 16:57
Seeing this issue as well when running a [useComboBox](https://react-spectrum.adobe.com/react-aria/useComboBox.html) example in Next.

**Comment by jokull** [comment] 2022-12-07 10:20
Getting this too, here's another minimal reproduction if helpful. https://github.com/jokull/nextjs-react-aria-bug

**Comment by mangej** [comment] 2022-12-19 09:43
I get the same error in Remix

```
ariaHideOutside.ts:97 Uncaught TypeError: Cannot read properties of null (reading 'contains')
    at ariaHideOutside.ts:97:64
    at Array.some (<anonymous>)
    at MutationObserver.<anonymous> (ariaHideOutside.ts:97:46)
```

**Comment by Eldraed** [comment] 2022-12-22 16:07
Hello there,

I have also encountered this issue, I think that it might be interesting to avoid crash when a reference is null or undefined in `ariaHideOutside` helper.
This error is currently caused by the `Overlay` component and the `portalContainer`, as you can see here : https://github.com/adobe/react-spectrum/blob/86b9d3d0564244215a73c3bd18edad53078c4f3b/packages/%40react-aria/overlays/src/Overlay.tsx#L37 by default `portalContainer` is set to `null` when `isSSR` is true.
When we are wrapping our application in `SSRProvider`, the hook `useIsSSR` always return `true` at first, then `false` after passing the `useLayoutEffect` inside the `if` condition instead of being false since the beginning. That switch between true and false is for me the main issue behind all of this.

I'm not enough aware about SSR constraints and the system used behind `SSRProvider` here, but can't we avoid the state change in this hook due to rerender after setting the state ? I would have suggest to replace this line : https://github.com/adobe/react-spectrum/blob/86b9d3d0564244215a73c3bd18edad53078c4f3b/packages/%40react-aria/ssr/src/SSRProvider.tsx#L94
by something like :`let [isSSR, setIsSSR] = useState(typeof window === 'undefined' && isInSSRContext);` but i'm pretty sure that this is not as easy as that 😛

I currently have found a workaround since i'm using react-aria hooks, this is to set a `portalContainer` ref on `Overlay` component, by doing that, you avoid the `null` set by `isSSR`.

**Comment by sephi-dev** [comment] 2022-12-26 09:09
Same error here with same stack 👀

**Comment by Javimtib92** [comment] 2022-12-31 09:25
I'm able to replicate the same error as well

**Comment by VERSAYANA** [comment] 2023-02-01 08:40
Is there any temporary solution for this?

**Comment by drivasperez** [comment] 2023-02-02 15:11
Here's a dirty workaround that seems to work:

```tsx
const Modal = (props) => {
  // Callback ref instead of `useRef`.
  const [ref, setRef] = React.useState<null | HTMLDivElement>(document.createElement("div"));
  // `useModalOverlay` expects it to be in the shape of a normal ref.
  const { modalProps, underlayProps } = useModalOverlay(props, state, {current: ref});

  // /* ... */

  return (
    <Overlay>
      <div className={"overlay"} {...underlayProps}>
        <div
          {...modalProps}
          className="modal"
          ref={setRef}
        >
          {children}
        </div>
      </div>
    </Overlay>
  )
}
```
When the component first renders, the value of `ref` is set to a div element unattached to the main document with no children, so `ariaHideOutside` does essentially nothing. When the modal is mounted, it calls `setRef` with its ref value, which causes the component to re-render, calling `useModalOverlay` a second time with the correct ref, so it works as expected.

**Comment by eissmann** [comment] 2023-02-03 09:23
> Seeing this issue as well when running a [useComboBox](https://react-spectrum.adobe.com/react-aria/useComboBox.html) example in Next.

In this case my workaround was to give the listBoxRef in there as popoverRef.

`...
    let inputRef = React.useRef(null);
    let listBoxRef = React.useRef(null);
    let popoverRef = listBoxRef;

    let { inputProps, listBoxProps, labelProps } = useComboBox(
        {
            ...props,
            inputRef,
            listBoxRef,
            popoverRef,
        },
        state
    );
    ...`

**Comment by Talor-A** [comment] 2023-02-07 16:43
this is working fine for me:

```tsx
<Overlay portalContainer={document.body}>
      <div
        css={css.underlay}
        {...underlayProps}
        onContextMenu={preventContextMenu}
      >
     ...
  </div>
</Overlay>
```

**Comment by mstllc** [comment] 2023-02-13 21:34
> this is working fine for me:
> 
> ```tsx
> <Overlay portalContainer={document.body}>
>       <div
>         css={css.underlay}
>         {...underlayProps}
>         onContextMenu={preventContextMenu}
>       >
>      ...
>   </div>
> </Overlay>
> ```

@Talor-A are you rendering this on the server or is this something you render conditionally?  In other words, are you rendering this `Overlay` initially with the rest of the page or only when a user does something?  This solution _works_ but only on the client, not the server.  If you try to render the page with this `Overlay` initially, it will throw an error,  unless I'm missing something.

**Comment by TommySorensen** [comment] 2023-03-03 14:03
If you take the example on https://react-spectrum.adobe.com/react-aria/usePopover.html bit by bit in a standard Nextjs beta v13.2.3 solution. Then the position is not set on on first render. This can be fixed with `portalContainer={document.body}` as @Talor-A  mentions. Any real fixes for this? It seems like a bug

**Comment by mryechkin** [comment] 2023-03-07 21:57
None of the suggested solutions are working for me unfortunately, using the styled-components example in [useComboBox](https://react-spectrum.adobe.com/react-aria/useComboBox.html).

**Comment by mryechkin** [comment] 2023-03-07 21:58
> If you try to render the page with this `Overlay` initially, it will throw an error, unless I'm missing something.

I can confirm this happens for me as well. That solution doesn't fix my issue with ComboBox unfortunately, still getting the same error.

**Comment by EmLXND** [comment] 2023-03-09 18:11
[this](https://github.com/adobe/react-spectrum/issues/3490) could be related, but was closed for some reason without the issue being fixed 🤷

**Comment by devongovett** [comment] 2023-03-30 19:52
I got to the bottom of this in #4297. This is actually the same issue as #3293. Due to the `useIsSSR` check here: https://github.com/adobe/react-spectrum/blob/a1efafd9e8bf893a6b433a3ccab60ff66295c302/packages/%40react-aria/overlays/src/Overlay.tsx#L37

The popover is not rendered for an extra render cycle after the combobox state's `isOpen` property becomes true. That causes the popover ref to be null and the crash here.

The fix is to only perform an extra re-render during initial hydration, and not whenever _any_ component mounts inside an SSR environment later on.

**Closed** 2023-03-30 20:50 UTC
Labels: bug, ssr
