### ISSUE TITLE
useOverlay, useInteractOutside on iOS12 causes modals to disappear instantly

### ISSUE THREAD

**Issue by BartoszGamza** [adobe/react-spectrum#2107] opened 2021-07-14 15:13 UTC
# 🐛 Bug Report 

As title says, on iOS 12 when using `useOverlay` (and `useInteractOutside` under the hood, which I believe might be a source of issue) the modal (or any other dialog basically) disappears instantly as presented on the movie attached. It can be easily reproduced by launching docs of `useDialog` in BrowserStack, on Safari 12

https://user-images.githubusercontent.com/26162660/125646656-35dee1b8-3b24-4603-8700-978fb7e77bee.mp4

## 🤔 Expected Behavior

The dialog should not close when appearing.

## 😯 Current Behavior

Dialog closes instantly after appearing.

## 🔦 Context

Even though the market share of iOS 12 is pretty low, the issue is quite severe - it completely disables the usage of dialog.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  1.2.2 (current latest)
| Browser          |  iOS Safari 12
| Operating System | iOS 12

## 🧢 Your Company/Team

[livechat.com](https://www.livechat.com/)

**Comment by reidbarber** [comment] 2021-07-14 16:47
Just tested in Simulator on iOS 12.0 and wasn't able to reproduce. Tested on both iPhone 5s and iPhone X sims:

<img width="459" alt="Screen Shot 2021-07-14 at 11 42 59 AM" src="https://user-images.githubusercontent.com/8961049/125660634-238f03db-b174-4ab4-aa1b-b4e8471415ca.png">

**Comment by LFDanLu** [comment] 2021-07-27 17:49
We'd be happy to accept a fix for this but we won't be picking this up ourselves due to the limited area of effect (only iOS 12 + iPhone Xs) of this bug.

**Closed by LFDanLu** 2021-07-27 17:49 UTC

**Comment by mitchellwarr** [comment] 2021-12-15 00:53
Found this issue (or something similar) in the new useSelect on an ipad v 12.5.5

**Comment by snowystinger** [comment] 2021-12-15 01:14
@mitchellwarr do you have any updates to how to reproduce? I'm not seeing it on my iPhone. though admittedly i am on much different versions
Would you be willing to do any debugging? We don't have much to go off unless you have some new repro steps/videos you'd be willing to share.

**Comment by mitchellwarr** [comment] 2021-12-15 01:18
@snowystinger yes ive just finished creating a new issue for this here:  https://github.com/adobe/react-spectrum/issues/2686

its different enough, i think, to this issue.

**Comment by snowystinger** [comment] 2021-12-15 01:22
@mitchellwarr o, fabulous, thank you!!

**Comment by mitchellwarr** [comment] 2021-12-15 01:27
@snowystinger glad to help!
i think this issue isnt overly specific, since it was the first browserstack version i tried with iOS 12 and stumbled on the bug.

can confirm in local with iOS 14 everything was fine
