### ISSUE TITLE
ESLINT Autoprefixer warnings

### ISSUE THREAD

**Issue by vreznikua** [adobe/react-spectrum#956] opened 2020-08-13 08:20 UTC
Eslint issues with :
 - overlays/main.css; 
 - breadcrumbs/main.css.
-->

# 🐛 Bug Report 

overlays/dist/main.css: 
 - (1:4326) Replace fill-available to stretch, because spec had been changed
 - (1:7673) Replace fill-available to stretch, because spec had been changed

breadcrumbs/dist/main.css: 
 - (1:745) start value has mixed support, consider using flex-start instead
 - (1:83) start value has mixed support, consider using flex-start instead

## 🤔 Expected Behavior

I don't have any eslint issues.

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/44365250/90110386-cc6ee600-dd55-11ea-8d17-80164386e299.png)

## 💁 Possible Solution

This issue related with Autoprefixer. (On my opinition).

**Comment by snowystinger** [comment] 2020-08-13 16:01
this is a duplicate of https://github.com/adobe/react-spectrum/issues/768

**Closed by snowystinger** 2020-08-13 16:01 UTC
