### ISSUE TITLE
ListView keyboard issues

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#2608] opened 2021-11-29 19:41 UTC
# 🐛 Bug Report 

- The fn+up arrow (page up) doesn't work in ListView. fn+down arrow (page down) does work. 
- Home and end keys don't do anything (regression? check what it should do)
- cannot shift select the first item, probably because the key is 0

## 🤔 Expected Behavior

The above keyboard interactions should work

## 😯 Current Behavior

The above keyboard interactions don't work

## 🧢 Your Company/Team

RSP

**Comment by ktabors** [comment] 2021-12-07 18:09
Duplicate of #2572

**Closed by ktabors** 2021-12-07 18:09 UTC
Labels: bug, rsp:ListView
