### ISSUE TITLE
FocusScope causes error in snapshot tests

### ISSUE THREAD

**Issue by tom-schafer-smar** [adobe/react-spectrum#3248] opened 2022-06-21 08:49 UTC
# 🐛 Bug Report 

Using the `FocusScope` component in a storyshots snapshot test leads to the following error:

```bash
TypeError: Cannot read property 'nextSibling' of null

      at node_modules/@react-aria/focus/dist/packages/@react-aria/focus/src/FocusScope.tsx:96:33
      at commitHookEffectListMount (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11692:26)
      at commitLifeCycles (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11753:11)
      at commitLayoutEffects (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14443:7)
      at HTMLUnknownElement.callCallback (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11391:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11440:16)
      at invokeGuardedCallback (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11499:31)
      at commitRootImpl (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14172:9)
      at unstable_runWithPriority (node_modules/@storybook/addon-storyshots/node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2486:10)
      at commitRoot (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14011:3)
      at performSyncWorkOnRoot (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13440:3)
      at node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2537:26
      at unstable_runWithPriority (node_modules/@storybook/addon-storyshots/node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2486:10)
      at flushSyncCallbackQueueImpl (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2532:9)
      at flushSyncCallbackQueue (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2519:3)
      at scheduleUpdateOnFiber (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13004:9)
      at updateContainer (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16454:3)
      at create (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:17149:3)
      at getRenderedTree (node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/react/renderTree.js:24:18)
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:9:24
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:29:24)
```

## 💻 Code Sample

I have created a minimal example here: https://github.com/tom-schafer-smar/focus-scope-snapshot-issue

The following is an example of a story that causes the error:

```typescript
import { ComponentMeta } from "@storybook/react";
import React from "react";
import { FocusScope } from "react-aria";

export default {
  title: "FocusScope",
  component: FocusScope,
} as ComponentMeta<typeof FocusScope>;

export const Primary = () => <FocusScope>a</FocusScope>;
```

## 🌍 Your Environment

| Software | Version(s) |
| ---------------- | ---------- |
| react-aria | 3.17.0
| Browser | N/A
| Operating System | MacOS Monterey 12.4

**Comment by tom-schafer-smar** [comment] 2022-06-23 08:11
Thanks @LFDanLu , useful to know about that workaround! Just to confirm, will you be closing the issue due to the workaround or is it possible that there might be a fix without requiring those steps?

**Comment by LFDanLu** [comment] 2022-06-23 17:45
I'm leaning towards closing since it feels to me that this is a Storyshot specific case where the custom renderer is actually the desired fix. I'd be interested if this issue can be reproduced with a generic component with a `ref.current.nextSibiling` call, something I was going to try next when I get some extra time.

**Comment by LFDanLu** [comment] 2022-06-25 01:04
Just tried it out with a generic component (div with ref that checked nextSibiling on render), it definitely seems to be due to the lack of a custom renderer rather than FocusScope itself. Without JSDOM or some kind of renderer, the ref itself is undefined and thus it cannot check nextSibling. I'll be closing this out, feel free to reopen this if you run into any other issues

**Closed by LFDanLu** 2022-06-25 01:04 UTC

**Comment by tom-schafer-smar** [comment] 2022-06-27 08:33
Thanks @LFDanLu , appreciate your time looking into this!
