### ISSUE TITLE
useModalOverlay throws 'Uncaught TypeError: Cannot read properties of null (reading 'contains')' on first render

### ISSUE THREAD

**Issue by toddym42** [adobe/react-spectrum#3947] opened 2023-01-23 12:36 UTC
# 🐛 Bug Report

The following error is thrown on first render when using the `useModalOverlay` hook:
> 'Uncaught TypeError: Cannot read properties of null (reading 'contains')'

Line 112 of `ariaHideOutside.ts` contains the following
```
if (![...visibleNodes, ...hiddenNodes].some(node => node.contains(change.target))) {
```
`visibleNodes` is based on a reference to the modal overlay element, and would be assigned with something like this:
```
...
const ref = useRef<HTMLDivElement>(null);
const { modalProps, underlayProps } = useModalOverlay(props, state, ref);

return (
  <Overlay>
    <div {...underlayProps}>
      <div {...modalProps} ref={ref}>
        {children(() => state.close())}
      </div>
    </div>
  </Overlay>
);
```
(This is also similar to the example provided in the react-aria docs [here](https://react-spectrum.adobe.com/react-aria/useModalOverlay.html)).

On the very first render, before the ref has been allocated to the relevant element, `ref.current` will be `null` (or whatever initial value you gave to the ref) causing the following previously mentioned error to be thrown.

The ref is then updated, and the everything is fine from that point.

I've been able to prevent the initial error being thrown by setting an initial dummy div value to the ref like this:
```
const ref = useRef<HTMLDivElement>(document.createElement('div'));
```
But this doesn't feel like the intended solution, and I'm not sure what other implications this may have.

## 🤔 Expected Behavior

`ariaHideOutside` not called with `[null]`, causing the above error to be thrown.

## 😯 Current Behavior

As detailed above

## 💁 Possible Solution

A solution could be to only call `ariaHideOutside` once `ref.current` is not null. e.g. by updaing the `useEffect` in `useModalOverlay` from
```
useEffect(() => {
  if (state.isOpen) {
    return ariaHideOutside([ref.current]);
  }
}, [state.isOpen, ref]);
```
to
```
useEffect(() => {
  if (state.isOpen && ref.current != null) {
    return ariaHideOutside([ref.current]);
  }
}, [state.isOpen, ref]);
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.22.0
| Browser          | Chrome
| Operating System | Windows

**Comment by reidbarber** [comment] 2023-01-23 15:41
If you are using SSRProvider, this may be a duplicate of https://github.com/adobe/react-spectrum/issues/3787

**Comment by toddym42** [comment] 2023-01-25 10:32
@reidbarber - thanks for the response. Yes, we are using `<SSRProvider>` so this looks to be the same issue.

**Comment by reidbarber** [comment] 2023-01-25 15:03
Thanks, closing as a duplicate

**Closed by reidbarber** 2023-01-25 15:03 UTC
