### ISSUE TITLE
Checkbox Group Validation

### ISSUE THREAD

**Issue by dbani-dev-shell** [adobe/react-spectrum#5693] opened 2024-01-13 01:45 UTC
### Provide a general summary of the issue here

It seems the Checkbox Group validation [example](https://react-spectrum.adobe.com/react-aria/CheckboxGroup.html#group-validation) does not revalidate after the checkbox is pressed. 

To note: Fantastic work on `react-aria-components`, keep up the great work! 

### 🤔 Expected Behavior?

Checkbox Group should clear validation when at least one checkbox is selected.

### 😯 Current Behavior

Checkbox Group does not clear validation. 

### 🖥️ Steps to Reproduce

[React Aria's Documentation Example for Checkbox Group Validation](https://react-spectrum.adobe.com/react-aria/CheckboxGroup.html#group-validation)

1. Press Submit
2. Press a Checkbox
3. Validation is still displayed

### Version

react-aria-components@1.0.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by LFDanLu** [comment] 2024-01-19 21:31
Thanks for filing this issue. I noticed this actually doesn't happen in our React Spectrum CheckboxGroup equivalent, seems to be due to our usage of a visually hidden input for the RAC Checkbox vs using an actual input. Typically `onChange` would fire [here](https://github.com/adobe/react-spectrum/blob/ee51290b98fdc7cad31957ed2dd0a486eb0c1427/packages/%40react-aria/form/src/useFormValidation.ts#L86) as a result of the checkbox state changing, updating the form's state but RAC's visually hidden input doesn't actually get pressed when you click on it hence no `onChange` firing. A potential solution would be to fire `state.commitValidation` [here](https://github.com/adobe/react-spectrum/blob/ee51290b98fdc7cad31957ed2dd0a486eb0c1427/packages/%40react-aria/checkbox/src/useCheckboxGroupItem.ts#L33-L42) instead for RAC Checkbox group items, will need to test if this has any unforseen behavior changes though

**Comment by smozely** [comment] 2024-02-19 18:57
#5836 appears to be a duplicate, but in that case isolating it to also happening on just Checkbox rather than a group. And that the behavior is different when using a mouse vs keyboard which is the same in the [example](https://react-spectrum.adobe.com/react-aria/CheckboxGroup.html#group-validation)

**Comment by nwidynski** [comment] 2024-03-18 20:58
@LFDanLu I took some time to take a look at this.

This issue seems pretty isolated to RAC's implementation of a visually hidden input, so can't we fix this inside RAC?
Maybe i am missing something related to how event dispatching is handled across different browsers/devices.

A slightly hacky, but working solution could look something like this:
```tsx
/**
 * Setup a stable callback to propagate changes in the state.
 */
let onChange = props.onChange;

if (!groupState || groupState.isInvalid) {
  const event = new Event('change');
  const dispatch = () => inputRef.current?.dispatchEvent(event);

  onChange = chain(dispatch, groupState.onChange);
}

props.onChange = useEffectEvent(onChange);
```

**Comment by LFDanLu** [comment] 2024-03-18 22:34
@nwidynski While that may certainly fix it for RAC, my concern is that someone may build their own checkbox using our checkbox hooks instead of opting to use RAC and use a visually hidden input in a similar fashion like we suggest [here](https://react-spectrum.adobe.com/react-aria/useCheckbox.html#styling). They would then run into original problem as well then and need to create a similar fix local to their implementation.

**Comment by nwidynski** [comment] 2024-03-18 23:31
@LFDanLu Got it. 

Well the problem is that this somehow has to get fixed for both isolated and grouped checkboxes at the same time. How about something like this in `useCheckbox`:

```tsx
const { [privateValidationStateProp]: groupValidationState } = props;

const dispatch = () => {
  const { realtimeValidation, commitValidation } = groupValidationState
    ? groupValidationState
    : validationState;
  
  if (realtimeValidation.isInvalid) {
    commitValidation();
  }
};

labelProps.onClick = chain(dispatch, labelProps.onClick);
```

**Comment by LFDanLu** [comment] 2024-03-19 20:13
@nwidynski Yep, that seems promising! Do you want to open a PR for that change?

**Comment by aulonm** [comment] 2024-04-26 14:26
Hi, 

We've come across the same bug, but it seems that it works with tab + space to check the checkbox, but it does not work with mouse clicks. Would #6079 fix that as well?

**Comment by LFDanLu** [comment] 2024-05-02 22:39
Yes I believe so, is the behavior in these built [docs](https://reactspectrum.blob.core.windows.net/reactspectrum/1658678ff9bcf8edda061c2306fad8f6ba028c85/docs/react-spectrum/CheckboxGroup.html#group-validation) essentially what you are looking for?

**Comment by aulonm** [comment] 2024-05-03 06:32
> Yes I believe so, is the behavior in these built [docs](https://reactspectrum.blob.core.windows.net/reactspectrum/1658678ff9bcf8edda061c2306fad8f6ba028c85/docs/react-spectrum/CheckboxGroup.html#group-validation) essentially what you are looking for?

Yes! Both the Group Validation and the Individual Validation behaviour is what we have been trying to do, and the examples on the individual are spot on for our use case as well.

**Comment by poulet42** [comment] 2024-07-11 16:40
Hello ! Just stumbled upon the issue too, I checked the storybook of #6079 and this seems to do the trick 🎉 Out of curiosity, is there anything preventing the PR to be merged @LFDanLu ? This would be awesome if it get released 🙏

**Comment by LFDanLu** [comment] 2024-07-11 17:52
Thanks for the reminder, if I remember correctly there was some simplification that could be made via https://github.com/adobe/react-spectrum/pull/6079#discussion_r1561839144. The team was thinking of picking this PR (and some others that have fallen by the wayside) up ourselves but are crunching on getting the next release out first.

**Closed** 2024-11-13 19:02 UTC
Labels: bug, help wanted, RAC
