### ISSUE TITLE
`onOpenChange` has no effect when applied to overlay Components (`Popover`, `Modal` )

### ISSUE THREAD

**Issue by Persists** [adobe/react-spectrum#7225] opened 2024-10-22 13:31 UTC
### Provide a general summary of the issue here

When using an overlay component like `Modal` or `Popover`, the `onOpenChange` event doesn't get triggered. I understand that using `onOpenChange` on the `DialogTrigger` would work, but in cases where there is no `DialogTrigger`, this approach can't be applied.

### 🤔 Expected Behavior?

The event should be called when opening/closing the overlay. 

### 😯 Current Behavior

The event is never called. 

### 🖥️ Steps to Reproduce

[Modal Example](https://codesandbox.io/p/sandbox/admiring-pasteur-y48p68?workspaceId=62ec24d5-1f87-4653-b449-fcd53e8dac80)
[Popover Example](https://codesandbox.io/p/sandbox/autumn-https-xwspcr?workspaceId=62ec24d5-1f87-4653-b449-fcd53e8dac80)

### Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

MacOs

**Comment by snowystinger** [comment] 2024-10-23 02:07
duplicate of https://github.com/adobe/react-spectrum/issues/6547

**Closed by snowystinger** 2024-10-23 02:07 UTC
