### ISSUE TITLE
Cannot update a component while rendering a different component 

### ISSUE THREAD

**Issue by bbutler522** [adobe/react-spectrum#2808] opened 2022-02-07 03:29 UTC
# 🐛 Bug Report 

The ToggleButton component is creating a warning `Warning: Cannot update a component ('App') while rendering a different component.` when I try to use an onChange handler to update React state. I noticed the issue in the website feature I'm working on, but also run into it when I sandbox the [documentation](https://react-spectrum.adobe.com/react-spectrum/ToggleButton.html) alone as well. 

The similar closed issues I've found that look to have been resolved, so I'm not sure if it's something I'm not realizing on my end or not.

## 🤔 Expected Behavior

The button should work without throwing a warning, like it does on the docs site.

## 😯 Current Behavior

The button correctly sets the state, but throws the following warning.

```
Warning: Cannot update a component (`App`) while rendering a different component (`ForwardRef($ee41bfa1892cb064198e19baae3426a$var$ToggleButton)`). To locate the bad setState() call inside `ForwardRef($ee41bfa1892cb064198e19baae3426a$var$ToggleButton)`
```

## 🔦 Context

I'm trying to create a toggle input that has controlled state and will make a call to my apps backend. Functionally it works, but the warning is thrown.

## 💻 Code Sample

This [sandbox](https://codesandbox.io/s/elastic-glade-xqxcw?file=/src/App.js) looks like it should be as close to the documentation as I could get, but I still get the warning message.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.6.0
| Browser          | [Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (arm64)](https://brave.com/latest/)
| Operating System | MacOS Monterey v. 12.0.1

**Comment by reidbarber** [comment] 2022-02-07 15:24
I believe this got handled by https://github.com/adobe/react-spectrum/pull/2304. This is currently available on nightlies right now, and should be released very soon. Closing as a duplicate of https://github.com/adobe/react-spectrum/issues/1440, but feel free to reopen if the issue persists.

**Closed by reidbarber** 2022-02-07 15:24 UTC
