### ISSUE TITLE
Textfield - type password

### ISSUE THREAD

**Issue by D-Saraf** [adobe/react-spectrum#1437] opened 2021-01-04 10:42 UTC
When a password type TextField is used, it hangs on IOS tablet device, i.e. there is some delay between clicking on the field and the keyboard popping up for the input.

**Comment by snowystinger** [comment] 2021-01-04 18:28
Can you provide more information about what device you're using and what browser version you're on?
I've tried it on my iphone 12pro with 14.3 and i'm not noticing any delay  https://codesandbox.io/s/sweet-rhodes-0x4h6?file=/src/App.js

**Comment by D-Saraf** [comment] 2021-01-05 10:16
Device-
iPad mini 4
OS version- 14.3

Browser-
Safari

**Comment by D-Saraf** [comment] 2021-01-05 10:17
Device-
iPad mini 4
OS version- 14.3

Browser-
Safari

Textfield is not working with type=’password’

From: Dheeraj Saraf <dsaraf@adobe.com>
Date: Tuesday, 5 January 2021 at 3:46 PM
To: adobe/react-spectrum <reply@reply.github.com>
Subject: Re: [adobe/react-spectrum] Textfield - type password (#1437)
Device-
iPad mini 4
OS version- 14.3

Browser-
Safari

**Comment by snowystinger** [comment] 2021-01-05 21:07
So we've tested this on 
iPhone 7 iOS 13.7
iPad Pro on iOS 13.3
iphone XS Max on iOS 14.2
iphone 12pro with 14.3

All of them appear to be working fine.

Are you able to reproduce it in the codesandbox i linked?
Otherwise, can you post the code you're using or post a video screen capture showing the issue?

**Comment by D-Saraf** [comment] 2021-01-06 06:21
As I mentioned before, it is working perfectly fine on all the devices but Safari/604.1 on iPad mini 4, OS version- 14.3. The keyboard is popping up after a considerable time lag for this particular device.
This is the way we have implemented the password textfield in our code.
<Textfield type=”password” />

**Comment by snowystinger** [comment] 2021-01-06 17:06
I believe you that TextField with type=password is having an issue on your device. Since none of us have that device though, we cannot verify or work through this issue. I'm trying to gather more information from you so we can make an educated guess as to what is happening.

Can you provide a video showing the issue?
Can you verify that you see the issue in the codesandbox link I sent? or is it only happening in your application?

**Comment by D-Saraf** [comment] 2021-01-07 17:53
The codesandbox link you shared is not using Textfield. Can you share an example using Textfield as type="password"?
Also, attached is the video showcasting the issue we are facing in iPad Mini 4. This seems to be a device specific issue as we are not facing this issue in any other device.

https://user-images.githubusercontent.com/70808330/103926677-3e016380-513f-11eb-8731-b51a7f7f997e.MP4

**Comment by snowystinger** [comment] 2021-01-07 18:23
Terribly sorry, not sure where I got that link, I've updated the comment with a new link. Including here as well. https://codesandbox.io/s/nifty-platform-kur8q?file=/src/App.js

**Comment by D-Saraf** [comment] 2021-01-08 07:52
PFA the attachment. The issue is reproducing with this piece of codesandbox code. The keyboard is not appearing even after clicking on the TextField element.

Uploading Textfield password codesandbox.MP4…

**Comment by D-Saraf** [comment] 2021-01-08 07:57
PFA the attachment. The issue is reproducing with this piece of codesandbox code. The keyboard is appearing with a considerable lag after clicking on the TextField element.

Uploading Textfield password codesandbox.MP4…

**Comment by D-Saraf** [comment] 2021-01-08 07:58
PFA the attachment. The issue is reproducing with this piece of codesandbox code. The keyboard is appearing with a considerable lag after clicking on the TextField element.

https://user-images.githubusercontent.com/70808330/103989160-4c8a6200-51b5-11eb-89fc-947788e7e2b5.MP4

**Comment by majornista** [comment] 2021-01-11 16:59
@D-Saraf and @snowystinger, 

I have been unable to reproduce the issue on an iPad mini 2 with iOS 12.5, which is the most recent version of iOS supported by this device.

https://user-images.githubusercontent.com/154077/104213508-5ce44c00-5404-11eb-9068-0803e975e31a.MP4

**Comment by snowystinger** [comment] 2021-01-15 22:59
@D-Saraf since we’re unable to reproduce and we don’t know what might be causing this, you may need to do some profiling detective work in order to narrow it down.  I’m going to close this issue for now, feel free to reopen if you learn more.

**Closed by snowystinger** 2021-01-15 22:59 UTC
