### ISSUE TITLE
Incorrect selectedItem types - can be null

### ISSUE THREAD

**Issue by donaldpipowitch** [adobe/react-spectrum#3915] opened 2023-01-13 06:53 UTC
# 🐛 Bug Report 

According to the types `selectedItem` is always a `Node<T>`, but it can actually be `null`.

https://github.com/adobe/react-spectrum/blob/7cebb4eea31f383f1eec06cc53a7909f8736f66a/packages/%40react-stately/list/src/useSingleSelectListState.ts#L34

https://github.com/adobe/react-spectrum/blob/7cebb4eea31f383f1eec06cc53a7909f8736f66a/packages/%40react-stately/list/src/useSingleSelectListState.ts#L63-L65

## 🤔 Expected Behavior

`readonly selectedItem: Node<T> | null`

## 😯 Current Behavior

`readonly selectedItem: Node<T>`

## 💁 Possible Solution

Add `| null`.

## 🔦 Context

We saw runtime errors, because of the unhandled `null` case.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by reidbarber** [comment] 2023-01-13 18:32
We are incrementally enabling Typescript's strict mode across all files, as a part of https://github.com/adobe/react-spectrum/issues/3183. It should get handled as a part of that, but if you'd like it sooner, feel free to submit a PR.

**Comment by donaldpipowitch** [comment] 2023-01-13 21:42
Ah, good to know react-aria isn't using strict settings so far.

**Comment by snowystinger** [comment] 2023-01-13 21:55
Parts are, parts are not, unfortunately i think it's still the majority are not at the moment.
To add more packages into strict checking, we can enable them here https://github.com/adobe/react-spectrum/blob/main/tsconfig.json#L49

**Comment by LFDanLu** [comment] 2023-01-25 19:33
Closing as dupe of #3183

**Closed by LFDanLu** 2023-01-25 19:33 UTC
