### ISSUE TITLE
Revist `isLoading` api for Table

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#1505] opened 2021-01-26 00:01 UTC
# 🙋 Feature Request

With the changes made to [useAsyncList](https://github.com/adobe/react-spectrum/blob/main/packages/@react-stately/data/src/useAsyncList.ts#L105), we should revisit Table and improve the loading swirl location/logic depending on what state `useAsyncList` returns

## 🤔 Expected Behavior

Loading swirl should appear at the bottom of the table if `loadingMore`, otherwise in the middle of the table for `loading`

## 😯 Current Behavior

Currently the loading swirl appears at the bottom of the table here: https://reactspectrum.blob.core.windows.net/reactspectrum/f8a204d341e0a36c2a1fe0ac8b9a65a13bb9648b/storybook/index.html?path=/story/table--async-client-side-filter-loading

## 🧢 Your Company/Team
RSP

**Comment by matthewdeutsch** [comment] 2021-03-23 22:15
dupe of #1728

**Closed by matthewdeutsch** 2021-03-23 22:15 UTC
Labels: rsp:Table
