### ISSUE TITLE
ComboBox - Clicking outside the menu is selecting an item in the menu 

### ISSUE THREAD

**Issue by eyao06** [adobe/react-spectrum#2181] opened 2021-07-30 01:15 UTC
# 🐛 Bug Report 

After typing in anything in the ComboBox, as long as it shrinks the menu a bit, and while still not having anything selected, click anywhere below the menu (anywhere that was within the previous menu height)
The field will clear, then the full menu of items will reappear and then the item in the area you clicked will be selected

i noticed this occurs when i add the loadingState prop to the ComboBox

https://user-images.githubusercontent.com/12926470/127585004-63e616e0-9984-4dbe-9e10-1023f95710ce.mov

## 🤔 Expected Behavior

- Menu will close without it re-opening

## 😯 Current Behavior

- On mouse down Menu closes > Field clears > Menu re-opens > On mouse up, if mouse cursor is within the menu space, an item will be selected

## 🔦 Context

- Steps to Reproduce
1. In the ComboBox input field, type in anything, we just want to filter the options in the menu so the menu height reduces 
2. Do not select anything in the menu
3. Hover you mouse to anywhere below the menu (the area where the menu use to cover before it was filtered)
4. Click there
5. Immediately the ComboBox field will clear and the menu will undo the filter, and the item where the click was, will be selected

## 💻 Code Sample

```
import React from "react";
import { Provider, defaultTheme, ComboBox, Item } from "@adobe/react-spectrum";
import "./styles.css";

let options = [
  { id: 1, name: 'Aerospace' },
  { id: 2, name: 'Mechanical' },
  { id: 3, name: 'Civil' },
  { id: 4, name: 'Biomedical' },
  { id: 5, name: 'Nuclear' },
  { id: 6, name: 'Industrial' },
  { id: 7, name: 'Chemical' },
  { id: 8, name: 'Agricultural' },
  { id: 9, name: 'Electrical' },
];

export default function App() {
  return (
    <Provider theme={defaultTheme}>
        <ComboBox
          label='Pick a engineering major'
          defaultItems={ options }
          loadingState>
          {(item) => <Item>{item.name}</Item>}
        </ComboBox>
    </Provider>
  );
}

```

**Comment by LFDanLu** [comment] 2021-07-30 16:39
Confirmed this is an issue, perhaps we can try to prevent selection while the menu is transitioning

**Comment by diegocasmo** [comment] 2021-08-12 23:08
This seems to be happening because the combo box input value is set to an empty string because the `selectedKey` is `null`. This results in filtering the collection and momentarily rendering all options. 

I was able to replicate it in the Storybook examples:
<details>
  <summary>Click to see `.gif` Storybook example</summary>
  
  ![combobox](https://user-images.githubusercontent.com/4553097/129280899-1d74fa66-5174-4bd8-a0ee-5a66b7844a2e.gif)
</details>


The issue appears to happen in the `commitSelection` function (`packages/@react/stately/combobox/src/useComboBoxState.ts`), in the `else` part of it:
``` ts
  let commitSelection = () => {
    // If multiple things are controlled, call onSelectionChange
    if (props.selectedKey !== undefined && props.inputValue !== undefined) {
      props.onSelectionChange(selectedKey);

      // Stop menu from reopening from useEffect
      let itemText = collection.getItem(selectedKey)?.textValue ?? '';
      lastValue.current = itemText;
      triggerState.close();
    } else {
      // If only a single aspect of combobox is controlled, reset input value and close menu for the user
      resetInputValue();
      triggerState.close();
    }
  };
```

**Comment by LFDanLu** [comment] 2023-01-25 20:07
Team discussed this, we'll see about preventing the selection of the item when the menu is closing (perhaps via ignoring selection changes if isOpen is false). The menu flash issue is harder to fix so we won't include that in the work here.

**Comment by LFDanLu** [comment] 2023-02-13 22:41
Looking to get rid of the menu flash, reopening

**Closed** 2023-02-15 00:24 UTC
Labels: bug, rsp:ComboBox
