### ISSUE TITLE
<Picker isOpen={true}> not supported in SSR

### ISSUE THREAD

**Issue by sparecycles** [adobe/react-spectrum#3091] opened 2022-05-02 03:29 UTC
### Expected Behaviour

Picker renders initially open (or at least doesn't crash the render).

### Actual Behaviour

<img width="563" alt="image" src="https://user-images.githubusercontent.com/719818/166180457-13b576e8-3526-42e1-8972-d5d9ce0646b2.png">

### Reproduce Scenario (including but not limited to)

Loading the page.

#### Platform and Version

```json
  "dependencies": {
    "@adobe/react-spectrum": "3.16.5",
    "next": "12.1.4",
    "react": "18.0.0",
    "react-dom": "18.0.0"
  },
```

#### Sample Code that illustrates the problem

```jsx
<Picker isOpen={true}>
  <Item/>
</Picker>
```

or 

```jsx
<Picker defaultOpen={true}>
  <Item/>
</Picker>
```

#### Logs taken while reproducing problem

```log
ReferenceError: document is not defined
    at $2aebdc186fd41e87$var$Overlay (webpack-internal:///./node_modules/@react-spectrum/overlays/dist/main.js:92:102)
    at renderWithHooks (node_modules/react-dom/cjs/react-dom-server.browser.development.js:5448:16)
    at renderForwardRef (node_modules/react-dom/cjs/react-dom-server.browser.development.js:5632:18)
    at renderElement (node_modules/react-dom/cjs/react-dom-server.browser.development.js:5795:11)
    at renderNodeDestructive (node_modules/react-dom/cjs/react-dom-server.browser.development.js:5875:11)
    at renderForwardRef (node_modules/react-dom/cjs/react-dom-server.browser.development.js:5649:5)
    at renderElement (node_modules/react-dom/cjs/react-dom-server.browser.development.js:5795:11)
    at renderNodeDestructive (node_modules/react-dom/cjs/react-dom-server.browser.development.js:5875:11)
    at renderNode (node_modules/react-dom/cjs/react-dom-server.browser.development.js:6009:12)
    at renderChildrenArray (node_modules/react-dom/cjs/react-dom-server.browser.development.js:5965:7)
```

**Comment by reidbarber** [comment] 2022-05-03 16:46
Closing as a duplicate of https://github.com/adobe/react-spectrum/issues/1055

**Closed by reidbarber** 2022-05-03 16:46 UTC
Labels: ssr
