### ISSUE TITLE
width: fit-content is not supported by <TabList>

### ISSUE THREAD

**Issue by alanreay** [adobe/react-spectrum#3951] opened 2023-01-24 18:52 UTC
# 🐛 Bug Report 

Trying to apply "fit-content" to width

## 🤔 Expected Behavior

```
<TabList
   width="fit-content"
>
```
leads to
```
element.style {
    width: fit-content;
}
```

## 😯 Current Behavior

```
<TabList
   width="fit-content"
>
```
leads to
```
element.style {
    width: var(--spectrum-global-dimension-fit-content, var(--spectrum-alias-fit-content));
}
```

## 💁 Possible Solution

looks like there is a missing handling for “fit-content” [here](https://github.com/adobe/react-spectrum/blob/4b702ebf16e91ac4be0f401a9e120bb8b65b56b7/packages/%40react-spectrum/utils/src/styleProps.ts#L122-L140). 

There is a workaround, you can use UNSAFE_style

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment] 2023-01-24 22:02
Closing as a dupe of https://github.com/adobe/react-spectrum/issues/3952

**Closed by snowystinger** 2023-01-24 22:02 UTC
