### ISSUE TITLE
Whenever, a select menu created using @react-spectrum/picker is closed, an error pops up

### ISSUE THREAD

**Issue by naveen-bharathi** [adobe/react-spectrum#1328] opened 2020-12-01 16:43 UTC
# 🐛 Bug Report 

Whenever, a select menu created using **@react-spectrum/picker** is closed, an error pops up. (Occurs only during development. Doesn't occur after the project is built for production)

## 🤔 Expected Behavior

When closing the select menu, it should close without any error

## 😯 Current Behavior

```js
TypeError: Argument 1 ('target') to ResizeObserver.unobserve must be an instance of Element
(anonymous function)


src/useResizeObserver.ts:37
  34 |   resizeObserverInstance.observe(ref.current);
  35 | 
  36 |   return () => {
> 37 |     resizeObserverInstance.unobserve(ref.current);
     | ^  38 |   };
  39 | }
  40 | 

callCallback
node_modules/react-dom/cjs/react-dom.development.js:3945
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:3994
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:4056
flushPassiveEffectsImpl
node_modules/react-dom/cjs/react-dom.development.js:23543
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js:646
flushDiscreteUpdates
node_modules/react-dom/cjs/react-dom.development.js:22356
flushDiscreteUpdatesIfNeeded
node_modules/react-dom/cjs/react-dom.development.js:3768
dispatchDiscreteEvent
node_modules/react-dom/cjs/react-dom.development.js:5886

(anonymous function)
src/useFocusVisible.ts:127
  124 | let focus = HTMLElement.prototype.focus;
  125 | HTMLElement.prototype.focus = function () {
  126 |   hasEventBeforeFocus = true;
> 127 |   focus.apply(this, arguments);
      | ^  128 | };
  129 | 
  130 | document.addEventListener('keydown', handleKeyboardEvent, true);

focusWithoutScrolling
src/focusWithoutScrolling.ts:34
  31 |     element.focus({preventScroll: true});
  32 |   } else {
  33 |     let scrollableElements = getScrollableElements(element);
> 34 |     element.focus();
  35 |     restoreScrollPosition(scrollableElements);
  36 |   }
  37 | }

focusSafely
src/focusSafely.ts:35
  32 |       }
  33 |     });
  34 |   } else {
> 35 |     focusWithoutScrolling(element);
  36 |   }
  37 | }
  38 | 

$c9e8f80f5bb1841844f54e4ad30b$var$focusElement
src/FocusScope.tsx:295
  292 | function focusElement(element: HTMLElement | null, scroll = false) {
  293 |   if (element != null && !scroll) {
  294 |     try {
> 295 |       focusSafely(element);
  296 |     } catch (err) {
  297 |       // ignore
  298 |     }

(anonymous function)
src/FocusScope.tsx:384
  381 | if (restoreFocus && nodeToRestore && isElementInScope(document.activeElement, scope)) {
  382 |   requestAnimationFrame(() => {
  383 |     if (document.body.contains(nodeToRestore)) {
> 384 |       focusElement(nodeToRestore);
      | ^  385 |     }
  386 |   });
  387 | }
```

## 🔦 Context

Causes difficulty in development. Everytime I close the select menu, I have to wait for the error popup to appear and close it before so as to interact with the UI

## 💻 Code Sample

```jsx
<Picker
  items={options}
  label="Picker"
  placeholder="Picker"
>
  {(option) => (
     <Item aria-label={option}>{option}</Item>
  )}
</Picker>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |3.2.1
| Browser          |Safari, Firefox, Edge, Chrome
| Operating System |macOS 11

**Comment by snowystinger** [comment] 2020-12-01 23:44
I think if you upgrade to a newer version this should be fixed. See code on main:
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/utils/src/useResizeObserver.ts#L39

**Comment by naveen-bharathi** [comment] 2020-12-02 03:11
> I think if you upgrade to a newer version this should be fixed. See code on main:
> https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/utils/src/useResizeObserver.ts#L39
@snowystinger The newer version doesn't fix the issue.

**Comment by naveen-bharathi** [comment] 2020-12-02 03:12
> I think if you upgrade to a newer version this should be fixed. See code on main:
> https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/utils/src/useResizeObserver.ts#L39

@snowystinger The newer version doesn't fix the issue.

**Comment by snowystinger** [comment] 2020-12-02 07:25
Same error?

**Comment by snowystinger** [comment] 2021-01-13 18:58
Unable to reproduce, closing due to inactivity. Feel free to reopen if you're still experiencing it with a codesandbox to demonstrate.

**Closed by snowystinger** 2021-01-13 18:58 UTC
Labels: waiting
