### ISSUE TITLE
Link stuck in pressed state when opened with keyboard

### ISSUE THREAD

**Issue by ali-idrizi** [adobe/react-spectrum#6883] opened 2024-08-15 10:43 UTC
### Provide a general summary of the issue here

When following a react-aria link using <kbd>enter</kbd> or <kbd>shift</kbd>+<kbd>enter</kbd> the link get's stuck in pressed state.

### 🤔 Expected Behavior?

The links should be restored to its default state once <kbd>enter</kbd> is released.

### 😯 Current Behavior

The link is stuck in pressed state and `data-pressed="true"`.

### 🖥️ Steps to Reproduce

1. Go to https://react-spectrum.adobe.com/react-aria/Link.html
2. Focus "The missing link" link in the first example
3. Press <kbd>enter</kbd> to follow it
4. Notice the link stuck in pressed state

### Version

1.3.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

Windows / macOS

**Comment by yihuiliao** [comment] 2024-08-16 22:04
Thanks for reporting this! I'm going to close this as a dupe of https://github.com/adobe/react-spectrum/issues/6094

**Closed by yihuiliao** 2024-08-16 22:04 UTC
