### ISSUE TITLE
Component Side Label Misaligned on Vertical Axis

### ISSUE THREAD

**Issue by ccr112393** [adobe/react-spectrum#7437] opened 2024-11-26 17:32 UTC
### Provide a general summary of the issue here

When component label position is set to "side", and the text falls onto more than one line, the label's Y axis is off center. 

<img width="289" alt="image" src="https://github.com/user-attachments/assets/ae745993-8b40-4c3a-af84-88639f66c197">

### 🤔 Expected Behavior?

Multi-line side labels would automatically be centered on the y-axis with its corresponding component, or offer customizable alignment options in relation to the component (i.e.: top, middle, bottom)

### 😯 Current Behavior

Currently, multi-line side labels retain their initial position resulting in text that falls below the component

### 🖥️ Steps to Reproduce

Create a Form component with labelPosition="side" and reduce the form width so the labels fall to multiple lines. 

### Version

3.38.0

### What browsers are you seeing the problem on?

Chrome, Other

### If other, please specify.

Adobe CEP Chromium Embedded

### What operating system are you using?

MacOS

**Comment by snowystinger** [comment] 2024-11-26 22:27
Thanks for the issue. Are you able to reproduce outside of CEP? ie in a codesandbox or stackblitz?

**Comment by snowystinger** [comment] 2024-11-26 23:58
Took a further look at this. This is the expected behavior. It will do this in all browsers. If the label was very long, then we don't want it pushing the field down to center align. It should be first baseline aligned so the text in the field is aligned with the first text line of the label.

However, something is still going on here because those stepper buttons don't look right.

I'm going to close this as working as intended.

**Closed by snowystinger** 2024-11-26 23:58 UTC
