### ISSUE TITLE
Table View: Text field inside a table view is not editable when clicked

### ISSUE THREAD

**Issue by collegewap** [adobe/react-spectrum#6868] opened 2024-08-13 07:13 UTC
### Provide a general summary of the issue here

If I add a text box inside a table, I cannot focus on it using click.

### 🤔 Expected Behavior?

I should be able to place a focusable text field inside the table.  

### 😯 Current Behavior

I am not able to place a focusable text field inside the table.

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/cool-blackburn-hjvyd2

### Version

3.36.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows 11

**Comment by snowystinger** [comment] 2024-08-13 09:09
Duplicate of https://github.com/adobe/react-spectrum/issues/2328

**Closed** 2024-08-13 09:09 UTC
