### ISSUE TITLE
OverlayTriggerStateContext is null when used within the RAC Select

### ISSUE THREAD

**Issue by screfy** [adobe/react-spectrum#6687] opened 2024-07-11 21:47 UTC
### Provide a general summary of the issue here

I'm trying to create a custom Popover using the `usePopover` hook and access the overlay trigger state from the `OverlayTriggerStateContext`. However, when I use my custom Popover with the Select component from React Aria Components, the state is null. Although, when I use it with the Menu component, it works just fine.

### 🤔 Expected Behavior?

`OverlayTriggerStateContext` should be defined

### 😯 Current Behavior

`OverlayTriggerStateContext` is null

![image](https://github.com/user-attachments/assets/edaf70df-d0ac-4a30-ac62-5c9ae0888155)

### 🔦 Context

I need a custom Popover component to control the HTML structure and implement animations that are easily done with Framer Motion.

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/react-aria-demo-3p5g5z

### Version

react-aria@3.33.1, react-aria-components@1.2.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS 14.5

**Comment by snowystinger** [comment] 2024-07-12 05:35
Thanks for the issue, this is a duplicate of https://github.com/adobe/react-spectrum/issues/6453

**Closed by snowystinger** 2024-07-12 05:35 UTC
