### ISSUE TITLE
<FocusScope contain> issue with text selection

### ISSUE THREAD

**Issue by pascalduez** [adobe/react-spectrum#1604] opened 2021-02-18 17:27 UTC
# 🐛 Bug Report 

Inside a `<FocusScope contain>` with a focused element inside, text selection becomes very hard and feels quite buggy.  
As soon as there's an element focused.   

## 🤔 Expected Behavior

Normal text selection.

## 😯 Current Behavior

On Firefox you loose control over what your currently trying to select, it selects a whole lot more.
On chrome the visual selection indicator does not even show up.

Firefox
https://user-images.githubusercontent.com/335467/108395631-4bb60880-7216-11eb-96c6-c2de7d801f7a.mp4

Chrome
https://user-images.githubusercontent.com/335467/108395671-5375ad00-7216-11eb-898b-a2dc9f25406f.mp4

## 💁 Possible Solution

Somehow related to #1479, I guess clicking outside the focused element should blur it.

## 🔦 Context

Building a dialog / modal component.

## 💻 Code Sample

https://codesandbox.io/s/react-aria-focusscope-doesnt-allow-blur-forked-5e2ls?file=/src/App.tsx

## 🌍 Your Environment

`"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0"`
`"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36"`
`"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15 Epiphany/605.1.15"`

## 🧢 Your Company/Team

Gandi

**Comment by LFDanLu** [comment] 2021-02-18 19:15
@pascalduez I believe this is working as intended and as @snowystinger mentioned [here](https://github.com/adobe/react-spectrum/issues/1479#issuecomment-763278443), allowing a state where nothing is focused within the FocusScope could be dangerous/confusing to screen readers. A fix to the above sandbox would be to perhaps add a wrapping div around the contents with tabIndex=-1 much like we do for our spectrum Modal/Dialogs. This would give focus a place to go when clicking away from the input field and allow you to perform text selection. What do you think?

**Comment by LFDanLu** [comment] 2021-03-24 18:05
Closing for now, feel free to reopen!

**Closed by LFDanLu** 2021-03-24 18:05 UTC
Labels: waiting
