### ISSUE TITLE
The usePreventScroll hook fail when used multiple times simultaneously

### ISSUE THREAD

**Issue by armandabric** [adobe/react-spectrum#3054] opened 2022-04-21 13:23 UTC
# 🐛 Bug Report 

When using the `usePreventScroll` hook more than one at the same time break the scrollbar emulation. For example: when opening a modal on top of the modal, or opening a modal in a drawer...

https://github.com/adobe/react-spectrum/blob/378582d606bf55c9937d74c82eb5a9f4fcb82018/packages/%40react-aria/overlays/src/usePreventScroll.ts#L60-L63

## 🤔 Expected Behavior

The second call of `usePreventScroll` hook should detect that the scroll is already prevented.

## 😯 Current Behavior

The second call of `usePreventScroll` hook try to recalculate the scrollbar width but the scrollbar is not available anymore (removed by the first `usePreventScroll` hook call.

## 💁 Possible Solution

Add a `data-react-aria-scroll-prevented` attribute on the HTML element to detect the multiple usage.

## 💻 Code Sample

Here a small reproduction: when you only disable once the scroll, it works. When you disable it a second time the pink div size increase: this is the bug. The padding right that preserve the scrollbar space disappear.

https://codesandbox.io/s/elated-bell-gmx4gl?file=/src/App.js

**Comment by snowystinger** [comment] 2022-04-21 17:12
Thanks for the repro. I noticed you can also get it into a state where both buttons says "prevent scroll", meaning scrolling should be possible, but the scroll bar is hidden. Just by clicking one, then the other, then doing both of them again in the same order.

**Comment by armandabric** [comment] 2022-04-21 17:32
The use case is simple: we have a drawer that open another drawer (one on top of the other).

**Comment by snowystinger** [comment] 2022-04-21 18:41
For anyone working in storybook on this bug, I can see extra reserving space in https://reactspectrum.blob.core.windows.net/reactspectrum/731d2382e64f8f07c81be3fd945a34fa6eca42c1/storybook/index.html?path=/story/dialogtrigger--nested-modals by adding a height to the provider that causes the page to scroll.

What's odd though is that I don't see the behavior noted in my comment above. The scrollbar is restored appropriately. I can't get it stuck in a situation where the scrollbar ends up hidden when it should be shown.

**Comment by fabianludwig** [comment] 2022-12-05 14:29
This bug will be fixed as soon as [(#3784) Properly restore original page scrollability for DialogContainer case](https://github.com/adobe/react-spectrum/pull/3784) is merged and published.

**Comment by reidbarber** [comment] 2023-10-26 15:13
Closing since this was fixed by #3784. Updated react-aria in the codesandbox and can no longer reproduce.

**Closed by reidbarber** 2023-10-26 15:13 UTC
Labels: bug
