### ISSUE TITLE
Unable to resolve module @swc/helpers/cjs/_class_private_field_init.cjs from /Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/@react-aria/interactions/dist/main.js

### ISSUE THREAD

**Issue by michaelroevievictoria** [adobe/react-spectrum#4894] opened 2023-08-10 15:20 UTC
### Provide a general summary of the issue here

I have an error 

```
Error: Unable to resolve module @swc/helpers/cjs/_class_private_field_init.cjs from /Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/@react-aria/interactions/dist/main.js: @swc/helpers/cjs/_class_private_field_init.cjs could not be found within the project or in these directories:
  node_modules
  ../node_modules
  ../../../node_modules
  2 | var $goTMa$react = require("react");
  3 | var $goTMa$swchelperscjs_class_private_field_getcjs = require("@swc/helpers/cjs/_class_private_field_get.cjs");
> 4 | var $goTMa$swchelperscjs_class_private_field_initcjs = require("@swc/helpers/cjs/_class_private_field_init.cjs");
    |                                                                 ^
  5 | var $goTMa$swchelperscjs_class_private_field_setcjs = require("@swc/helpers/cjs/_class_private_field_set.cjs");
  6 | var $goTMa$reactariassr = require("@react-aria/ssr");
  7 |
    at ModuleResolver.resolveDependency (/Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:15)
    at DependencyGraph.resolveDependency (/Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async addDependency (/Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 2)
   
```

Not sure if some libraries connected to another libraries

but im using native-base 

Im not using @swc/helpers

### 🤔 Expected Behavior?

it should be work and not having an error I also try to path but it show well in vscode.

### 😯 Current Behavior

```
Error: Unable to resolve module @swc/helpers/cjs/_class_private_field_init.cjs from /Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/@react-aria/interactions/dist/main.js: @swc/helpers/cjs/_class_private_field_init.cjs could not be found within the project or in these directories:
  node_modules
  ../node_modules
  ../../../node_modules
  2 | var $goTMa$react = require("react");
  3 | var $goTMa$swchelperscjs_class_private_field_getcjs = require("@swc/helpers/cjs/_class_private_field_get.cjs");
> 4 | var $goTMa$swchelperscjs_class_private_field_initcjs = require("@swc/helpers/cjs/_class_private_field_init.cjs");
    |                                                                 ^
  5 | var $goTMa$swchelperscjs_class_private_field_setcjs = require("@swc/helpers/cjs/_class_private_field_set.cjs");
  6 | var $goTMa$reactariassr = require("@react-aria/ssr");
  7 |
    at ModuleResolver.resolveDependency (/Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:15)
    at DependencyGraph.resolveDependency (/Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async addDependency (/Users/mrv/Desktop/Projects/art-hearts-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 2)
   
```

### 🖥️ Steps to Reproduce

hmmmm I just run the app it tells me the error its your library ???

### Version

-

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

mbp m2

**Comment by reidbarber** [comment] 2023-08-10 15:40
Can you specify which version of React Spectrum you're using, and which build tool you're using for your app?

**Comment by jakecrump** [comment] 2023-08-10 15:54
Having the same issue. Unsure if it impacts other packages but specifically for me, `@react-aria/button` version `3.8.1` is causing the above error. I added an override to an earlier version (3.8.0) and the error goes away.

**Comment by michaelroevievictoria** [comment] 2023-08-10 16:01
@reidbarber Im using react-native, actually im not sure why the error comes on this library I have already suspected that this issue is within the native-base but I try to bump up the library but the error goes still the same .

![image](https://github.com/adobe/react-spectrum/assets/6307916/2930ae11-3364-488d-a956-cd50b180f3c3)


> Can you specify which version of React Aria you're using, and which build tool you're using for your app?

**Comment by michaelroevievictoria** [comment] 2023-08-10 16:06
Added info 

![image](https://github.com/adobe/react-spectrum/assets/6307916/e93bfa82-6344-4f52-88fb-5dbfcda68163)

![image](https://github.com/adobe/react-spectrum/assets/6307916/2f8fc2d8-16ae-47fe-9f7d-791149d7f18f)

**Comment by reidbarber** [comment] 2023-08-10 16:12
@jakecrump which build tool and version are you using for your app? Does this happen to be an older version of Next.js?

**Comment by reidbarber** [comment] 2023-08-10 16:13
@michaelroevievictoria is this using Expo? If so, which version?

**Comment by michaelroevievictoria** [comment] 2023-08-10 16:14
@reidbarber im using react native cli 
```
"react-native": "0.69.3",
"native-base": "3.2.2-rc.3",
```

**Comment by jakecrump** [comment] 2023-08-10 16:33
> @jakecrump which build tool and version are you using for your app? Does this happen to be an older version of Next.js?

Yeah, it's Next `12.3.2` (updating to 13 is not possible at this time)

**Comment by LFDanLu** [comment] 2023-08-10 16:42
I believe this issue is the same as [this one](https://github.com/adobe/react-spectrum/issues/4425), see this [comment](https://github.com/adobe/react-spectrum/issues/4425#issuecomment-1626864624) for more details.

**Comment by jakecrump** [comment] 2023-08-10 17:23
Since it's a third-party module for my case, I'm unable to manually downgrade (for now). Fortunately, adding this override to the package.json seems to work until a more permanent solution can be explored.
```
  "overrides": {
    "@react-aria/interactions": "3.16.0"
  }
  ```

**Comment by dcisneros2** [comment] 2023-08-10 20:11
The issue is happening on react-native, started last night since builds were working before, looks like it lines up with react-aria/interactions update. Not using dependency directly but react-native-base uses it.

@swc/helpers version referenced is 0.51.0, but this we are also not using directly.

**Comment by devongovett** [comment] 2023-08-10 21:52
Looking inside `@swc/helper`, it looks like the requested file does exist: https://unpkg.com/browse/@swc/helpers@0.5.1/cjs/_class_private_field_init.cjs

Can you verify what version of Metro bundler you are using? Looks like `.cjs` file support was added around a year ago in 0.72.0. https://github.com/facebook/metro/issues/535

**Comment by devongovett** [comment] 2023-08-10 21:56
Oh, looks like you're using react-native 0.69.3 according to your above comment. That version is over a year old and marked as deprecated on npm: https://www.npmjs.com/package/react-native/v/0.69.3. Looks like it is also using an old version of metro from before `.cjs` support was added. Any chance you can upgrade your version?

**Comment by dcisneros2** [comment] 2023-08-10 22:10
Using ^0.71.1 of metro. React native 0.66. 

Upgrading will be pretty difficult to do. Dependencies in current project are not compatible with later node.

**Comment by devongovett** [comment] 2023-08-10 22:16
Hmm. I'm not really sure what we can do here. We don't control the `@swc/helpers` project, it's just used as part of our build.

Maybe you can try to configure your version metro so it accepts `.cjs` files? This comment might provide a clue about how to do it. https://github.com/facebook/metro/issues/535#issuecomment-1180120485 I haven't personally used React Native or Metro so I'm not sure how much more I can help.

**Comment by michaelroevievictoria** [comment] 2023-08-10 23:36
I solve mine , my issue now is within react native 

1. **Create` metro.config.js`:**

Create a `metro.config.js` file in the root directory of your React Native CLI project if it doesn't already exist.

2. **Adjust Configuration:**
Open the `metro.config.js` file and configure Metro's resolver to include the .cjs extension:

3. **Adjust Module Imports:**
Open the metro.config.js file and configure Metro's resolver to include the .cjs extension:

```
module.exports = {
  resolver: {
    sourceExts: ['js', 'json', 'ts', 'tsx', 'cjs'], // Add 'cjs' as a source extension
  },
};
```

**Comment by VAIMORSS** [comment] 2023-08-14 17:09
@michaelroevievictoria it worked for me :)

**Closed** 2023-08-15 04:29 UTC

**Comment by karthikeyancontus** [comment] 2023-08-16 12:33
module.exports = {
  resolver: {
    sourceExts: ['js', 'json', 'ts', 'tsx', 'cjs'], // Add 'cjs' as a source extension
  },
};
RN version is "react-native" : "0.69.12", it worked for me

**Comment by devongovett** [comment] 2023-08-17 20:48
For those of you using Next.js on this thread, I reached out to the Vercel folks and they were nice enough to backport a fix to `@swc/helpers` that you can use with Next v12! See https://github.com/vercel/next.js/issues/48593#issuecomment-1681930868 for how to override the version with your package manager.

**Comment by sidalikharef** [comment] 2023-08-23 05:54
> I solve mine , my issue now is within `"react-native": "0.69.3"`
> 
> 1. **Create` metro.config.js`:**
> 
> Create a `metro.config.js` file in the root directory of your React Native CLI project if it doesn't already exist.
> 
> 2. **Adjust Configuration:**
>    Open the `metro.config.js` file and configure Metro's resolver to include the .cjs extension:
> 3. **Adjust Module Imports:**
>    Open the metro.config.js file and configure Metro's resolver to include the .cjs extension:
> 
> ```
> module.exports = {
>   resolver: {
>     sourceExts: ['js', 'json', 'ts', 'tsx', 'cjs'], // Add 'cjs' as a source extension
>   },
> };
> ```

it worked for me Thanks 🌹

**Comment by carlosq-ordering** [comment] 2023-09-01 19:01
> Create

it worked for me Thanks 🌹

**Comment by samuelprogramer** [comment] 2023-11-12 14:34
Using `"react-native": "0.72.5",`

> I solve mine , my issue now is within `"react-native": "0.69.3"`
> 
> 1. **Create` metro.config.js`:**
> 
> Create a `metro.config.js` file in the root directory of your React Native CLI project if it doesn't already exist.
> 
> 2. **Adjust Configuration:**
>    Open the `metro.config.js` file and configure Metro's resolver to include the .cjs extension:
> 3. **Adjust Module Imports:**
>    Open the metro.config.js file and configure Metro's resolver to include the .cjs extension:
> 
> ```
> module.exports = {
>   resolver: {
>     sourceExts: ['js', 'json', 'ts', 'tsx', 'cjs'], // Add 'cjs' as a source extension
>   },
> };
> ```
