### ISSUE TITLE
DateRange picker get focused even when clicking outside the component

### ISSUE THREAD

**Issue by mauron85** [adobe/react-spectrum#6025] opened 2024-03-08 08:56 UTC
### Provide a general summary of the issue here

DateRange picker get focused even when clicking outside the component. Watch following gif:

![2024-03-08-09-51-07](https://github.com/adobe/react-spectrum/assets/359450/85237ba0-137b-4497-b485-405de7c3b45e)

### 🤔 Expected Behavior?

DateRangePicker get focus only when either label or the input is clicked or focused via Tab key

### 😯 Current Behavior

DateRangePicker get focus when clicking outside the component

### 🔦 Context

https://react-spectrum.adobe.com/react-aria/DateRangePicker.html

### 🖥️ Steps to Reproduce

Visit example:

https://react-spectrum.adobe.com/react-aria/DateRangePicker.html

click few pixels bellow the component

### Version

1.01

### What browsers are you seeing the problem on?

Microsoft Edge

### What operating system are you using?

Windows 10

**Comment by snowystinger** [comment] 2024-03-08 10:33
Thanks, closing as a duplicate of https://github.com/adobe/react-spectrum/issues/3164

**Closed by snowystinger** 2024-03-08 10:33 UTC
