### ISSUE TITLE
Disabled Picker onClick changes the text color for a moment

### ISSUE THREAD

**Issue by bryantabaird** [adobe/react-spectrum#1079] opened 2020-09-17 19:18 UTC
When clicking on the button of a disabled Picker, the text flashes black for a brief moment.

Note that this does not happen when clicking on the Picker chevron arrow.

See attached video for example

[Screen Recording 2020-09-16 at 2.30.01 PM.zip](https://github.com/adobe/react-spectrum/files/5241388/Screen.Recording.2020-09-16.at.2.30.01.PM.zip)

**Comment by snowystinger** [comment] 2020-09-17 20:11
I'm unable to reproduce in either of our two themes here https://react-spectrum.adobe.com/react-spectrum/Picker.html#disabled
does it only happen in light? (not lightest)

**Comment by bryantabaird** [comment] 2020-09-17 20:30
It happens in light and dark. I just tried here: https://react-spectrum.adobe.com/react-spectrum/Picker.html#disabled and found that I could not repro.

I also found that to repro, you may need to set the `selectedKey` prop to one of the items:

```
const items = [{ id: 'dimension', label: 'Dimension' }, { id: 'metric', label: 'Metric' }];
<Picker
	label={'Test'}
	selectedKey={'dimension'}
	isDisabled
	items={items}
>
```

**Comment by snowystinger** [comment] 2020-09-17 21:45
O yep, need the selectedKey. Cool, thanks for reporting 👍

**Comment by bryantabaird** [comment] 2020-09-17 21:57
Yep! Sorry I didn't report before, I wasn't aware it was needed until your previous comment made me look into it

**Comment by snowystinger** [comment] 2020-09-17 22:13
No worries, videos are great, but our preferred method of bug reports is a reproducible case with steps, the closer it can be to just a single one of our components with no outside influence, the easier and faster we can track it down and fix it :)
Otherwise we're just guessing.

**Comment by mischnic** [comment] 2020-09-29 10:05
This happens because of this declaration
https://github.com/adobe/react-spectrum/blob/bd9852ce71c11a970a135668373e16cf8962dc3c/packages/%40adobe/spectrum-css-temp/components/dropdown/skin.css#L71-L73

A disabled button is still `:active` when pressed:

https://codepen.io/mischnic/pen/JjXqPKr

Maybe this was already fixed in Spectrum CSS? I can't even find a "dropdown" component anymore in https://github.com/adobe/spectrum-css.

**Comment by dannify** [comment] 2020-10-06 16:14
Maybe it was renamed to Picker? In any case it doesn't look like it exists in there so we should fix it here too.

**Closed** 2020-11-06 18:53 UTC
Labels: bug, rsp:Picker
