### ISSUE TITLE
RAC Tooltip wrong data-placement

### ISSUE THREAD

**Issue by patrickkuhlmann** [adobe/react-spectrum#6659] opened 2024-07-03 11:36 UTC
when you supply a combined placement as in 'bottom end' for example the resulting data-placement prop will only contain bottom as thats what is returned as placement by the `useOverlayPosition` Hook

### 🤔 Expected Behavior?

data-placement should accurately display `bottom end`

### 😯 Current Behavior

data-placement displays only `bottom`

**Comment by snowystinger** [comment] 2024-07-08 00:52
closing as a duplicate of https://github.com/adobe/react-spectrum/issues/6517

**Closed by snowystinger** 2024-07-08 00:52 UTC
