### ISSUE TITLE
The react-aria-components Combobox automatically closed list of options after select a very long text option

### ISSUE THREAD

**Issue by thaihoangminh** [adobe/react-spectrum#5971] opened 2024-02-29 03:53 UTC
### Provide a general summary of the issue here

After selecting the last option `Option 3 with a very long text` I can not select the other options due to the list of options in the Popover automatically closed.

Here is a link example that I have followed and cloned: https://react-spectrum.adobe.com/react-aria/examples/user-combobox.html

### 🤔 Expected Behavior?

The popover should not automatically close after selecting a very long text of the option

### 😯 Current Behavior

The popover automatically closes after selecting a very long text of the option

### 🖥️ Steps to Reproduce

Select `Option 3 with a very long text` after selecting the first or second option from the list. Once selected, the first or second option can no longer be chosen.

Codesanbox: https://codesandbox.io/p/devbox/react-aria-components-forked-xd3nhc

### Version

1.1.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOs

**Comment by reidbarber** [comment] 2024-02-29 03:55
This looks like a duplicate of https://github.com/adobe/react-spectrum/issues/5653

**Closed** 2024-02-29 04:17 UTC
