### ISSUE TITLE
useResizeObserver not preventing Resize Observer errors in some situations

### ISSUE THREAD

**Issue by dgsousa** [adobe/react-spectrum#1924] opened 2021-05-18 03:58 UTC
# 🐛 Bug Report 

In some situations, spectrum components that use `useResizeObserver` throw errors such as 
`ResizeObserver loop limit exceeded` 
to be thrown in Chrome and
`ResizeObserver loop completed with undelivered notifications.`
in Firefox. 

Generally these errors are benign and can be swallowed. However, Safari's CORS policy throws anonymous script errors and swallowing all script errors in Safari is a less than ideal solution.

## 🤔 Expected Behavior

useResizeObserver should not be causing Resize Observers to throw errors.

## 💁 Possible Solution

Resize Observers generally throw these errors to prevent infinite loops as detailed here:
https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded

But these errors are preventable using the approach detailed in this article:
https://blog.elantha.com/resizeobserver-loop-limit-exceeded/

## 💻 Code Sample

```
import React from "react";
import ReactDOM from "react-dom";
import App from "./App";

window.addEventListener('error', (err) => {
    console.log(err);
})

ReactDOM.render(<App />, document.getElementById("root"));
```

```
import React, {
  useEffect,
  useState,
} from 'react';
import {
  defaultTheme,
  Flex,
  View,
  Provider,
  Content,
  Text,
} from '@adobe/react-spectrum';
import {
  Tabs,
  Item,
} from '@react-spectrum/tabs';


export default function App() {
  const [
    widthUnder1100,
    setWidthUnder1100,
  ] = useState(window.innerWidth < 1100);


  useEffect(() => {
    const handleResize = () => {
      setWidthUnder1100(window.innerWidth < 1100);
    };
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  const shrink = widthUnder1100;
  return (
    <Provider theme={ defaultTheme } colorScheme='light'>
      <Flex>
        <div
          data-id='collapse'
          style={ { width: shrink ? '200px' : 'auto' } }>
          <Tabs aria-label='Chat log collapse example'>
            <Item title='John Doe' key='item1'>
              <Content marginTop='size-250' marginStart='size-125'>
                <Text>1</Text>
              </Content>
            </Item>
            <Item title='Jane Doe' key='item2'>
              <Content marginTop='size-250' marginStart='size-125'>
                <Text>2</Text>
              </Content>
            </Item>
            <Item title='Joe Bloggs' key='item3'>
              <Content marginTop='size-250' marginStart='size-125'>
                <Text>3</Text>
              </Content>
            </Item>
          </Tabs>
        </div>
      </Flex>
    </Provider>
  );
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 16
| Browser          | Chrome / Firefox / Safari
| Operating System | MacOS

## 🧢 Your Company/Team
Adobe / Marketo

Marketo

**Comment by LFDanLu** [comment] 2021-06-30 18:13
Reproduced the error locally, will have to investigate to see if the solution in the blog you linked has any unforeseen side effects

**Comment by dashed** [comment] 2022-02-25 23:36
@LFDanLu is this still being investigated? We're seeing this in [sentry.io](https://sentry.io/) after this PR was merged https://github.com/getsentry/sentry/pull/32061

**Comment by LFDanLu** [comment] 2022-02-25 23:54
@dashed thanks for the reminder, this must have fell off my radar. I'll see if I can get this into one of our upcoming sprints but would welcome a PR!

Just to note, my concerns were mainly centered around any odd flickering that may occur with adding a requestAnimationFrame. If any flickering was noticed, I was leaning towards trying to swallow this error/prevent it from causing noise since seems to be a benign error.

**Comment by snowystinger** [comment] 2023-03-15 07:24
See https://github.com/adobe/react-spectrum/pull/4204

**Comment by snowystinger** [comment] 2023-03-30 21:56
We've found someone able to reproduce again, reopening for more investigation

**Comment by snowystinger** [comment] 2023-04-26 22:42
I have a minimal reproduction https://codesandbox.io/s/clever-hodgkin-ygvn7r?file=/src/App.js

Open in Safari
Make the window not super tall
Open the console
Open left and right combobox

**Comment by LFDanLu** [comment] 2023-09-12 22:21
Looks like this is still happening for the TableView in React 17/16 specifically. Try https://reactspectrum.blob.core.windows.net/reactspectrum/14553eb3181befc00e81883864743b323491ce3a/storybook-16/index.html?path=/story/tableview--resize-test&providerSwitcher-express=false and https://reactspectrum.blob.core.windows.net/reactspectrum/14553eb3181befc00e81883864743b323491ce3a/storybook-17/index.html?path=/story/tableview--resize-test&providerSwitcher-express=false and check the console upon resizing the browser window in such a way that the TableView shrinks.

**Comment by LFDanLu** [comment] 2023-09-14 00:01
Some additional info: this only started happening in React 17/16 from this [PR](https://github.com/adobe/react-spectrum/pull/4564). Before this, we didn't receive the `ResizeObserver loop completed with undelivered notifications.` warning in React 18/17/16 when resizing the TableView's containing window at least since early Dec 2022. 

Storybooks for testing, to reproduce simply open the javascript console and add a error listener via `window.addEventListener('error', (e) => console.log('ERROR: ', e));` and try shrinking the story window to the point that the TableView's width grows smaller.

breaking case: https://reactspectrum.blob.core.windows.net/reactspectrum/11b5be3a08cfcd564fcb98f534cdabeb64ba0711/storybook-17/iframe.html?scrolling=false&providerSwitcher-locale=&providerSwitcher-theme=&providerSwitcher-scale=&providerSwitcher-express=false&args=&id=tableview--static&viewMode=story

working case from the commit [before](https://github.com/adobe/react-spectrum/commit/fc0079efaf89d1b723027d313217b88be883af1e): https://reactspectrum.blob.core.windows.net/reactspectrum/91515d24149449ffea8099f5c06eb588bd6b6c15/storybook-17/iframe.html?scrolling=false&strict=false&args=&providerSwitcher-locale=&providerSwitcher-theme=&providerSwitcher-scale=&providerSwitcher-express=false&id=tableview--static&viewMode=story

**Closed** 2023-11-22 02:47 UTC
Labels: enhancement
