### ISSUE TITLE
Image component onError handler

### ISSUE THREAD

**Issue by sdiverdi** [adobe/react-spectrum#3913] opened 2023-01-13 00:45 UTC
# 🙋 Feature Request

Add an `onError` property to the `Image` component so that we can handle the image not loading correctly.

## 🤔 Expected Behavior

```
<Image src={url} alt={altText} onError={handleError} />
```

Calls `handleError` when there is an error in the image loading.

## 😯 Current Behavior

No way to handle errors in image loading, displays a broken file icon and the alt text.

## 💁 Possible Solution

I've worked around it by getting the internal `img` tag and adding a listener to it:

```
const imgRef = React.useRef(null);

React.useEffect(() => {
  const divEl = imgRef.current.UNSAFE_getDOMNode();
  const imgEls = divEl.getElementsByTagName('img');
  for (const imgEl of imgEls) {
    imgEl.addEventListener('error', handleError);
  }
  return () => {
    for (const imgEl of imgEls) {
      imgEl.removeEventListener('error', handleError);
    }
  };
}, []);

return <Image ref={imgRef} />;
```

## 🔦 Context

When an image URL can't be loaded, I want to remove the component displaying the image, rather than displaying a broken file icon.

## 💻 Examples

A gallery of images: if an image can't load, don't include the image in the gallery, rather than displaying a broken image.

## 🧢 Your Company/Team

Adobe Research

**Comment by snowystinger** [comment] 2023-01-13 01:03
Dupe of https://github.com/adobe/react-spectrum/issues/3404, as a teammate remembered.
It would be useful to know more about your use case if you don't mind replying over there.

Specifically, it'd be good to know more about your use case, are you using our CardView?

**Closed by snowystinger** 2023-01-13 01:03 UTC
Labels: enhancement
