### ISSUE TITLE
Simulate hovered, pressed, and focused-visible states

### ISSUE THREAD

**Issue by andrecasal** [adobe/react-spectrum#6198] opened 2024-04-12 15:16 UTC
### Provide a general summary of the feature here

Simulate hovered, pressed, and focused-visible states

### 🤔 Expected Behavior?

Programmatically control state.

### 😯 Current Behavior

Setting `data-hovered="true"` doesn't work. Looking into the `useHover()`also doesn't seem to work.

### 💁 Possible Solution

Copy the button's source code and hard-code the state?

### 🔦 Context

I'm building a color contrast test page that automated tests will run against.

Being automated tests, I need the components to retain a particular state (like hover or pressed).

![Screenshot 2024-04-12 at 16 12 21](https://github.com/adobe/react-spectrum/assets/22457463/cdef43e4-b595-4bf4-97ed-c5b51327976e)

### 🧢 Your Company/Team

https://verveui.pro/

**Comment by reidbarber** [comment] 2024-04-12 15:29
I don't think you can programmatically trigger a hover from within the browser since it is a [trusted event](https://www.w3.org/TR/DOM-Level-3-Events/#trusted-events), but instead you'll want to have a way to apply those styles through some other means.

In React Spectrum, we apply `UNSAFE_className={classNames(styles, 'is-hovered')} data-hover="true"` to elements to trigger the hover styles for visual regression testing with Chromatic. Unit tests cover whether or not the classes/attributes actually get applied for a hover event.

Alternatively, you could look at using something like [playwright](https://playwright.dev/docs/input#mouse-click) to run interactions in a real browser and do [visual comparisons.](https://playwright.dev/docs/test-snapshots)

**Comment by andrecasal** [comment] 2024-04-12 16:05
Hey @reidbarber, thanks for the feedback.

I wanted the page to serve as a target for both manual and automated tests.

Having Playwright interact works, but the page couldn't be used as a target for manual tests without having to interact with the elements - which is cumbersome.

**Comment by reidbarber** [comment] 2024-04-12 17:14
Yeah, I'm not sure there is a good solution for handling this unfortunately.

**Comment by snowystinger** [comment] 2024-04-12 23:08
For what it's worth, we've split our own storybooks so that we have one for manual testing and one for visual regressions. We found they were just too different in goals to try to maintain as a single target. For instance, in your screenshot, what does it mean for a manual tester to interact with the button which is retaining the pressed state?

We don't want to expose setting these interactive states as API because that opens them for non-accessible misuse outside of tests. As @reidbarber pointed out, these are all trusted user event states.

I'm going to close this issue for now because there are ways to handle this. We can reopen if a new concern comes up. Thanks for the discussion!

**Closed by snowystinger** 2024-04-12 23:08 UTC

**Comment by andrecasal** [comment] 2024-04-13 11:43
Hey @snowystinger, the manual tests are merelly visual, not interactive, i.e. someone looks at the page with all component states and determines "yeah, looks good".

Everything else is automated with Playwright for testing interactions (hover, pressed, focus-active, etc), and checking the [APCA](https://www.achecks.org/apca-wcag-3-accessible-colour-contrast-checker/) color contrast results under each component (which the manual tester can also see).

Creating redundant selectors like `.is-hovered` for `[data-hovered]` feels wrong 😅 But I'll find a way. Thanks guys!

**Comment by andrecasal** [comment] 2024-04-13 13:33
Leaving my solution here for anyone who bumps into this.

Creating redundant selectors would dirty up my styles - so that was a no go.

What I did instead was programatically read the styles from the stylesheet directly and apply them to each component. Here's an example:
```tsx
import { type MetaFunction } from '@remix-run/node'
import { Button } from '#app/components/buttons/button'
import { Container } from '#app/components/layout/container'
import { Flex } from '#app/components/layout/flex'
import { H1 } from '#app/components/typography/h1'
import { H2 } from '#app/components/typography/h2'
import { useIsomorphicLayoutEffect } from '#app/hooks/useIsomorphicLayoutEffect.js'

export const meta: MetaFunction = () => {
	return [{ name: 'robots', content: `noindex,nofollow` }]
}

export default function UILibraryTestPage() {
	useIsomorphicLayoutEffect(() => {
		const componentRules = Object.entries(document.styleSheets[0].cssRules).filter(rule => rule[1].name === 'components')
		const buttonStyles = Object.entries(componentRules[0][1].cssRules).filter(rule => rule[1].selectorText === '.button')
		const buttonPrimaryStyles = Object.entries(buttonStyles[0][1].cssRules).filter(rule => rule[1].selectorText === '&.primary')
		const buttonSecondaryStyles = Object.entries(buttonStyles[0][1].cssRules).filter(rule => rule[1].selectorText === '&.secondary')
		const buttonDangerStyles = Object.entries(buttonStyles[0][1].cssRules).filter(rule => rule[1].selectorText === '&.danger')
		const buttonGhostStyles = Object.entries(buttonStyles[0][1].cssRules).filter(rule => rule[1].selectorText === '&.ghost')

		const buttonPrimaryHoveredStyles = Object.entries(buttonPrimaryStyles[0][1].cssRules).filter(rule => rule[1].selectorText === '&[data-hovered]')[0][1].style
		const buttonSecondaryHoveredStyles = Object.entries(buttonSecondaryStyles[0][1].cssRules).filter(rule => rule[1].selectorText === '&[data-hovered]')[0][1].style
		const buttonDangerHoveredStyles = Object.entries(buttonDangerStyles[0][1].cssRules).filter(rule => rule[1].selectorText === '&[data-hovered]')[0][1].style
		const buttonGhostHoveredStyles = Object.entries(buttonGhostStyles[0][1].cssRules).filter(rule => rule[1].selectorText === '&[data-hovered]')[0][1].style

		const buttonPrimaryPressedStyles = Object.entries(buttonPrimaryStyles[0][1].cssRules).filter(rule => rule[1].selectorText === '&[data-pressed]')[0][1].style
		const buttonSecondaryPressedStyles = Object.entries(buttonSecondaryStyles[0][1].cssRules).filter(rule => rule[1].selectorText === '&[data-pressed]')[0][1].style
		const buttonDangerPressedStyles = Object.entries(buttonDangerStyles[0][1].cssRules).filter(rule => rule[1].selectorText === '&[data-pressed]')[0][1].style
		const buttonGhostPressedStyles = Object.entries(buttonGhostStyles[0][1].cssRules).filter(rule => rule[1].selectorText === '&[data-pressed]')[0][1].style

		const buttonPrimaryHovered = document.querySelector('#hovered button.primary')
		const buttonSecondaryHovered = document.querySelector('#hovered button.secondary')
		const buttonDangerHovered = document.querySelector('#hovered button.danger')
		const buttonDisabledHovered = document.querySelector('#hovered button.ghost')

		const buttonPrimaryPressed = document.querySelector('#pressed button.primary')
		const buttonSecondaryPressed = document.querySelector('#pressed button.secondary')
		const buttonDangerPressed = document.querySelector('#pressed button.danger')
		const buttonDisabledPressed = document.querySelector('#pressed button.ghost')

		buttonPrimaryHovered.style = buttonPrimaryHoveredStyles.cssText
		buttonSecondaryHovered.style = buttonSecondaryHoveredStyles.cssText
		buttonDangerHovered.style = buttonDangerHoveredStyles.cssText
		buttonDisabledHovered.style = buttonGhostHoveredStyles.cssText

		buttonPrimaryPressed.style = buttonPrimaryPressedStyles.cssText
		buttonSecondaryPressed.style = buttonSecondaryPressedStyles.cssText
		buttonDangerPressed.style = buttonDangerPressedStyles.cssText
		buttonDisabledPressed.style = buttonGhostPressedStyles.cssText
	})

	return (
		<Container>
			<H1>Color Contrast Test Page</H1>
			<Flex>
				<Flex orientation="vertical" gap="10" data-theme="light" className="bg-background text-foreground rounded-xl px-5 pb-5">
					<H2>Button</H2>
					<Flex gap="10" id="normal">
						<Button size="md" variant="primary" className="w-28">
							Primary
						</Button>
						<Button size="md" variant="secondary" className="w-28">
							Secondary
						</Button>
						<Button size="md" variant="danger" className="w-28">
							Danger
						</Button>
						<Button size="md" variant="ghost" className="w-28">
							Ghost
						</Button>
					</Flex>
					<Flex gap="10" id="hovered">
						<Button size="md" variant="primary" className="w-28">
							Hovered
						</Button>
						<Button size="md" variant="secondary" className="w-28">
							Hovered
						</Button>
						<Button size="md" variant="danger" className="w-28">
							Hovered
						</Button>
						<Button size="md" variant="ghost" className="w-28">
							Hovered
						</Button>
					</Flex>
					<Flex gap="10" id="pressed">
						<Button size="md" variant="primary" className="w-28">
							Pressed
						</Button>
						<Button size="md" variant="secondary" className="w-28">
							Pressed
						</Button>
						<Button size="md" variant="danger" className="w-28">
							Pressed
						</Button>
						<Button size="md" variant="ghost" className="w-28">
							Pressed
						</Button>
					</Flex>
					<Flex gap="10" id="disabled">
						<Button size="md" variant="primary" className="w-28" isDisabled>
							Disabled
						</Button>
						<Button size="md" variant="secondary" className="w-28" isDisabled>
							Disabled
						</Button>
						<Button size="md" variant="danger" className="w-28" isDisabled>
							Disabled
						</Button>
						<Button size="md" variant="ghost" className="w-28" isDisabled>
							Disabled
						</Button>
					</Flex>
					<H2>Badge/Chip/Tag?</H2>
					<Flex gap="10">
						<Button size="md" variant="primary">
							Primary
						</Button>
						<Button size="md" variant="secondary">
							Secondary
						</Button>
						<Button size="md" variant="danger">
							Danger
						</Button>
						<Button size="md" variant="ghost">
							Ghost
						</Button>
					</Flex>
					<H2>Alert</H2>
					<Flex gap="10">
						<Button size="md" variant="primary">
							Primary
						</Button>
						<Button size="md" variant="secondary">
							Secondary
						</Button>
						<Button size="md" variant="danger">
							Danger
						</Button>
						<Button size="md" variant="ghost">
							Ghost
						</Button>
					</Flex>
					<H2>Card</H2>
					<Flex gap="10">
						<Button size="md" variant="primary">
							Primary
						</Button>
						<Button size="md" variant="secondary">
							Secondary
						</Button>
						<Button size="md" variant="danger">
							Danger
						</Button>
						<Button size="md" variant="ghost">
							Ghost
						</Button>
					</Flex>
				</Flex>
				<Flex orientation="vertical" gap="10" data-theme="dark" className="bg-background text-foreground rounded-xl px-5 pb-5">
					<H2>Button</H2>
					<Flex gap="10">
						<Button size="md" variant="primary" className="w-28">
							Primary
						</Button>
						<Button size="md" variant="secondary" className="w-28">
							Secondary
						</Button>
						<Button size="md" variant="danger" className="w-28">
							Danger
						</Button>
						<Button size="md" variant="ghost" className="w-28">
							Ghost
						</Button>
					</Flex>
					<Flex gap="10">
						<Button size="md" variant="primary" className="w-28" data-hovered="true">
							Hovered
						</Button>
						<Button size="md" variant="secondary" className="w-28" data-hovered="true">
							Hovered
						</Button>
						<Button size="md" variant="danger" className="w-28" data-hovered="true">
							Hovered
						</Button>
						<Button size="md" variant="ghost" className="w-28" data-hovered="true">
							Hovered
						</Button>
					</Flex>
					<Flex gap="10">
						<Button size="md" variant="primary" className="w-28" data-pressed="true">
							Pressed
						</Button>
						<Button size="md" variant="secondary" className="w-28" data-pressed="true">
							Pressed
						</Button>
						<Button size="md" variant="danger" className="w-28" data-pressed="true">
							Pressed
						</Button>
						<Button size="md" variant="ghost" className="w-28" data-pressed="true">
							Pressed
						</Button>
					</Flex>
					<Flex gap="10">
						<Button size="md" variant="primary" className="w-28" data-focus-visible="true">
							Focus
						</Button>
						<Button size="md" variant="secondary" className="w-28" data-focus-visible="true">
							Focus
						</Button>
						<Button size="md" variant="danger" className="w-28" data-focus-visible="true">
							Focus
						</Button>
						<Button size="md" variant="ghost" className="w-28" data-focus-visible="true">
							Focus
						</Button>
					</Flex>
					<H2>Badge/Chip/Tag?</H2>
					<Flex gap="10">
						<Button size="md" variant="primary">
							Primary
						</Button>
						<Button size="md" variant="secondary">
							Secondary
						</Button>
						<Button size="md" variant="danger">
							Danger
						</Button>
						<Button size="md" variant="ghost">
							Ghost
						</Button>
					</Flex>
					<H2>Alert</H2>
					<Flex gap="10">
						<Button size="md" variant="primary">
							Primary
						</Button>
						<Button size="md" variant="secondary">
							Secondary
						</Button>
						<Button size="md" variant="danger">
							Danger
						</Button>
						<Button size="md" variant="ghost">
							Ghost
						</Button>
					</Flex>
					<H2>Card</H2>
					<Flex gap="10">
						<Button size="md" variant="primary">
							Primary
						</Button>
						<Button size="md" variant="secondary">
							Secondary
						</Button>
						<Button size="md" variant="danger">
							Danger
						</Button>
						<Button size="md" variant="ghost">
							Ghost
						</Button>
					</Flex>
				</Flex>
			</Flex>
		</Container>
	)
}
```

Please excuse TS errors. I'll get to the types later. Ping me if you'd like to have them.

**Comment by drunewin** [comment] 2024-09-27 16:58
@andrecasal FWIW we found that this wrapper component worked also. It wraps a ref'd `Button` along with an effect that calls [`Object.defineProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) to set the state and added tailwind's [`pointer-events-none`](https://tailwindcss.com/docs/pointer-events) class to prevent state changes. Of course, your button also needs to forward refs.

```tsx
interface LockedStateButtonProps extends ButtonProps {
  state: 'hovered' | 'pressed';
}

const LockedStateButton = ({ state, ...props }: LockedStateButtonProps) => {
  const ref = useRef<HTMLButtonElement>(null);
  useLayoutEffect(() => {
    if (ref.current) {
      Object.defineProperty(ref.current.dataset, state, {
        value: 'true',
        writable: false, // Makes the property non-writable, not sure if necessary with 'pointer-events-none'
      });
    }
  }, [state]);
  return <Button {...props} ref={ref} className={'pointer-events-none'} />;
};
```

**Comment by benjavicente** [comment] 2025-02-25 17:58
If anyone stumbles to this issue searching for a general approach, [ref callbacks could be the answer](https://react.dev/reference/react-dom/components/common#ref-callback):

```tsx
import { RefCallback } from "react";

type State = {
  hovered?: boolean;
  pressed?: boolean;
};

export function forceReactAriaState<T extends HTMLElement>(state: State = {}): RefCallback<T> {
  return (element) => {
    if (!element) return;
    element.style.pointerEvents = "none";
    for (const [key, value] of Object.entries(state)) {
      element.dataset[key] = value ? "true" : "false";
    }
  };
}
```

Usage:

```tsx
<Button kind="primary" ref={forceReactAriaState({ hovered: true }} {...args} />
```

This assumes that styling is targeting the dataset, like with the [tailwind plugin](https://react-spectrum.adobe.com/react-aria/styling.html#plugin).
