### ISSUE TITLE
Listbox != Sidenav

### ISSUE THREAD

**Issue by undavide** [adobe/react-spectrum#1433] opened 2021-01-02 09:59 UTC
# ❔ Question

Is the Listbox component meant to work _also_ as a sidenav (see Spectrum Web Components' implementation [here](https://opensource.adobe.com/spectrum-web-components/components/sidenav)) or you plan to have a dedicated component for that purpose?

## 🔦 Context

I'm working on something loosely along the lines of Adobe's own CC sidebar, see:

![image](https://user-images.githubusercontent.com/5939127/103454949-f9ae3780-4ce8-11eb-9b1b-3df7b3fe953c.png)

The closest thing that React components provide is the Listbox, but it looks like bending it to something it wasn't originally meant for.

## 🧢 Your Company/Team

No Adobe employee here :-)

Thanks!

**Comment by LFDanLu** [comment] 2021-01-04 18:27
@undavide We plan to have a separate `SideNav` component, stay tuned!

**Comment by matthewdeutsch** [comment] 2021-01-04 20:14
closing issue, dupe of #1095 - will inform community when we begin work on `SideNav`!

**Closed by matthewdeutsch** 2021-01-04 20:14 UTC
Labels: duplicate
