### ISSUE TITLE
Export maps in all packages to support NodeJS + ESM?

### ISSUE THREAD

**Issue by mayank99** [adobe/react-spectrum#3396] opened 2022-08-11 16:46 UTC
# 🙋 Feature Request

Consider adding `exports` field to the package.json of `react-aria` and all its subpackages.

## 😯 Current Behavior

Currently there is no `exports` field, which means the package doesn't work in NodeJS + ESM environments. 

https://publint.bjornlu.com/react-aria@3.18.0
https://publint.bjornlu.com/@internationalized/string@3.0.0

## 💁 Possible Solution

https://nodejs.org/api/packages.html#exports

## 🔦 Context

I'm trying to use components from `react-aria` with `preact/compat` on the server (SSR) using `astro` (which internally uses `vite@3` which recently switched to [ESM for SSR](https://vitejs.dev/blog/announcing-vite3.html#build-improvements)). I realize this is a convoluted setup but it would be really nice to make this work. Currently it works perfectly on the client but errors on the server, and I opened a bug in the astro repo which led me here. https://github.com/withastro/astro/issues/4107#issuecomment-1212129186

**Comment by snowystinger** [comment] 2022-08-11 19:09
closing as dupe of https://github.com/adobe/react-spectrum/issues/2881

**Closed by snowystinger** 2022-08-11 19:09 UTC

**Comment by mayank99** [comment] 2022-08-11 20:07
@snowystinger Looks like that one is a bug report? Maybe the issue title needs to be updated because I did do a search before creating this issue.

**Comment by snowystinger** [comment] 2022-08-11 21:25
It started as a bug report, it may end up as a feature we add. The same conversation though is happening there https://github.com/adobe/react-spectrum/issues/2881#issuecomment-1209900161 so it'd be better to keep the discussion there. Feel free to chime in on that thread.
Don't worry if you missed it with a search. Anyone who searches and finds yours instead will now find a link to the original. :)
