### ISSUE TITLE
Table with headerless column as last column has side scroll

### ISSUE THREAD

**Issue by jluyau** [adobe/react-spectrum#1283] opened 2020-11-17 22:27 UTC
# 🐛 Bug Report 

If a table has a headerless column (`<Column hideHeader>...</Column>`) as the last column, the table body contents will overflow horizontally and thus can be scrolled a tiny bit.

## 🤔 Expected Behavior

Should fill the space without the need for side scrolling

## 😯 Current Behavior

The row content extends beyond the viewable area, creating a horizontal scrollbar

## 💻 Code Sample

Sandbox: https://codesandbox.io/s/peaceful-albattani-674nd?fontsize=14&hidenavigation=1&theme=dark

Code: 
```
import React from "react";
import { Provider, defaultTheme, ActionButton } from "@adobe/react-spectrum";
import {
  Table,
  TableHeader,
  TableBody,
  Column,
  Row,
  Cell
} from "@react-spectrum/table";
import Add from "@spectrum-icons/workflow/Add";
import "./styles.css";

export default function App() {
  const items = [{ key: "1", name: "File 1" }];
  return (
    <Provider theme={defaultTheme}>
      <Table>
        <TableHeader>
          <Column key="name">Header</Column>
          <Column key="action" hideHeader>
            Action
          </Column>
        </TableHeader>
        <TableBody items={items}>
          {(item) => (
            <Row key={item.key}>
              {(column) => {
                if (column === "action") {
                  return (
                    <Cell>
                      <ActionButton>
                        <Add />
                      </ActionButton>
                    </Cell>
                  );
                }
                return <Cell>{item[column]}</Cell>;
              }}
            </Row>
          )}
        </TableBody>
      </Table>
    </Provider>
  );
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.5.0
| react-spectrum/table | 3.0.0-alpha.8 
| Browser          | Chrome 86.0.4240.198
| Operating System | MacOS Catalina

## 🧢 Your Company/Team

Adobe/quarry

**Comment by LFDanLu** [comment] 2021-06-15 18:11
Can't reproduce in the sandbox nor in local storybook, closing.

**Closed by LFDanLu** 2021-06-15 18:11 UTC
Labels: rsp:TableView
