### ISSUE TITLE
[RAC]  TextField + React Hook Form

### ISSUE THREAD

**Issue by thevipinmishra** [adobe/react-spectrum#5090] opened 2023-09-17 10:33 UTC
I was giving the [TextField](https://react-spectrum.adobe.com/react-aria/TextField.html) component a try, along with [React Hook Form](https://react-hook-form.com/).

Now, adding the props returned by `register` function into the `TextField` component is not working as expected, I know this can easily be solved by spreading the props on the `Input` element that we nest under the TextField anyway, but was curious to know about the API and design decisions.

```js
{name: 'companyName', onChange: ƒ, onBlur: ƒ, ref: ƒ}
```

Passing props to TextField shouldn't just work?

_Originally posted by @thevipinmishra in https://github.com/adobe/react-spectrum/discussions/5089_

**Comment by snowystinger** [comment] 2023-09-17 21:26
I'm not sure what you mean, the props on `TextField` work fine for me? https://codesandbox.io/s/heuristic-cloud-kynmh9?file=/src/App.js

Can you provide a minimal codesandbox to reproduce the issue you're having?

**Comment by cedeber** [comment] 2023-09-18 09:22
`onChange` is not standard with react-aria. It doesn't expose the event, but directly the value. Here's what you need:

```ts
/**
 * Used to make the onChange callback compatible with react-aria wich doesn't send an event but the value of the field
 */
export function useRegisterReactAria<
  TFieldValues extends FieldValues,
  TFieldName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>,
>(
  register: UseFormRegister<TFieldValues>,
): (
  name: TFieldName,
  options?: RegisterOptions<TFieldValues, TFieldName>,
) => Omit<UseFormRegisterReturn<TFieldName>, "onChange"> & Pick<ValueBase<unknown>, "onChange"> {
  return function (name, options) {
    const { onChange, ...rest } = register(name, options);

    return {
      ...rest,
      onChange: (value: unknown) => {
        // We need to expose the name too to make the formState working, like trigger "isDirty", ...
        void onChange({ target: { value, name } });
      },
    };
  };
}

/**
 * Used to make the onChange callback compatible with react-aria. @see useRegisterReactAria
 * The rest of the react-hook-form useForm() function is simply exposed.
 */
export function useFormAria<
  TFieldValues extends FieldValues = FieldValues,
  TContext = unknown,
  TTransformedValues extends FieldValues | undefined = undefined,
>(
  props?: UseFormProps<TFieldValues, TContext>,
): Omit<UseFormReturn<TFieldValues, TContext, TTransformedValues>, "register"> & {
  register: ReturnType<typeof useRegisterReactAria<TFieldValues>>;
} {
  const { register: _register, ...rest } = useForm(props);
  const register = useRegisterReactAria(_register);

  return { ...rest, register };
}
```

The value being `unknown` could probably be better typed from `TFieldValues` but I didn't took the time to inspect more here.

**Comment by cedeber** [comment] 2023-09-18 17:16
Looks like `<Input />` from react-aria-components is a standard input, so `onChange` is standard, unlike the `onChange` from the hook. The `TextField` + `Input` are not using the `inputProps` from the `useTextField` hook. That's why it's working with the components but not if you build your own textfield input with the hook.

@thevipinmishra you need to pass `<Input />` to the controller, not `TextField` https://codesandbox.io/s/react-hook-form-with-ui-library-ts-forked-prcxpt

**Comment by devongovett** [comment] 2023-09-18 18:01
This may work for TextField, but I would recommend using `onChange` on the top-level component and _not_ putting it on `<Input>` directly. For example, with a NumberField, the `onChange` event can be emitted even when the Input does not fire the native onChange (e.g. due to up down arrow key presses). That's why we've standardized on just emitting the value in all onChange events for consistency.

Example: https://codesandbox.io/s/react-hook-form-with-ui-library-ts-forked-9xjlkm?file=/src/index.tsx

**Comment by cedeber** [comment] 2023-09-18 18:57
Ok, I am not using react-aria-components, but good to know. It works like the hook then (which makes sense and is good) I've update my codesandox (yours doesn't work btw) but as expected, the example with the Controller in https://github.com/adobe/react-spectrum/discussions/5089#discussioncomment-7022772 doesn't work. It can't automagically found how onChange works.

**Comment by devongovett** [comment] 2023-12-17 03:44
We now have a section in the docs that shows how to use React Aria Components with React Hook Form. https://react-spectrum.adobe.com/react-aria/forms.html#react-hook-form Going to close this for now.

**Closed by devongovett** 2023-12-17 03:44 UTC
Labels: waiting, RAC
