### ISSUE TITLE
[RAC] Tree typeahead interferes with tree item inputs

### ISSUE THREAD

**Issue by hejhi** [adobe/react-spectrum#7552] opened 2024-12-23 22:31 UTC
### Provide a general summary of the issue here

Likely related to similar issues mentioned [elsewhere](https://github.com/adobe/react-spectrum/issues/6037)—if I have an input inside my `TreeItem` (say for renaming), there appears to be no way to disable typeahead from stealing the focus away from the input.

I'm also fully aware the `Tree` is still beta, but wanted to flag it.

Additionally, thanks for the excellent work and open sourcing all of this!

### 🤔 Expected Behavior?

I would expect typeahead to not steal focus from inputs inside of `TreeItem`/`TreeItemContent` (or a mechanism/guidance to temporarily disable it).

### 😯 Current Behavior

Typeahead steals focus from the input when the user begins typing, and applies it to a matched tree item as part of typeahead.

### 💁 Possible Solution

Either:
- a mechanism to support a (likely fairly common) scenario where a user needs to edit an item in a tree
- a prop to disable typeahead
- documentation explaining this as a design choice, as [this example](https://react-spectrum.adobe.com/react-spectrum/TreeView.html#with-action-groups) (albeit not for the `Tree` component itself, nor demonstrating an inline input) implies this is a valid use case

### 🔦 Context

I have essentially the same scenario as [this example](https://react-spectrum.adobe.com/react-spectrum/TreeView.html#with-action-groups), where I want to allow the user to be able to edit a tree item label in-place.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/upbeat-gagarin-637jj4

Focus the input field and type "P", observe focus is stolen and transferred to "Photos".

### Version

1.5.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by snowystinger** [comment] 2024-12-26 22:25
Thanks for the issue, closing as this is a duplicate of the issue linked in the description. Grid edit mode will handle this.

**Closed by snowystinger** 2024-12-26 22:25 UTC
