### ISSUE TITLE
Popover for Select immediately closes on Firefox Mobile simulator 

### ISSUE THREAD

**Issue by jwickens** [adobe/react-spectrum#4422] opened 2023-04-21 09:47 UTC
# 🐛 Bug Report 

Clicking to open a selector component causes it to open and then close. A long press will open it.

This may be a regression of https://github.com/adobe/react-spectrum/issues/816

## 💻 Code Sample

https://react-spectrum.adobe.com/react-aria/useSelect.html#useselect

Click "select a option" on firefox and you should be able to replicate this issue.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  3.22 and whatever is on the website.
| Browser          |  Firefox 111 using mobile simulator from dev tools
| Operating System | Windows 11

**Comment by LFDanLu** [comment] 2023-04-21 16:51
Reproduced in Firefox 112 on my Android device as well, thanks for catching this!

**Comment by LFDanLu** [comment] 2023-04-24 20:48
@jwickens https://github.com/adobe/react-spectrum/blob/1a38c6f7ed998fae8ef5321b832a4d68b7926a5e/packages/%40react-aria/menu/src/useMenuTrigger.ts#L114-L118 would suggest that the select menu should already be opened via `onPress` rather than `onPressStart` for touch device, maybe something with Firefox is breaking that detection?

**Comment by LFDanLu** [comment] 2023-04-25 16:53
Thanks for digging into this and glad you found a workaround.
> it doesn't seem like the intent of this function
You are correct, `isVirtualPointerEvent` is supposed to detect screen reader virtual clicks. The compatibility mouse clicks are definitely problematic, hopefully we can resume work on https://github.com/adobe/react-spectrum/pull/2942 to try and get this issue squared away.

**Comment by devongovett** [comment] 2024-12-20 21:57
Cannot reproduce anymore. May have been fixed by #7026.

**Closed by devongovett** 2024-12-20 21:57 UTC
Labels: bug
