### ISSUE TITLE
Checkbox flickers gray when switching from indeterminate to selected in Chrome

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#1834] opened 2021-04-22 22:38 UTC
# 🐛 Bug Report 

In Chrome only, when a checkbox switches from indeterminate emphasized to selected emphasized it flickers gray first. This can be seen in the Table select all checkbox when selecting the last row.

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | da3dc02
| Browser          | Chrome 89
| Operating System | Mac, Windows

**Comment by ktabors** [comment] 2021-05-28 05:14
It might be the grey background color of the ::before. When I check computed values of the ::before Chrome says it is white. When I look at all the css the only blue I see is from the box shadow on the ::after. There is a change my dev tools are broken right now because mousing over variables isn't showing the color.
https://user-images.githubusercontent.com/309540/119932745-3862b980-bf38-11eb-9c05-bbd38d911959.mov

**Comment by ktabors** [comment] 2021-06-10 00:04
I think this is a Chrome browser bug when using react dev tools and "Highlight updates when components render." is turned on. When I do the same in Firefox this doesn't happen. It also doesn't happen in chrome when that setting is off.

**Comment by ktabors** [comment] 2021-08-04 17:17
This appears to be caused when the user clicks on row to toggle selection instead of the checkbox to toggle selection.

**Comment by ktabors** [comment] 2021-08-05 01:38
Created a codesandbox with this reproduced with checkboxex and buttons. https://codesandbox.io/s/proud-moon-2supq?file=/src/App.tsx

To reproduce click on the the toggle apple button then the toggle orange button. The select checkbox without a label with switch from blue indeterminate to gray to selected blue checkmark.

**Comment by snowystinger** [comment] 2021-08-05 06:05
FYI, you can watch it slowed down using https://developer.chrome.com/docs/devtools/css/animations/

**Comment by paulgpeterson** [comment] 2021-12-07 00:33
I'm going to investigate this issue and see if I can pinpoint the cause.

**Comment by snowystinger** [comment] 2021-12-07 00:43
There's a potentially easier way to reproduce this btw. If you are in Chrome and running our storybook locally, you can go to this story https://reactspectrum.blob.core.windows.net/reactspectrum/21f32255590d88597e73618614e83a3a6a8cc73e/storybook-17/index.html?path=/story/tableview--dynamic-with-selection (you can see it in this link as well, it's just a recent build we've deployed)
then steps are
1) click select all
2) click on the first row "Foo 1" text, this is important, do not click the check mark for the row
3) click on the same spot again, the select all checkbox will now be selected and grey

if you click on the checkboxes to toggle an individual row, the bug will not happen.

let me know if you have trouble reproducing it as I can do it right now

**Comment by paulgpeterson** [comment] 2021-12-07 17:12
Thanks for the tips @snowystinger, that works.

**Comment by khoad** [comment] 2021-12-09 23:32
The above PR has been merged, this issue should be closed?

**Comment by LFDanLu** [comment] 2021-12-09 23:36
@khoad Thanks for the heads up!

**Closed by LFDanLu** 2021-12-09 23:36 UTC
Labels: bug, rsp:Checkbox, rsp:TableView
