### ISSUE TITLE
[Drag & Drop] Drop rect hitbox misaligned with Chrome devtools zoom

### ISSUE THREAD

**Issue by nathanforce** [adobe/react-spectrum#4365] opened 2023-04-11 13:41 UTC
I spent many hours trying to debug my drop target behavior only to discover the issue was caused by Chrome Devtools zoom being at 75%.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/6694194/231181517-696e4dd3-3d9b-4189-a99f-6d41867f9fa8.png">

The behavior probably differs based on the zoom level but my issue was basically that the drop target didn't change state to appear as a drop target unless I hover over some random part of the screen. 

I'm not sure if y'all have any action here but I posted it just in case others are searching issues for this. Feel free to close the issue right away.

**Comment by reidbarber** [comment] 2023-04-11 16:20
For others debugging, you need to open the menu and choose 'Add device type', then switch to 'Desktop'.

I'm leaning towards this being a non-issue since it isn't present when zoom levels are adjusted outside of the responsive dev tools mode. I think the issue may be related to the visual viewport changing. I would be curious to see if this issue is present when zooming on an Android device with Chrome.

**Comment by LFDanLu** [comment] 2023-04-19 18:33
Closing for now, feel free to reopen if this reproduces on other mobile devices

**Closed by LFDanLu** 2023-04-19 18:33 UTC
