### ISSUE TITLE
useAsyncList errors out on reload() when paired with ListView

### ISSUE THREAD

**Issue by tiffany-sy-lin** [adobe/react-spectrum#5171] opened 2023-09-29 15:31 UTC
### Provide a general summary of the issue here

When using `useAsyncList` with `ListView`, we get a virtualizer error when you try to do `list.reload()`.

### 🤔 Expected Behavior?

List should reload without errors

### 😯 Current Behavior

List throws `Cannot read properties of undefined (reading 'rect')`. I've tracked it down to `Virtualizer.ts` in RSP

### 🖥️ Steps to Reproduce

Recreated in a [sandbox](https://codesandbox.io/s/staging-night-zvmrw7?file=/src/App.js)

1. Load sandbox
2. Press the 'Press me' button
3. App should error out

### Version

3.29.0 (& tried on 3.30.0 as well)

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

### 🧢 Your Company/Team

DXUE Quarry

**Comment by LFDanLu** [comment] 2023-09-29 23:23
Reproduced, note that this is due to the data being instantly returned via useAsyncList's `load` function. If a [delay is added ](https://codesandbox.io/s/hopeful-hermann-588mtr?file=/src/App.js) to the useAsyncList's `load` function then it works fine. We can investigate how to perhaps debounce/delay updates to the items provided to our virtualizer components.

@tiffany-sy-lin Is Quarry running into an issue where the load call is returning too quickly?

**Comment by tiffany-sy-lin** [comment] 2023-09-29 23:37
@LFDanLu Maybe? The sandbox I provided, is a parred down version of how we're using useAsyncList in inventory. The original reporter said they experienced it with large datasets though (unsure how large is 'large'), but the story example they provided only had 10 items.

**Comment by alexis-lanoix-sixthfin** [comment] 2024-09-11 07:26
This bug seems to be fixed now (tested on version 3.36.3):
[sandbox](https://codesandbox.io/p/sandbox/stupefied-sara-y4vzh7?file=%2Fpackage.json%3A8%2C31-8%2C37)

**Comment by snowystinger** [comment] 2024-09-11 08:05
Thanks for trying that out. I verified it appears to be fixed.

**Closed by snowystinger** 2024-09-11 08:05 UTC
Labels: bug, has workaround
