### ISSUE TITLE
RAC Tooltip misbehaves with defaultOpen set

### ISSUE THREAD

**Issue by patrickkuhlmann** [adobe/react-spectrum#6658] opened 2024-07-03 11:19 UTC
Using defaultOpen on a `<Tooltip />` directly causes the Tooltip to not be closable anymore. This was introduced by this commit [a77030aebb717126b1441b45b11c3644c60c623f](https://github.com/adobe/react-spectrum/commit/a77030aebb717126b1441b45b11c3644c60c623f)

Additionally it is wrongly positioned compared to using defaultOpen on `<TooltipTrigger />` as it is intended to.

If I misunderstand this behavior or the motivation behind it please let me know.

### 🤔 Expected Behavior?

defaultOpen to only be used for the initial state and still allow the Tooltip to be closed after

### 😯 Current Behavior

Tooltip stays no matter what

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/devbox/react-aria-components-rx7t2y?file=%2Fsrc%2FApp.tsx

**Comment by snowystinger** [comment] 2024-07-08 00:50
Closing as a duplicate of https://github.com/adobe/react-spectrum/issues/6505

**Closed by snowystinger** 2024-07-08 00:50 UTC
