### ISSUE TITLE
TypeError: Document.createTreeWalker on disabled button

### ISSUE THREAD

**Issue by sylvainDNS** [adobe/react-spectrum#4149] opened 2023-03-02 18:41 UTC
# 🐛 Bug Report 

We made a DatePicker component using the pattern [available in the documentation](https://react-spectrum.adobe.com/react-aria/useDatePicker.html#example).

We use `minValue` & `maxValue` props to specify a range of dates for our user, but there is a bug when the next/previous month button goes disabled.

## 🤔 Expected Behavior

On Firefox, when a `minValue` & `maxValue` is specified, I navigate between months.   
I can select a date on these months with the DatePicker.

## 😯 Current Behavior

On Firefox, when a `minValue` & `maxValue` is specified, when I navigate to a months where the next or previous button is disabled, the Popover disappear with an console error.   
I can't select a date on these months with the DatePicker.

<details>
<summary>See the full stack trace here</summary>

```javascript
Uncaught TypeError: Document.createTreeWalker: Argument 1 is not an object.
    $9bf71ea28793e738$export$2d6ec8fc375ceafa http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UP2NOSTW.js?v=0395e22c:513
    $9bf71ea28793e738$var$focusFirstInScope http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UP2NOSTW.js?v=0395e22c:360
    current http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UP2NOSTW.js?v=0395e22c:291
    onBlur http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UP2NOSTW.js?v=0395e22c:284
    observer http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-AVLSIZUM.js?v=0395e22c:1213
    715c682d09d639cc http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-AVLSIZUM.js?v=0395e22c:1209
    onFocus http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-AVLSIZUM.js?v=0395e22c:1248
    callCallback2 http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3795
    invokeGuardedCallbackDev http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3820
    invokeGuardedCallback http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3854
    invokeGuardedCallbackAndCatchFirstError http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3857
    executeDispatch http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:6486
    processDispatchQueueItemsInOrder http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:6506
    processDispatchQueue http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:6515
    dispatchEventsForPlugins http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:6523
    dom React
    batchedEventUpdates http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3671
    dispatchEventForPluginEventSystem http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:6646
    attemptToDispatchEvent http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:5195
    dispatchEvent http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:5150
    unstable_runWithPriority http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:346
    runWithPriority$1 http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:8598
    discreteUpdates$1 http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:16253
    discreteUpdates http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3685
    dispatchDiscreteEvent http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:5125
    focus http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-AVLSIZUM.js?v=0395e22c:1314
    $7215afc6de606d6b$export$de79e2c695e052f3 http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-AVLSIZUM.js?v=0395e22c:179
    onPointerDown http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-AVLSIZUM.js?v=0395e22c:805
    callCallback2 http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3795
    invokeGuardedCallbackDev http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3820
    invokeGuardedCallback http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3854
3 chunk-UP2NOSTW.js:513:25
    $9bf71ea28793e738$export$2d6ec8fc375ceafa http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UP2NOSTW.js?v=0395e22c:513
    $9bf71ea28793e738$var$focusFirstInScope http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UP2NOSTW.js?v=0395e22c:360
    current http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UP2NOSTW.js?v=0395e22c:291
    (Async: FrameRequestCallback)
    onBlur http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UP2NOSTW.js?v=0395e22c:284
    observer http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-AVLSIZUM.js?v=0395e22c:1213
    (Async: MutationCallback)
    715c682d09d639cc http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-AVLSIZUM.js?v=0395e22c:1209
    onFocus http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-AVLSIZUM.js?v=0395e22c:1248
    callCallback2 http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3795
    invokeGuardedCallbackDev http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3820
    invokeGuardedCallback http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3854
    invokeGuardedCallbackAndCatchFirstError http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3857
    executeDispatch http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:6486
    processDispatchQueueItemsInOrder http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:6506
    processDispatchQueue http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:6515
    dispatchEventsForPlugins http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:6523
    dispatchEventForPluginEventSystem http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:6647
    batchedEventUpdates http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3671
    dispatchEventForPluginEventSystem http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:6646
    attemptToDispatchEvent http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:5195
    dispatchEvent http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:5150
    bind_applyFunctionN self-hosted:1686
    dispatchEvent self-hosted:1643
    unstable_runWithPriority http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:346
    runWithPriority$1 http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:8598
    discreteUpdates$1 http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:16253
    discreteUpdates http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3685
    dispatchDiscreteEvent http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:5125
    bind_applyFunctionN self-hosted:1686
    dispatchDiscreteEvent self-hosted:1643
    focus http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-AVLSIZUM.js?v=0395e22c:1314
    $7215afc6de606d6b$export$de79e2c695e052f3 http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-AVLSIZUM.js?v=0395e22c:179
    onPointerDown http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-AVLSIZUM.js?v=0395e22c:805
    callCallback2 http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3795
    invokeGuardedCallbackDev http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3820
    invokeGuardedCallback http://localhost:61000/@fs/app/node_modules/.vite/deps/chunk-UYDCBW63.js?v=0395e22c:3854
```
</details>

## 💁 Possible Solution

I don't have a solution but after reading other issues on this error, I think that there is a problem with the `onBlur` event when the `button` change from _focused_ to _disabled_.

I found a workaround, see below ⬇️ 

## 💻 Code Sample

You can find a code sample here which reproduce the issue : https://codesandbox.io/s/react-spectrum-typeerror-document-createtreewalker-2fr5v7?file=%2Fsrc%2FButton.tsx%3A519-546

The code is a copy of the example in the documentation. There isn't any error displayed in the console on CodeSandbox, but the Popover closes unexpectedly

I found a workaround : if we stop the propagation of the `onBlur` event, the error disappear and the DatePicker works correctly. Try to uncomment the line on CodeSandbox 👍 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          | Firefox 110

**Comment by LFDanLu** [comment] 2023-03-06 22:37
Verified in the [aria docs](https://react-spectrum.adobe.com/react-aria/useDatePicker.html#minimum-and-maximum-values) and in our Spectrum [component](https://react-spectrum.adobe.com/react-spectrum/DatePicker.html#minimum-and-maximum-values) in Firefox, thanks for catching this.

**Comment by ktabors** [comment] 2023-06-15 05:29
Closing because this is a duplicate of #3441

**Closed by ktabors** 2023-06-15 05:29 UTC
Labels: bug
