### ISSUE TITLE
useCalendarGrid ignores state locale

### ISSUE THREAD

**Issue by tekno0ryder** [adobe/react-spectrum#5273] opened 2023-10-19 09:00 UTC
### Provide a general summary of the issue here

Trying to set the locale to my country's locale for in internal app (ignoring browser locale) for consistency by passing it to `useCalendarState` but it results an a wrong calendar.

### 🤔 Expected Behavior?

1- First day of week should be Sunday as per `ar-SA`
2- 1st Oct should be on Sunday.

### 😯 Current Behavior

1- First day of week is showing Monday.
2- 1st Oct is showing on Tuesday.

### 💁 Possible Solution

`useCalendarGrid` that returns `weekDays` should respect my state's locale to show correct results

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/quiet-cherry-w2m6kc

### Version

3.29.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows 11

**Comment by matheusps** [comment] 2023-11-30 17:14
Same issue here. As a workaround, wrapped my application with I18nProvider. Hope it helps

**Comment by snowystinger** [comment] 2023-12-01 20:15
Thanks for the issue, this is working as intended.

Locale is not a prop that can be sent to useCalendarState, you can see all props here https://react-spectrum.adobe.com/react-stately/useCalendarState.html#interface

Using the I18nProvider is the correct way to handle this, you should have one at the root of your application if you need to ignore the browser setting. See https://react-spectrum.adobe.com/react-aria/internationalization.html#example

You can also specify this override for JUST the calendar by wrapping an individual calendar with the provider as well. In case you need to display multiple different calendars or need a calendar that doesn't match the rest of your app's locale.

Let us know if you have any further questions. I'm going to close this for now, but if there's a bug or further issue, we can reopen or create a new one.

**Closed by snowystinger** 2023-12-01 20:15 UTC
