### ISSUE TITLE
`containerPadding` is not applied when flipping popover

### ISSUE THREAD

**Issue by deebov** [adobe/react-spectrum#5224] opened 2023-10-09 14:18 UTC
### Provide a general summary of the issue here

As you can see in the video below, the space between the popover and the edge of the window is less than the default 12px. This only happens when the popover is flipped.

https://share.cleanshot.com/GlCmpS9m

<img width="671" alt="image" src="https://github.com/adobe/react-spectrum/assets/28673719/a7fafea8-fd4b-48e7-b8be-1089efc53006">

### 🤔 Expected Behavior?

The space between the popover and the edge of the window is always consisted, no matter if the popover is flipped or not.

### 😯 Current Behavior

The space between the popover and the edge of the window is less than it should be when it's flipped.

### 🖥️ Steps to Reproduce

Just see the video in the description.

### Version

1.0.0-beta.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by reidbarber** [comment] 2023-10-18 22:33
Looks like this also happens in React Spectrum overlays.

**Comment by snowystinger** [comment] 2024-07-30 11:13
It looks like this was resolved at some point, I can't reproduce in the latest docs. Neither in RAC nor RSP. I'm going to close it now. We can reopen if it's still happening.

**Closed by snowystinger** 2024-07-30 11:13 UTC
Labels: bug
