### ISSUE TITLE
Virtualized list does not scroll selected item into view on pointer click

### ISSUE THREAD

**Issue by omacranger** [adobe/react-spectrum#3910] opened 2023-01-12 14:24 UTC
# 🐛 Bug Report 

Hello! Virtualized listboxes do not properly restore the scroll position / scroll the selected item into view. It looks like it has something to do with the view caching / recognition inside a virtualized listbox item. We ran into the same issue with an in house virtualized 'picker,' but the same issue is evident on the [React Spectrum Asynchronous Picker](https://react-spectrum.adobe.com/react-spectrum/Picker.html#asynchronous-loading) when viewing a long list. This _appears_ to only happen when using a pointer, probably due to the [modality check in the useEffect](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/virtualizer/src/Virtualizer.tsx#L138). Using a keyboard to interact with the same element always scrolls it into view.

## 🤔 Expected Behavior

Clicking on a select to open it should always scroll the selected item into view. 

## 😯 Current Behavior

Every other open of the `useSelectableCollection` starts at the beginning of the list. You can replicate this by again using the [React Spectrum Asynchronous Picker](https://react-spectrum.adobe.com/react-spectrum/Picker.html#asynchronous-loading) and clicking on the picker multiple times. It will alternate between scrolling it into view, and starting at the beginning of the list.

## 💁 Possible Solution

The modality check for pointers in the above example ([modality check in the useEffect](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/virtualizer/src/Virtualizer.tsx#L138)) seems to only scroll the selected item into view if modality isn't a pointer, which conflicts with opening it repeatedly with a pointer. It appears to be due to views being cached and invalidated after the first open as the [other useEffect](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/virtualizer/src/Virtualizer.tsx#L176) cannot find the view (since it has been destroyed), doesn't focus automatically due to the modality check above, and focuses the container instead with `focusWithoutScrolling`.  

Something like below can be used as a workaround inside the Picker, Select, etc, to forcefully reset the visible rect and have the virtualizer re-handle layout: 

```tsx
useEffect(() => {
    if (!state.isOpen) {
      if (layout.virtualizer) {
        layout.virtualizer.visibleRect = new Rect();
      }
    }
  }, [state.isOpen, layout.virtualizer]);
```

## 🔦 Context

When opening a select, users like to see the currently selected item in view so adjacent ones can be selected and the appearance of the currently selected item is still visible and doesn't appear like it's been unselected.

## 💻 Code Sample

Can be seen on the  [React Spectrum Asynchronous Picker](https://react-spectrum.adobe.com/react-spectrum/Picker.html#asynchronous-loading).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | latest
| Browser          | Chrome 108
| Operating System | MacOS

## 🧢 Your Company/Team

Other

**Comment by LFDanLu** [comment] 2023-01-12 19:51
Thanks for bringing this up, this looks to be a regression. There seems to be some kind of race condition where  `!isFocusWithin.current` [here](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/virtualizer/src/Virtualizer.tsx#L138) is returning false occasionally, seemingly due to the order in which `useSelectableItem` calls `.focus` on the actual list item (causing this to set `isFocusWithin` as [true](https://github.com/adobe/react-spectrum/blob/e42010c5e1cdae4ae62c456e52e04ff66cf1dac2/packages/%40react-aria/virtualizer/src/Virtualizer.tsx#L166)) versus this [blur](https://github.com/adobe/react-spectrum/blob/e42010c5e1cdae4ae62c456e52e04ff66cf1dac2/packages/%40react-aria/virtualizer/src/Virtualizer.tsx#L169-L171) setting `isFocusWithin` as false because the focusedView doesn't exist yet as you noted.

Will need to find some time to deep dive for the cause of this regression, will keep your proposed solution in mind. Ideally Virtualizer would notify when it has finished constructing its visible view perhaps, or maybe we can delay focusing the list item until the scrollIntoView part of Virtualizer has executed

**Comment by LFDanLu** [comment] 2023-01-21 01:52
@ozguruysal looks like applying a max height onto the ListBox `ul` fixes the issue: https://codesandbox.io/s/pensive-architecture-3d9pvi. Still digging to see why exactly, mind filing a separate issue since [this](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/selection/src/useSelectableCollection.ts#L362) code is separate from the virtualizer code when handling scrolling the focused key into view?

**Comment by ozguruysal** [comment] 2023-01-21 09:11
Thank you @LFDanLu, opened a separate issue.

**Comment by LFDanLu** [comment] 2024-08-19 16:34
Looks like this was fixed by https://github.com/adobe/react-spectrum/pull/6527 as well

**Closed by LFDanLu** 2024-08-19 16:34 UTC
Labels: bug, needs investigation
