### ISSUE TITLE
TableView cell overflow props behaves improper.

### ISSUE THREAD

**Issue by shivamgoyal-43** [adobe/react-spectrum#5591] opened 2023-12-18 05:41 UTC
### Provide a general summary of the issue here

The link in the cell is adding ellipsis( ... ) multiple times when we are using overflow: 'wrap' props.

### 🤔 Expected Behavior?

It should add ellipsis at the end or should display the entire link text without ellipsis.

### 😯 Current Behavior

The link in the cell is adding ellipsis( ... ) multiple times when we are using overflow: 'wrap' props.

### Version

3.29.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Mac

### 🧢 Your Company/Team

ACC

**Comment by reidbarber** [comment] 2023-12-18 17:00
Updated the post to remove internal Adobe info. Here is a codesandbox demonstrating the described behavior: https://codesandbox.io/p/sandbox/without-word-break-c4cnvd

I think this is the expected behavior for long strings like this. You can solve this by surrounding your long string with a `span` with  `overflow-wrap: break-word`: https://codesandbox.io/p/sandbox/with-word-break-h9l7d8?file=%2Fsrc%2FApp.js%3A21%2C22

**Comment by snowystinger** [comment] 2023-12-18 23:44
Closing, this is working as intended. Thanks for the links/examples @reidbarber

**Closed by snowystinger** 2023-12-18 23:44 UTC
