### ISSUE TITLE
useOverlay always stops propagation which breaks other overlay triggers

### ISSUE THREAD

**Issue by AndyOGo** [adobe/react-spectrum#5167] opened 2023-09-29 08:54 UTC
### Provide a general summary of the issue here

[`useOverlay`](https://react-spectrum.adobe.com/react-aria/useOverlay.html) always calls `stopPropagation`, which prevents other over triggers from opening.

- https://github.com/adobe/react-spectrum/blob/1b17b5574982a8a38932385f377e1695f2fb959a/packages/%40react-aria/overlays/src/useOverlay.ts#L97
- https://github.com/adobe/react-spectrum/blob/1b17b5574982a8a38932385f377e1695f2fb959a/packages/%40react-aria/overlays/src/useOverlay.ts#L106

### 🤔 Expected Behavior?

If the overlay is the last item, it should not stop the propagation.

Or the behavior of propagation should be controllable.

### 😯 Current Behavior

Event propagation is always stopped and breaks other UI's using [`userOverlayTrigger`](https://react-spectrum.adobe.com/react-aria/useOverlayTrigger.html).

Actually it prevents any focusable element from being focused.

### 💁 Possible Solution

- don't stop propagation if it's the last overlay on the stack or if's a sibling overlay trigger
- Make stop propagation configurable

### 🔦 Context

I'm using a table with a list of context menus build with overlays.

I can't open a context menu at the same time I close another.

### 🖥️ Steps to Reproduce

None yet

### Version

react-aria@3.27.0

### What browsers are you seeing the problem on?

Microsoft Edge

### If other, please specify.

But really, all of them.

### What operating system are you using?

Windows

**Comment by LFDanLu** [comment] 2023-09-29 23:16
I believe this is a duplicate of https://github.com/adobe/react-spectrum/issues/5031, the [linked issue](https://github.com/adobe/react-spectrum/issues/2061) for more information on the reason why we stop propagation in useOverlay. Closing as a dupe, feel free to reopen if otherwise.

**Closed by LFDanLu** 2023-09-29 23:16 UTC
