### ISSUE TITLE
Allow forcibly padding out the entered year in the DatePicker with zeros

### ISSUE THREAD

**Issue by illright** [adobe/react-spectrum#5995] opened 2024-03-04 10:09 UTC
### Provide a general summary of the feature here

I would like to prevent the situation in which someone would look at the field with a placeholder `dd-mm-yyyy` and enter a date `01-12-24`, meaning December 1st of 2024, but actually entering December 1st of 24. I'd prefer it happened by reformatting the date after input to read `01-12-0024`. 

### 🤔 Expected Behavior?

If you enter `dd-mm-yy`, it should format it to `dd-mm-00yy`

### 😯 Current Behavior

It leaves the formatting as it is, leading some people to believe that the `20` prefix is implied

### 💁 Possible Solution

There is a prop like that for days and months (`shouldForceLeadingZeros`), but it doesn't affect the year field. We could add another prop that would add the amount of zeros of the current year (if this software will be around by year 10000)

### 🔦 Context

I would like to prevent the situation in which someone would look at the field with a placeholder `dd-mm-yyyy` and enter a date `01-12-24`, meaning December 1st of 2024, but actually entering December 1st of 24.

Enter this date here: https://react-spectrum.adobe.com/react-aria-starter/index.html?path=/story/datefield--example&args=label:Event+date;shouldForceLeadingZeros:!true

**Comment by adriantrunzo** [comment] 2024-03-05 02:13
I've also run into this issue. I think it's worth pointing out that the HTML date input left pads the input as the expected behavior above describes, at least in Firefox: 

https://github.com/adobe/react-spectrum/assets/1218900/09698182-efd1-4a4d-8617-78339a5a51ca

What's the reason for `shouldForceLeadingZeroes` not affecting the year value?

**Comment by devongovett** [comment] 2024-03-16 03:05
internally, we use [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat) to format dates, which ensures it is done in a localized manner. As far as I can tell, this does not support a zero-padded year format, it only has `numeric` and `2-digit`. I suspect that zero padding isn't so simple when you consider other numbering systems and regions around the world where it might be unexpected.

**Comment by illright** [comment] 2024-03-16 09:53
I suppose that a workaround could be to set the minimum date to `01-01-100`, that would disallow users to enter two-digit years and likely cause them to figure out what they need to do

**Comment by snowystinger** [comment] 2024-03-18 00:51
Closing, to reopen we'd need either support in DateTimeFormat or proof that this is acceptable across all locales/numbering systems/regions
Thanks for the discussion!

**Closed by snowystinger** 2024-03-18 00:51 UTC
