### ISSUE TITLE
RAC Link - wrong href for external links when using RouterProvider with React Router

### ISSUE THREAD

**Issue by universse** [adobe/react-spectrum#6803] opened 2024-07-31 07:06 UTC
### Provide a general summary of the issue here

When using RAC RouterProvider with `useHref` from React Router, the final href is incorrect. Also filed an issue under React Router  https://github.com/remix-run/react-router/issues/11856.

### 🤔 Expected Behavior?

External link is appended to the site origin.

### 😯 Current Behavior

External link should be kept as is.

### 🖥️ Steps to Reproduce

Reproduction https://stackblitz.com/edit/vitejs-vite-jqjqfr?file=src%2FApp.tsx

### Version

NA

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

Windows

**Comment by snowystinger** [comment] 2024-07-31 08:52
I think this might be a duplicate of https://github.com/adobe/react-spectrum/issues/6397

**Closed** 2024-08-01 06:35 UTC
