### ISSUE TITLE
onPress/onButton triggers click event on other element if layout changes based on onPress handler on touch devices

### ISSUE THREAD

**Issue by jeyj0** [adobe/react-spectrum#5802] opened 2024-02-05 16:18 UTC
### Provide a general summary of the issue here

When using the `usePress` or `useButton` hooks, the result of the event handler may change the layout of the page (for example expanding/collapsing an area). This action might move another pressable element to the location at which the button was previously. On touch devices, this causes the element that moved to the location to have its own click/press handler triggered.

### 🤔 Expected Behavior?

When tapping an element with an onPress handler that changes the layout, no other element's onClick/onPress handler is triggered due to the layout change.

### 😯 Current Behavior

When tapping an element with an onPress handler on a mobile device, if that handler changes the page's layout such that another tappable element moves under the touch location, that element's onClick handler is triggered.

### 🔦 Context

I implemented a hamburger menu that causes the menu to "fly in" from the right. The animation of the menu caused a link to move over the area of the button that opens the menu. On mobile devices, this sometimes caused the link to immediately be clicked, causing a navigation. (Workaround used: making the element clickable only after the animation is completed)

I implemented a text box with truncated text that should expand when clicking a "Read more" button, and be collapsible again. When collapsing, a link moves to the area where the collapse button was before the handler, causing a click on the link and therefore a navigation.

### 🖥️ Steps to Reproduce

[A codesandbox with a minimal reproduction](https://codesandbox.io/p/sandbox/react-aria-button-bug-tx2vkj?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls93xqjh00062066fbx1z4d7%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls93xqjh00022066ykp0b8li%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls93xqjh000320666p5we7ev%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls93xqjh000520667xfbk42r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls93xqjh00022066ykp0b8li%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls93xqjh00012066ispj5z1s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522cls93xqjh00022066ykp0b8li%2522%252C%2522activeTabId%2522%253A%2522cls93xqjh00012066ispj5z1s%2522%257D%252C%2522cls93xqjh000520667xfbk42r%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls93xqjh00042066eztklo2u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls93xqjh000520667xfbk42r%2522%252C%2522activeTabId%2522%253A%2522cls93xqjh00042066eztklo2u%2522%257D%252C%2522cls93xqjh000320666p5we7ev%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls93xqjh000320666p5we7ev%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

You can reproduce the bug using both Firefox's and Chrome's devtools by simulating a touch device, or by using an actual touch device.

- [ ] test on safari (no devices available)

### Version

react-aria 3.31.1

### What browsers are you seeing the problem on?

Other

### If other, please specify.

Mobile Firefox, Mobile Chrome, Firefox & Chrome with Touch simulation

### What operating system are you using?

Linux / Android

**Comment by snowystinger** [comment] 2024-02-05 20:30
I believe this is a dupe of https://github.com/adobe/react-spectrum/issues/1513

**Closed** 2024-09-12 16:23 UTC
