### ISSUE TITLE
nextjs + styled-components not working

### ISSUE THREAD

**Issue by hanselabreu** [adobe/react-spectrum#1200] opened 2020-10-28 06:30 UTC
# 🐛 Bug Report 

Using the `@react-aria/overlays` along with `nextjs` and `styled-components` is generating an error on the `_document.tsx` sample file provided by `nextjs`.

## 🤔 Expected Behavior

Styles should be passed to components.

## 😯 Current Behavior

When using the `OverlayContainer` component I get the following error coming from the `_document.tsx` file: 

```
Server Error
ReferenceError: document is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
pages/_document.tsx (11:8) @ Object.ctx.renderPage

   9 | try {
  10 |   ctx.renderPage = () =>
> 11 |     originalRenderPage({
     |    ^
  12 |       enhanceApp: (App: any) => (props: any) =>
  13 |         sheet.collectStyles(<App {...props} />),
  14 |     });
```

I have my app wrapped in both `SSRProvider` and `OverlayProvider` like so: 

```
import React from "react";
import { createGlobalStyle, ThemeProvider } from "styled-components";
import { SSRProvider, OverlayProvider } from "react-aria";

import { theme } from "theme";

const GlobalStyle = createGlobalStyle`
  body {
    margin: 0;
    padding: 0;
  }
`;

export const CoreProvider: React.FC = ({ children }) => {
  return (
    <>
      <GlobalStyle />
      <ThemeProvider {...{ theme }}>
        <SSRProvider>
          <OverlayProvider>{children}</OverlayProvider>
        </SSRProvider>
      </ThemeProvider>
    </>
  );
};
```

The problem is **only** when importing and using the `OverlayContainer` component. If I comment it out, error is removed.

## 💻 Code Sample

See above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | N/A
| react-aria | 3.0.0
| Browser          | Chrome 86.0.4240.111
| Operating System | MacOS

**Comment by hanselabreu** [comment] 2020-10-28 06:51
Figured it out. We need to check that we're on the client before creating the portal. `document` will be undefined in the server.

```
export function OverlayContainer(props: ModalProviderProps): React.ReactPortal | null {
  let [mounted, setMounted] = useState(false)
  let contents = <OverlayProvider {...props} />;

  useEffect(() => {
    setMounted(true)
  }, [])

  return mounted ?  ReactDOM.createPortal(contents, document.body) : null
}
```

Tried opening a PR but didn't have permissions. 🤷‍♂️

**Comment by dannify** [comment] 2020-10-29 00:15
Dupe of https://github.com/adobe/react-spectrum/issues/1055

**Comment by alexanderbluhm** [comment] 2020-11-15 22:34
Still a problem for me.

**Comment by devongovett** [comment] 2020-12-02 17:33
Closing as a dup of #1055.

**Closed by devongovett** 2020-12-02 17:33 UTC
