### ISSUE TITLE
RAC `Input` `defaultValue` causes error

### ISSUE THREAD

**Issue by imericxu** [adobe/react-spectrum#6689] opened 2024-07-11 23:48 UTC
### Provide a general summary of the issue here

Setting `defaultValue` for `Input` doesn't do what it's supposed to and causes an error.

### 🤔 Expected Behavior?

Input should remain uncontrolled and initialized with the given value.

### 😯 Current Behavior

`value` is set to empty and the `defaultValue` is ignored. Both attributes existing at the same time also causes an error in the console, since controlled inputs can't have a `defaultValue`.

### 🖥️ Steps to Reproduce

Here's an example `TextField` `input` that would cause the described issue.
```tsx
<TextField>
  <Label>Rows</Label>
    <Input
      name="rows"
      type="number"
      step={1}
      min={MazeController.DIMS_RANGE.minSize}
      max={MazeController.DIMS_RANGE.maxSize}
      placeholder={MazeController.DEFAULTS.dimensions.rows.toString()}
      autoComplete="off"
      defaultValue={MazeController.DEFAULTS.dimensions.rows}
      className="remove-input-arrows h-full w-full bg-transparent px-3"
    />
    {/* Error message */}
    <FieldError />
  </div>
</TextField>
```

### Version

1.2.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by snowystinger** [comment] 2024-07-12 03:10
You're meant to put the value on the `TextField`, not the Input. Please see https://react-spectrum.adobe.com/react-aria/TextField.html#controlled-value
I'm going to close this as working as intended. Let us know if you run into other issues.

**Closed by snowystinger** 2024-07-12 03:10 UTC

**Comment by imericxu** [comment] 2024-07-12 04:36
Ah 🤦‍♂️
