### ISSUE TITLE
`onSubmit` event for form is being triggered when an option in bottomsheet is selected.

### ISSUE THREAD

**Issue by 9903SV** [adobe/react-spectrum#2990] opened 2022-03-29 12:05 UTC
# 🐛 Bug Report 

In Combobox/Picker Mobile Overlays, when clicked on an option in the combobox overlay, the `onSubmit` event of the element in the bottom layer is being triggered.

This happens only in touch devices.

@devongovett @snowystinger @LFDanLu @dannify 

## 🤔 Expected Behavior

When clicked on an option in the ModalDialog, the `onSubmit` event of the element in the bottom layer should not be triggered.

## 😯 Current Behavior

When clicked on an option in the ModalDialog, the `onSubmit` event of the element in the bottom layer is being triggered.

## 🔦 Context

We have a form with multiple picker fields. When an option is selected in from a picker and if the submit button happens to be right below the selected option, then the button gets clicked and the form gets submitted (`onPress` is not being called, only form submit event is triggered).

We have referred to the existing issues https://github.com/adobe/react-spectrum/issues/2869 etc and tried all the possible solutions.

We have also created a patch as mentioned in https://github.com/adobe/react-spectrum/pull/2942, but the issue still persists. 

## 💻 Code Sample

https://codesandbox.io/s/jovial-night-k55cu3?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.9.0
| Browser          | Chrome 94.0.4606.81
| Operating System | Ubuntu 20.04.3 LTS

## 🕷 Tracking Issue (optional)

https://fm2n21.csb.app/?

**Note:**

- This issue in the above codesandbox link can be reproduced only when opened in a new tab. The issue disappears when the page is refreshed.

https://user-images.githubusercontent.com/63204729/160606778-88a73403-5303-4f89-891d-2cb2c9429162.mp4

**Comment by LFDanLu** [comment] 2022-03-29 17:17
I'm surprised that https://github.com/adobe/react-spectrum/pull/2942 doesn't fix this issue, I made a similar story in that branch to test it locally + tried https://reactspectrum.blob.core.windows.net/reactspectrum/f65d29f4d2fa5088026367cf33241f086f13d896/storybook/iframe.html?id=menutrigger--menu-overlapping-buttons&providerSwitcher-locale=&providerSwitcher-theme=&providerSwitcher-scale=&providerSwitcher-toastPosition=bottom&viewMode=story and wasn't able to reproduce it on my phone or in the chrome emulator. 

You mentioned you tried to create a patch to bring in those changes on your end, mind expanding on how you did this (patch-package)?

**Comment by 9903SV** [comment] 2022-03-30 04:13
We have used resolutions in `package.json` file to get a common version for `react-aria/interactions`. We have made the changes as mentioned in #2942 and generated a patch file using patch-package.

The above codesandbox example doesn't contain the patch file, but is a similar representation of the issue we are facing.

I guess the story which you have mentioned in the above example doesn't contain a form.

The issue occurs only when the button is wrapped in a form and the form `onSubmit` event gets called. (button events like onPress, onPressStart, onPressChange etc are not get called).

And also, the issue occurs only when opened in a new tab and disappears when the page/tab is refreshed as mentioned in the above discussion.

**Comment by LFDanLu** [comment] 2022-03-30 17:52
Are you able to reproduce here: https://reactspectrum.blob.core.windows.net/reactspectrum/cb70ed2c3d1dc3ac31f77cf52899e97741340b8b/storybook/index.html?path=/story/usemodal-issues--click-through-form-submit? I am unable to, that PR contains the fix from #2942. 
The above story is from: https://github.com/adobe/react-spectrum/pull/2996/files

**Comment by 9903SV** [comment] 2022-03-31 07:06
In the story that you have mentioned above, the form submit event isn't getting triggered when clicked directly on the button. (not through the modal).

The issue has been reproduced in the video mentioned below. The form submit event is being triggered when a normal HTML button is used (`Click Me Normal Button`) . 

https://user-images.githubusercontent.com/63204729/160996952-395496b2-eacc-4064-baf5-04a520b0bff6.mp4

**Comment by LFDanLu** [comment] 2022-03-31 16:45
Good catch, you are correct. Looks like the additional logic added to usePress in #2942 broke buttons and other pressable elements (checkboxes), but removing that logic breaks one of the the test cases... Will have to dig some more.

**Comment by devongovett** [comment] 2024-12-20 20:15
I cannot reproduce this anymore in the latest version. It was probably fixed by #7026.

**Closed by devongovett** 2024-12-20 20:15 UTC
Labels: bug
