### ISSUE TITLE
Button in ComboBox not displaying Popup when value in ListBoxItem is to long

### ISSUE THREAD

**Issue by tordsta** [adobe/react-spectrum#5653] opened 2024-01-04 11:54 UTC
### Provide a general summary of the issue here

When you have a ListBoxItem with a value longer than the Input/ComboBox component, the Button component inside ComboBox stops displaying the Popover when clicked with mouse.
For example: <ListBoxItem>Dooooooooooooooooooooooooooooooooog</ListBoxItem>

### 🤔 Expected Behavior?

When a long ListBoxItem is selected, the Popover should open when the "<Button>▼</Button>" button is clicked. 

### 😯 Current Behavior

When a long ListBoxItem is selected, the Popover does not open when the "<Button>▼</Button>" button is clicked. 

### 💁 Possible Solution

I dont know what the underlying issue is.

### 🔦 Context

I just want to be able to have longer values in ListBoxItem.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/elated-rumple-c5q8r5?file=/src/App.js:30,17

### Version

1.0.0

### What browsers are you seeing the problem on?

Other

### If other, please specify.

Arc

### What operating system are you using?

macOS Sonoma 14.1

**Comment by reidbarber** [comment] 2024-01-04 15:47
I'm seeing this in Chrome, but not Safari, so it seems like a browser feature where it focuses the text input if you click over where the overflowing text is. I'm not sure that this is a RAC bug, but more something that needs to be solved with styling.

**Comment by ben-hapip** [comment] 2024-01-29 04:39
@reidbarber @tordsta just going to chime in and say that onSelectionChange is being called when the text overflows. Still think some CSS should solve it?

**Comment by reidbarber** [comment] 2024-01-29 15:39
I'm not seeing onSelectionChange get called when the button is clicked over the overflowed text:

https://github.com/adobe/react-spectrum/assets/8961049/e1e25b4d-5a2f-4a07-aa1d-18bbbc0a0ecb

**Comment by max-two** [comment] 2024-02-02 02:05
@LFDanLu You mentioned in [another combobox issue](https://github.com/adobe/react-spectrum/issues/5790#issuecomment-1922621835) this [PR](https://github.com/adobe/react-spectrum/pull/5453/files) about closing comboboxes on scroll.

I don't know this code well enough to say one way or the other, but it sounds potentially related to this where the input being scrolled seems to close the dropdown menu immediately.

**Comment by max-two** [comment] 2024-02-02 02:10
Decided to check the down arrow behaviour because of the other thread I linked about and it is also wonky.  If you type out a bunch of characters long enough to get input box scrolling and then hit down arrow sometimes it will open / close immediately or sometimes it will stay open.  But even if it stay open, it will close and reset input as soon as you try to type another character.


https://github.com/adobe/react-spectrum/assets/21112335/d55327b2-2af6-4eff-add5-954a991a3df6

**Comment by sookmax** [comment] 2024-02-02 14:16
> @LFDanLu You mentioned in [another combobox issue](https://github.com/adobe/react-spectrum/issues/5790#issuecomment-1922621835) this [PR](https://github.com/adobe/react-spectrum/pull/5453/files) about closing comboboxes on scroll.
> 
> I don't know this code well enough to say one way or the other, but it sounds potentially related to this where the input being scrolled seems to close the dropdown menu immediately.

It indeed seems to have something to do with a scroll listener.

In particular, I've noticed the following `onScroll()` is being called when I click the trigger button while a long item is selected, closing the popover that was just open by the button action:
https://github.com/adobe/react-spectrum/blob/bd477d20344f491144dc34b9bd114070c2e9b10b/packages/%40react-aria/overlays/src/useCloseOnScroll.ts#L37-L49

Since in our case, `onClose()` is passed eventually to `useCloseOnScroll()` by `usePopover()` only when popover is non-modal:
https://github.com/adobe/react-spectrum/blob/bd477d20344f491144dc34b9bd114070c2e9b10b/packages/%40react-aria/overlays/src/usePopover.ts#L101

If I force `ComboBox` to pass the `PopoverConext` with `isNonModal: false` in my local dev environment, I see the popover behave correctly when the trigger button is pressed:
```diff
<Provider
  values={[
    [ComboBoxStateContext, state],
    [LabelContext, {...labelProps, ref: labelRef}],
    [ButtonContext, {...buttonProps, ref: buttonRef, isPressed: state.isOpen}],
    [InputContext, {...inputProps, ref: inputRef}],
    [OverlayTriggerStateContext, state],
    [PopoverContext, {
      ref: popoverRef,
      triggerRef: inputRef,
      placement: 'bottom start',
--      isNonModal: true,
++     isNonModal: false,
      trigger: 'ComboBox',
      style: {'--trigger-width': menuWidth} as React.CSSProperties
    }],
    [ListBoxContext, {...listBoxProps, ref: listBoxRef}],
    [ListStateContext, state],
    [TextContext, {
      slots: {
        description: descriptionProps,
        errorMessage: errorMessageProps
      }
    }],
    [GroupContext, {isInvalid: validation.isInvalid, isDisabled: props.isDisabled || false}],
    [FieldErrorContext, validation]
  ]}>
```

### isNonModal: true
https://github.com/adobe/react-spectrum/assets/71210554/d99b07b9-264d-4f3e-ad52-26e3f856cfa2

### isNonModal: false
https://github.com/adobe/react-spectrum/assets/71210554/2f444376-dda4-4fcd-9c08-699fda8dc757

Now don't get me wrong though, I'm not suggesting `isNonModal: false` as a possible fix for this issue 😅. (just wanted to show you the difference in popover behavior)

**Comment by staticshock** [comment] 2024-03-22 04:43
Another observation:

- If the caret is at the beginning of the long input, ArrowDown fails to open the Popover.
- If the caret is at the end of the long input, clicking the button fails to open the Popover.

Might there be some variation of @sookmax's `isNonModal`  observation that could be used as a workaround while this issue is open?

**Comment by sookmax** [comment] 2024-03-22 12:27
Hey guys, is this issue somehow magically fixed..?

I've notice the above example at https://codesandbox.io/p/sandbox/elated-rumple-c5q8r5?file=/src/App.js:30,17 working correctly now?

And I'm no longer able to reproduce it locally either.. I'm not sure what was the case before, but now every time I open the popover via the trigger button, the following `onResize()` that is registered as `visualViewport?.addEventListener('resize', onResize);` runs:

https://github.com/adobe/react-spectrum/blob/f6a664ba900c3e6307a0f9461241aa3b2397efeb/packages/%40react-aria/overlays/src/useOverlayPosition.ts#L195-L204

It sets `isResizing.current` to `true` until the timeout runs after 500ms, which has an effect on whether `onClose()` (provided by `usePopover()`) is called:

https://github.com/adobe/react-spectrum/blob/f6a664ba900c3e6307a0f9461241aa3b2397efeb/packages/%40react-aria/overlays/src/useOverlayPosition.ts#L222-L234

What I've noticed is that by the time `useCloseOnScroll()` calls `onCloseHandler()`, now `isResizing.current` is `true`, not invoking `onClose()` and hence not closing the popover as a result:

https://github.com/adobe/react-spectrum/blob/f6a664ba900c3e6307a0f9461241aa3b2397efeb/packages/%40react-aria/overlays/src/useCloseOnScroll.ts#L37-L51

Has there been a change in [VisualViewport API](https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport) that might have altered when `'resize'` event is called? Or was it always like this and the root cause of this lies somewhere else?

**Comment by staticshock** [comment] 2024-03-22 14:54
I'm still reproducing the original problem via your codesandbox link.

**Comment by LFDanLu** [comment] 2024-03-22 18:35
I'm unable to reproduce as well any more. Not quite sure what changed
MacOS 14.1
Chrome: 122.0.6261.129 
Firefox:  123.0.1
Safari:  17.1 

Windows 11
Chrome: 123.0.6312.59
Firefox: 124.0.1
Edge: 122.0.2365.92

@staticshock  As for a workaround, you could revert the changes from https://github.com/adobe/react-spectrum/pull/5453/files perhaps if absolutely need be, the combobox had existed for quite some time without closing its popover on scrolling and I think reverting that temporarily in a local patch package for your app/project isn't the worst. Alternatively, I've been meaning to look into a workaround of sorts where we either ignore scroll events that don't affect the trigger's actual position in useCloseOnScroll or to just special case `isNonModal=true` cases where we further delay the close on scroll listening

**Comment by staticshock** [comment] 2024-03-22 21:17
Thanks, @LFDanLu. And thanks for the diagnosis, @sookmax!

For the record, adding `isNonModal={false}` to the Popover fixes the issue for me:

```jsx
<ComboBox>
  <Group>
    <Input />
    <Button>Open</Button>
  </Group>
  <Popover isNonModal={false}>
    <ListBox>
      <ListBoxItem>
        Something long enough that it overflows the box
      </ListBoxItem>
    </ListBox>
  </Popover>
</ComboBox>
```

With `isNonModal={true}` the issue becomes reproducible. Any chance this is a race condition, where the difference in performance between our machines could be a factor?

**Comment by LFDanLu** [comment] 2024-03-22 22:10
Adding `isNonModal={false}` is non-desirable here because it because it has accessibility implications due to 
https://github.com/adobe/react-spectrum/blob/f6a664ba900c3e6307a0f9461241aa3b2397efeb/packages/%40react-aria/overlays/src/usePopover.ts#L108-L112 which will hide the combobox's input from screen readers when the modal is open. For normal modals, hiding all elements other than the modal from screenreaders is nice since it provides a focused context for screen reader users. However, for a combobox, the input controls what items appear in the popover while it is open so the screen reader needs to be able see/interact with the input element still. 

I don't quite recall why `isNonModal` is also tied to page scrollability and why we don't simply freeze the ComboBox page scrolling like other popovers (which is probably why the issue is resolved when setting `isNonModal={false}`), will have to dig up the discourse on those changes since that goes quite a ways back.

> Any chance this is a race condition, where the difference in performance between our machines could be a factor?

Given the 500ms timeout that @sookmax has unearthed, its entirely possible. I'm on a 2019 MacBook so not super new, what machine are you seeing this issue with?

**Comment by staticshock** [comment] 2024-03-23 03:55
2021 MacBook Pro w/M1 Pro chip

**Comment by sookmax** [comment] 2024-03-23 08:54
@staticshock Can you also share us the version of the browser that you're using?

**Comment by staticshock** [comment] 2024-03-23 17:47
Chrome 123.0.6312.59

**Comment by snowystinger** [comment] 2024-03-24 02:06
I'm unable to reproduce with Chrome 123.0.6312.59 on MacOS 14.4 and 2021 M1 Max

**Comment by staticshock** [comment] 2024-03-24 03:15
I'm using a regular (external) trackpad. I'm kind of assuming that my inputs are registering as regular mouse inputs.

**Comment by snowystinger** [comment] 2024-03-24 04:29
Maybe, just trying to rule out anything associated with cross browser and cross input normalization we do.
Any sort of a lead or difference so we can reproduce as well because I do believe you're seeing the issue.

**Comment by sookmax** [comment] 2024-03-25 15:17
@staticshock 

When `'Tap to click'` is enabled in Trackpad options, `state.pointerType` in `usePress()` would become `'virtual'` as opposed to `null`, which is the case for a physical trackpad press and a mouse click.

Not that I'm saying it's related to you observing the issue, but just wanted to mention it just in case. (I use `'Tap to click'` as well albeit mine is the built-in trackpad, and I'm not able to reproduce the bug anymore with it.)

**Comment by staticshock** [comment] 2024-03-25 16:07
Good thought. I just disabled tap to click, and that did not make a difference. I'm still consistently reproducing the bug via [the original sandbox](https://codesandbox.io/p/sandbox/elated-rumple-c5q8r5?file=/src/App.js:30,17).

**Comment by staticshock** [comment] 2024-03-25 19:20
I can also reproduce the issue on [browserstack](https://browserstack.com). Can one of you try loading up Chrome 123 on browserstack and trying it there?

**Comment by LFDanLu** [comment] 2024-03-25 19:56
I just tried on browerstack on Chrome 123, wasn't able to reproduce, albiet the trial only gave me like a minute to try haha. Seeing if there is a corp account that I can use to play around with some more.

**Comment by psirenny** [comment] 2024-04-25 09:25
> I can also reproduce the issue on [browserstack](https://browserstack.com). Can one of you try loading up Chrome 123 on browserstack and trying it there?

Same, I can also reliably reproduce the issue on Chrome 124 and Brave 165.

**Comment by LFDanLu** [comment] 2024-04-25 17:00
I can now reproduce it reliably via the original sandbox in Chrome 124, will see about if we can get some time to debug in an upcoming sprint.

**Comment by staticshock** [comment] 2024-04-25 17:11
Take a snapshot of your entire universe down to the atoms—reproducibility is a precious gift!

**Comment by sookmax** [comment] 2024-05-03 14:24
Looks like I'm the only outlier here that still cannot reproduce.. 😭 on Chrome Version 124.0.6367.119 (Official Build) (arm64)


https://github.com/adobe/react-spectrum/assets/71210554/82c80706-f502-4847-8ec0-ab2abbd7b096

**Comment by danielweck** [comment] 2024-05-03 16:08
I can reproduce this 100% with Chromium/Chrome/Edge etc. but not with Firefox and Safari (all latest versions available, MacOS)

**Comment by danielweck** [comment] 2024-05-03 16:12
Another data point: the long text MUST cause an offset of the first character (left hand side of the text clipped), otherwise the bug doesn't occur. In other words, if the text is longer than the input field but it is left-aligned (right hand side of the text clipped) then the bug doesn't occur.

**Comment by danielweck** [comment] 2024-05-06 10:09
Another find: setting the `isNonModal` prop to true seems to fix the problem ... but of course we need to be aware of unintended consequences, notably with respect to accessibility (tab cycling for keyboard users continues to work as normal, but screen reader users might encounter issues with the inert background behind the pop over ... I haven't tested yet)

https://github.com/adobe/react-spectrum/blob/cf0846eb49fcdde669e9dc4c0c2d2109b50e46dd/packages/%40react-aria/overlays/src/usePopover.ts#L33-L40


```js
  /**
   * Whether the popover is non-modal, i.e. elements outside the popover may be
   * interacted with by assistive technologies.
   *
   * Most popovers should not use this option as it may negatively impact the screen
   * reader experience. Only use with components such as combobox, which are designed
   * to handle this situation carefully.
   */
  isNonModal?: boolean,
```

**Comment by psirenny** [comment] 2024-05-06 10:12
> Another find: setting the `isNonModal` prop to true seems to fix the problem

The most frustrating unintended consequence (for us), is that it disables click-outside to dismiss.

**Closed** 2024-06-07 01:08 UTC
Labels: RAC
