### ISSUE TITLE
useSliderState returns wrong values when used with minValue different than 0

### ISSUE THREAD

**Issue by sara0405** [adobe/react-spectrum#7279] opened 2024-10-29 10:40 UTC
### Provide a general summary of the issue here

When `useSliderState` hook is used with `minValue` that is different from 0, and default values that are all multipliers of `step`, starting from `minValue`, hook returns wrong values because it calculates values starting from 0.

### 🤔 Expected Behavior?

Hook should return correct values.

### 😯 Current Behavior

```
const {values} = useSliderState({
  minValue:1,
  maxValue:10,
  step: 1.5,
  defaultValue: [1.5, 10],
  numberFormatter
});

console.log(values); // [1, 9]
```

while the result should be [1,10]

### 💁 Possible Solution

The source of bug is in this function: https://github.com/adobe/react-spectrum/blob/4baa1b08ed92d1b0ef83e64fc4a0b22cdda5e70b/packages/%40react-stately/slider/src/useSliderState.ts#L179

```diff
let restrictValues = useCallback((values: number[]) => values?.map((val, idx) => {
- let min = idx === 0 ? minValue : val[idx - 1];
- let max = idx === values.length - 1 ? maxValue : val[idx + 1];
+ let min = idx === 0 ? minValue : values[idx - 1];
+ let max = idx === values.length - 1 ? maxValue : values[idx + 1];
     return snapValueToStep(val, min, max, step);
  }), [minValue, maxValue, step]);
```

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/agitated-wright-8v69cf?workspaceId=ed8e9704-1d4f-49ed-b533-d6c0713edeb4

### Version

react-stately: 3.32.2

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

macOS Sonoma

**Comment by snowystinger** [comment] 2024-11-04 19:07
Thanks for diving into this.
This looks like the correct analysis, would you be willing to make a PR for it with a test?

**Comment by Danji-ya** [comment] 2024-11-07 13:56
@snowystinger 
I am interested in this issue would you please assign it to me.

**Comment by Danji-ya** [comment] 2024-11-08 14:25
Thank you @sara0405
I can reproduce the issue in the code below.
```
const {values} = useSliderState({
  minValue:1,
  maxValue:10,
  step: 1.5,
  defaultValue: [1, 10],
  numberFormatter
});

// values:  (2) [1, 9]
```

**Closed** 2024-11-13 15:02 UTC
Labels: bug
