### ISSUE TITLE
Add footer support to react aria components' table component

### ISSUE THREAD

**Issue by willtitterton** [adobe/react-spectrum#7146] opened 2024-10-04 16:21 UTC
### Provide a general summary of the feature here

Currently it's not possible to include a table footer when using the table component provided by the react aria components library. 

### 🤔 Expected Behavior?

The following should be possible.

```
 <Table>
     <TableHeader>...</TableHeader>
     <TableBody>...</TableBody>
     <TableFooter>...</TableFooter>
 </Table>
```

### 😯 Current Behavior

Supplying a valid `tfoot` html tag after the table body results in the following error: 
`Warning: validateDOMNesting(...): <tfoot> cannot appear as a child of <#fragment>.at tfoot`

### Semantic information
The <tfoot> tag, along with the <thead> and <tbody> tags, provides semantic information that can be used for both screen and print rendering. 

### Contextual information
The <tfoot> tag provides contextual information for assistive technologies like screen readers and search engines. 

### Table scrolling
The <tfoot> tag allows the table body to scroll independently of the header and footer. This is especially useful for large tables.

**Comment by yihuiliao** [comment] 2024-10-04 18:31
Closing as a dupe of https://github.com/adobe/react-spectrum/issues/4372

**Closed by yihuiliao** 2024-10-04 18:31 UTC
