### ISSUE TITLE
RAC Tooltip doesn't work for custom components

### ISSUE THREAD

**Issue by emlai** [adobe/react-spectrum#5733] opened 2024-01-22 13:30 UTC
### Provide a general summary of the issue here

RAC Tooltip doesn't open when the trigger element is a custom component, such as:

```tsx
function MyButton(props) {
  return <button type="button" {...props} />;
}
```

### 🤔 Expected Behavior?

Tooltip should work for custom components, as long as they're focusable and hoverable.

### 😯 Current Behavior

Tooltip doesn't work for custom components.

### 🔦 Context

In our design system, we need to support adding a tooltip to various custom components such as Button, TextField, Select, ComboBox.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/recursing-liskov-mfyj6m?file=%2Fsrc%2FApp.js%3A20%2C63

### Version

1.0.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS 14.2.1

**Comment by ryo-manba** [comment] 2024-01-22 14:13
It appears that for using Tooltip, you should use the [useButton](https://react-spectrum.adobe.com/react-aria/useButton.html) hook instead of directly passing props. Check this out at the following link for a demo: https://codesandbox.io/p/sandbox/distracted-kowalevski-46fp8s?file=%2Fsrc%2FApp.js

Additionally, for other components like TextField, Select, ComboBox, there are specific hooks available for each. It might be beneficial to use them in conjunction with your custom components!

**Comment by emlai** [comment] 2024-01-22 16:47
For context, we're not using RAC Select/ComboBox because RAC ComboBox doesn't support multi-selection (https://github.com/adobe/react-spectrum/issues/2140).
And I assume `useComboBox` wouldn't work with a `react-select`-based ComboBox implementation.

**Comment by reidbarber** [comment] 2024-01-22 16:59
As @ryo-manba mentioned, the trigger element should be from a focusable/hoverable element either from RAC, or created by a hook like useButton. Here is a good explanation from @LFDanLu in https://github.com/adobe/react-spectrum/discussions/5119 on how to handle this:

> Our RAC Button's call of useButton accesses this context via a [useFocusable](https://github.com/adobe/react-spectrum/blob/f65c181868be342a9238e5c26c12a1a0d346ca2f/packages/%40react-aria/button/src/useButton.ts#L97) call so if you were to use your own custom button element you'd have to call useButton as well. For non-button elements you'd call useFocusable and usePress.

**Comment by reidbarber** [comment] 2024-01-23 16:49
Closing since this is expected behavior, but feel free to post any related follow-up questions here.

**Closed by reidbarber** 2024-01-23 16:49 UTC

**Comment by lelumees** [comment] 2024-01-29 13:53
Just noting here that the `useButton` workaround does not seem to work when it is used for cloned children.

```tsx
function MyTooltip(props) {
  const triggerRef = React.useRef();
  const { buttonProps } = useButton(props, triggerRef);
  const trigger = React.cloneElement(
    props.children,
    mergeProps(buttonProps, props.children.props, { ref: triggerRef })
  );

  return (
    <TooltipTrigger delay={0} closeDelay={0}>
      {trigger}
      <Tooltip>{props.content}</Tooltip>
    </TooltipTrigger>
  );
}

```

Full demo here: https://codesandbox.io/p/sandbox/goofy-sunset-plg3c3

**Comment by lelumees** [comment] 2024-01-29 17:59
> Right, there's a context that is consumed inside useButton, so that needs to be in a component inside the TooltipTrigger, not outside it.

Thanks for the explanation @snowystinger! Is there a better way to build your own custom Tooltip that would utilise RAC Tooltip components underneath? We've been using `react-aria` hooks so far, but the API provided by RAC is much cleaner and we'd love to use that instead.

**Comment by LFDanLu** [comment] 2024-01-29 19:37
Could you use our RAC button as well? Or is the trigger element provided to your Tooltip component not controlled directly by you (aka is it provided by the end user?) What setup do you have for your custom Tooltip? For you sandbox, you can probably just wrap the trigger in a wrapper that calls `useButton`

**Comment by lelumees** [comment] 2024-01-30 11:36
> Or is the trigger element provided to your Tooltip component not controlled directly by you (aka is it provided by the end user?)
Yes, exactly that, hence the RAC Button is off the table for us.

> What setup do you have for your custom Tooltip?
Not sure I get this, but it is built as part of an in-house design system component kit. Ideally we'd not change anything functionally and just apply our styles on top of the Tooltip provided by RAC. We do not restrict the children to be of any specific component, so worst case it can be something not button-like, e.g. just an icon.

> For you sandbox, you can probably just wrap the trigger in a wrapper that calls useButton
I am aware of that and I've considered it, but I would ideally not wrap children with any additional components to keep the DOM tree clean and avoid causing layout issues.

Thanks for jumping into this!

**Comment by LFDanLu** [comment] 2024-01-30 17:54
> I am aware of that and I've considered it, but I would ideally not wrap children with any additional components to keep the DOM tree clean and avoid causing layout issues.

The wrapper could do the same clone operation + useButton call that you've done in your sandbox and return the result of that, no? That way you aren't adding an extra DOM node.

**Comment by lelumees** [comment] 2024-01-31 09:15
> The wrapper could do the same clone operation + useButton call

I thought it would have the same problem as the originally suggested solution, but you are right - if I do the cloning in a wrapper component it works 🎉 

Thanks a lot @LFDanLu and others for helping me out!

I will leave the working code snippet here in case if anyone wants to use the same solution:
```tsx
import React from "react";
import "./styles.css";
import { Tooltip, TooltipTrigger } from "react-aria-components";
import { useButton, mergeProps } from "react-aria";

export default function App() {
  return (
    <div style={{ padding: 50 }}>
      <MyTooltip content="Hello">
        <span>Show me tooltip</span>
      </MyTooltip>
    </div>
  );
}

function TriggerWrapperWithoutDiv(props) {
  const triggerRef = React.useRef();
  const { buttonProps } = useButton(props, triggerRef);

  return React.cloneElement(
    props.children,
    mergeProps(buttonProps, props.children.props, { ref: triggerRef })
  );
}

function MyTooltip(props) {
  return (
    <TooltipTrigger delay={0} closeDelay={0}>
      <TriggerWrapperWithoutDiv>{props.children}</TriggerWrapperWithoutDiv>
      <Tooltip>{props.content}</Tooltip>
    </TooltipTrigger>
  );
}

```
