### ISSUE TITLE
Tabbing out of text field when using allowsCustomValue clears the selectedItem

### ISSUE THREAD

**Issue by garand** [adobe/react-spectrum#4728] opened 2023-06-28 16:42 UTC
# 🐛 Bug Report 

When `allowsCustomValue` is set to true, and a predefined option is selected, when pressing Tab to leave the input field, the `selectedKey` and `selectedItem` are reset to `null`.

## 🤔 Expected Behavior

If a predefined option is selected, tabbing out of the input field should keep the `selectedKey` and `selectedItem` values.

## 😯 Current Behavior

When `allowsCustomValue` is set to true, and a predefined option is selected, when pressing Tab to leave the input field, the `selectedKey` and `selectedItem` are reset to null, but the `inputValue` remains correct. If you click outside of the texbox to remove focus then it keeps the `selectedKey` and `selectedItem`

## 💻 Code Sample

Here's a StackBlitz recreation. https://stackblitz.com/edit/stackblitz-starters-dp549h?file=src%2FApp.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | Latest (3.26.0)
| Browser          | All browsers
| Operating System | macOS

**Comment by reidbarber** [comment] 2023-06-28 16:58
On `Tab`, the value is getting committed:

https://github.com/adobe/react-spectrum/blob/2b6302bbec3ab48c9efb22b88d521a37227385ec/packages/%40react-aria/combobox/src/useComboBox.ts#L113-L120

where state.commit() has a case for `allowsCustomValue`:

https://github.com/adobe/react-spectrum/blob/2b6302bbec3ab48c9efb22b88d521a37227385ec/packages/%40react-stately/combobox/src/useComboBoxState.ts#L296-L298

where `commitCustomValue` sets the `selectedKey` as `null`:

https://github.com/adobe/react-spectrum/blob/2b6302bbec3ab48c9efb22b88d521a37227385ec/packages/%40react-stately/combobox/src/useComboBoxState.ts#L265-L269

So this is the expected behavior right now.

If we wanted to change this behavior, we would need to add a check if there is no `selectedKey` and `allowsCustomValue` is provided.

**Comment by garand** [comment] 2023-06-28 17:04
@reidbarber Thanks for the quick response... that makes sense, but it feels wrong that two ways of moving focus out of a text box would have two different outcomes.

Packages like Radix allow calling `event.preventDefault` in their custom handlers, maybe that could be an added feature here. 🤔

**Comment by LFDanLu** [comment] 2023-06-28 18:49
https://github.com/adobe/react-spectrum/issues/2413 covers this I believe. https://github.com/adobe/react-spectrum/pull/2670 was opened to fix it, but is stale at this point so will have to be revisited.

**Comment by garand** [comment] 2023-06-28 19:04
@LFDanLu Oh yeah, #2670 looks to be exactly what I'm looking for! Hoping that gets merged in or the same behavior is exposed as an option.

**Comment by snowystinger** [comment] 2024-07-30 11:52
Looks like this wasn't auto closed by https://github.com/adobe/react-spectrum/pull/2670
closing now

**Closed by snowystinger** 2024-07-30 11:52 UTC
