### ISSUE TITLE
Support for deno / fresh

### ISSUE THREAD

**Issue by chrisirhc** [adobe/react-spectrum#3860] opened 2022-12-17 05:01 UTC
# 🙋 Feature Request

Seems like react-spectrum relies on transpilation for styles to be injected. 

## 🤔 Expected Behavior

Some way for the styles to be reflected when using with deno/fresh.

## 😯 Current Behavior

DOM renders fine along with interaction but no styles.

## 💁 Possible Solution

* Potential CSS modules support in deno.
* Other kinds of support. Perhaps similar to NextJS support. I'll need to investigate further. 

## 🧢 Your Company/Team

Hobby project

**Comment by LFDanLu** [comment] 2023-01-11 18:55
Duplicate of https://github.com/adobe/react-spectrum/issues/781

**Comment by chrisirhc** [comment] 2023-01-12 13:00
How have you verified that this is a preact issue? Spectrum depends on CSS modules which deno/fresh do not support since there's no transpilation step. 
I was able to get the DOM to render fine via preact but no styles were applied.

**Comment by LFDanLu** [comment] 2023-01-12 18:15
Apologies, jumped the gun when diagnosing this issue.

**Comment by devongovett** [comment] 2023-01-17 21:22
Two issues here:

1. Fresh uses Preact, so I don't think we could claim that it is supported unless we also support Preact. That is tracked in #781. At the moment, unless a third party is willing to contribute, it likely won't happen anytime soon.
2. For styling, we have a hard requirement that build tools have some way of importing stylesheets from JavaScript. Our CSS modules are pre-compiled to regular CSS files before we publish to npm so that is not an issue. The issue is loading the CSS. We use the `import` statement for that, which is widely supported by other tools. This is required to ensure CSS is loaded together with the corresponding JS. You can read my comment on a similar Next.js issue for more context: https://github.com/vercel/next.js/issues/19936#issuecomment-878465841. Unless Fresh adds support for importing CSS, I don't think we really have many options here.

Given these points, I don't think we can support Fresh in its current state. You are welcome to open issues on Fresh for CSS support or help with Preact support for React Spectrum. In the meantime, I'll close this issue and we can re-evaluate if the situation changes.

**Closed by devongovett** 2023-01-17 21:22 UTC
