### ISSUE TITLE
`data-hovered` props is being eaten

### ISSUE THREAD

**Issue by unional** [adobe/react-spectrum#6891] opened 2024-08-15 22:59 UTC
### Provide a general summary of the issue here

When setting the data attribute prop `data-hovered`, the prop is eaten and not showing up in the DOM element.

### 🤔 Expected Behavior?

`<Button data-hovered/>` should yield `<button data-hovered/>`

### 😯 Current Behavior

`<Button data-hovered/>` yields `<button/>`

### 💁 Possible Solution

Haven't look into the code, but likely there is a spread `const { 'data-hovered': dataHovered, ...rest } = props` and missing `<button data-hovered={dataHovered}/>`

another possibility is that since those data-attributes are managed by rac, a merge is missing to honor the initial values.

### 🔦 Context

This make it not possible to set the hover state without some hack/workaround.

This could be the root cause of #6198 #4411 

Related to #6522 #6403 

### 🖥️ Steps to Reproduce

[codesandbox](https://codesandbox.io/p/sandbox/react-aria-components-template-g7wmmk?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzrrz1o900063b6jl16zdonz%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzrrz1o900023b6j07cvxp3i%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzrrz1o900033b6j126o30a5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzrrz1o900053b6jtpeodcw9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzrrz1o900023b6j07cvxp3i%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzrrz1o900013b6j3wg8foh6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzrrz1o900023b6j07cvxp3i%2522%252C%2522activeTabId%2522%253A%2522clzrrz1o900013b6j3wg8foh6%2522%257D%252C%2522clzrrz1o900053b6jtpeodcw9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzrrz1o900043b6jgie0u6fc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clzrrz1o900053b6jtpeodcw9%2522%252C%2522activeTabId%2522%253A%2522clzrrz1o900043b6jgie0u6fc%2522%257D%252C%2522clzrrz1o900033b6j126o30a5%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzrrz1o900033b6j126o30a5%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

In the repro, you can see that `data-hover` is being recognized:
![image](https://github.com/user-attachments/assets/3cab854f-99d9-40fd-9ee9-9abc06c05964)

This is because `data-hover` is not a data attribute managed by `react-aria-components`.
So the prop is added to the DOM:

```html
<button data-hover="true" type="button" class="data-[hover]:bg-blue-300" data-rac="">data-hover set</button>
```

When hovering on the one with `data-hovered` CSS, it is working. i.e. `:hover` is applying `data-hovered` (and `data-focused`) correctly:
![image](https://github.com/user-attachments/assets/77202b5c-fdb8-47a4-b8c6-ea404fc1261b)

But looking at the first button you will see the `data-hovered` prop is missing:

```html
<button type="button" class="data-[hovered]:bg-red-500" data-rac="">data-hovered set</button>
```

while the code defined it:

```html
      <Button
        data-hovered
        className="data-[hovered]:bg-red-500"
        onPress={() => alert("Hello world!")}
      >
        data-hovered set
      </Button>
```

As a side note, setting element state from dev tool doesn't work:
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/52227ce1-9783-4487-8faa-2fb1aa6796dc">

That's probably a limitation to the data-attribute approach, I guess.

### Version

react-aria-components: 1.3.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

### 🧢 Your Company/Team

Palo Alto Networks

**Comment by snowystinger** [comment] 2024-08-16 01:06
I think the first question we need to answer is, what is the use case here? Is it just visual regression testing?

<details>
<summary>
Thoughts on a possible implementation below, but not going to consider further until we answer if this is something we actually want to support.
</summary>
We could add something like this inside useRenderProps
```
  let keys = Object.keys(dataAttributes || {});
  let deps = keys.map(k => props[k]).concat(keys.map(k => dataAttributes[k]));
  let mergedDataAttributes = useMemo(() => {
    let dataAttrs = {} as Record<string, string | undefined>;
    for (let key of keys) {
      dataAttrs[key] = props[key] !== undefined ? props[key] : dataAttributes[key];
    }
    return dataAttrs;
  }, [...deps]);
```

Where `dataAttributes` is an object containing what we currently explicitly place as props on the target element. The keys in dataAttributes matter, we wouldn't want this set to change, ever, or memoing will be harder.

This would default to our own value for the data attribute first, then would fallback to any on the props.

I'm a little cautious about this because while the data-attributes are documented, there's no way to warn a user if they are about to pass one into a component which is in conflict with one that we are going to use. We wouldn't be able to warn users about it either because they may be doing it on purpose like in your example.

I'm also not convinced which one should win, what I've outlined above is a blend, since we can't enforce "not" setting it if we do this. Making it so the user always wins is a lot of power (with great power comes great responsibility) on the flip side.

Finally, it does make useRenderProps a little slower. We could move it out to another hook to work around it though.
</details>

**Comment by unional** [comment] 2024-08-16 01:15
My use case is visual regression testing, as well as specification and documentation.
I want the engineer and designer going to our website and storybook to see exactly how the component should look like on various state. And also have it match the Figma defined by the design system team.

In terms of code and consistency, at it also nice and natural to see what you defined shows up on the DOM for `data-*`, just like `aria-*` attributes.

**Comment by snowystinger** [comment] 2024-08-16 01:24
> In terms of code and consistency, at it also nice and natural to see what you defined shows up on the DOM for data-*, just like aria-* attributes.

But this isn't true, we control many aria-* attributes, so if you send them in as props, they may or may not come out on the other side and they may be merged/altered. That's a majority of the reason for this library.

I don't think consistency applies here as we are consistent in our handling of these. We have certain properties that we are going to apply regardless of what a user tries to send it. Right now, that applies to a certain set of documented data-* attributes we consider to be API.

**Comment by unional** [comment] 2024-09-14 00:56
It seems like I somehow didn't mentioned that specifying `data-hover` in `@headlessui/react` works as expected. It is also using `react-aria` under the hood.

**Comment by snowystinger** [comment] 2024-09-16 04:57
It appears they are using React Aria, not React Aria Components https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/button/button.tsx

React Aria isn't responsible for dealing with the data-* attributes, that's not part of its API. So you could build your own components from the hooks and make the data-* attributes whatever you like.

I'm going to close this issue as working as intended. I think we can continue discussions over on https://github.com/adobe/react-spectrum/issues/6403 if there's more as I believe that's really what you're trying to do.

**Closed by snowystinger** 2024-09-16 04:57 UTC
