### ISSUE TITLE
OverlayContainer no longer accepts <div> props like className

### ISSUE THREAD

**Issue by dlech** [adobe/react-spectrum#3375] opened 2022-08-03 17:07 UTC
# 🐛 Bug Report 

Upgrading from react-aria from 3.17.0 to 3.18.0 causes a breaking change in the type checking of `OverlayContainer`. It no longer accepts props like `className`.

See: https://github.com/pybricks/pybricks-code/runs/7656753018?check_suite_focus=true#step:5:6

## 🤔 Expected Behavior

Since the container is a `<div>`, `OverlayContainer` should accept any props valid for that element.

Also minor version releases should not contain breaking changes.

## 😯 Current Behavior

Type checking fails.

## 💁 Possible Solution

Replace `DOMAttributes` with something more specific in:

    export interface ModalProviderProps extends DOMAttributes

## 🔦 Context

We cannot upgrade the `react-aria` package until this is fixed or we find a workaround.

## 💻 Code Sample

Code from the repo in the CI link above:

```typescript
                <OverlayContainer className={Classes.PORTAL}>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

Pybricks

## 🕷 Tracking Issue (optional)

https://github.com/pybricks/pybricks-code/pull/1021

**Comment by reidbarber** [comment] 2022-08-08 15:52
Closing as a duplicate of https://github.com/adobe/react-spectrum/issues/3372, this should get fixed soon

**Closed by reidbarber** 2022-08-08 15:52 UTC
