### ISSUE TITLE
Open Table performance bugs

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#1205] opened 2020-10-28 20:16 UTC
# 🐛 Bug Report 
The following bugs were captured in prior testing sessions.

- [ ] When I focus the checkbox cell and hold the down arrow to scroll down, it becomes very choppy in the scrolling, maybe disable checkbox focus animation

## 🧢 Your Company/Team

RSP

**Comment by LFDanLu** [comment] 2021-05-26 00:21
For posterity:
- At this time, the first issue doesn't seem too bad on Chrome. Most noticeable in the many rows/columns story but only initially.
-  Second error still happens, attaching error screenshot:
![image](https://user-images.githubusercontent.com/9661127/119584248-238df680-bd7d-11eb-8f3b-07324adfb255.png)
```
TypeError: Cannot read property 'key' of undefined
    at TableLayout.getColumnWidth (TableLayout.ts:191)
    at TableLayout.buildColumn (TableLayout.ts:221)
    at TableLayout.buildNode (TableLayout.ts:288)
    at TableLayout.buildChild (ListLayout.ts:173)
    at TableLayout.buildHeaderRow (TableLayout.ts:156)
    at TableLayout.buildNode (TableLayout.ts:283)
    at TableLayout.buildChild (ListLayout.ts:173)
    at TableLayout.buildHeader (TableLayout.ts:131)
    at TableLayout.buildCollection (TableLayout.ts:56)
    at TableLayout.validate (ListLayout.ts:130)
```
- the third issue seems related to the first? Still seems to be an issue when reducing the number of rows so might be something separate

**Comment by dannify** [comment] 2021-06-09 00:35
1 and 2 might be fixed by focus change fix? To be confirmed.

**Comment by LFDanLu** [comment] 2021-06-09 23:30
Update:
1 and 3 are still valid after the focus change fix. Mainly noticeable in Chrome and Edge in the "many rows and columns" story

**Comment by LFDanLu** [comment] 2021-06-14 18:40
Turns out the performance issues aren't an issue on production builds of React. Original reported issue found in the following storybook: https://reactspectrum.blob.core.windows.net/reactspectrum/f96f4275059d894ae598842e824bceb6adb01893/storybook/index.html?path=/story/table--many-columns-and-rows. Seeing some strange behavior on windows chrome though, digging

**Comment by dannify** [comment] 2021-08-04 00:34
This seems enough of an edge case to put on hold for now.

**Comment by snowystinger** [comment] 2022-12-16 21:52
@LFDanLu I think these are all resolved now, can you double check?

**Comment by LFDanLu** [comment] 2022-12-16 22:06
The only issue that remains now is the "focus checkbox and hold down arrow" one, I'll update this ticket to reflect that

**Comment by snowystinger** [comment] 2023-02-14 21:42
We cannot reproduce anymore. Closing

**Closed by snowystinger** 2023-02-14 21:42 UTC
Labels: bug, rsp:TableView
