### ISSUE TITLE
useOverlayPosition: wrong positioning when page is zoomed

### ISSUE THREAD

**Issue by LosYear** [adobe/react-spectrum#4478] opened 2023-05-04 13:35 UTC
# 🐛 Bug Report 
To reproduce this bug simply open the docs (https://react-spectrum.adobe.com/react-aria/usePopover.html#placement), click on the trigger which shows start-positioned popup and zoom the page

## 🤔 Expected Behavior

Popup stays at the same place where it was when page is not zoomed

## 😯 Current Behavior

<img width="600" alt="Screenshot 2023-05-04 at 16 33 13" src="https://user-images.githubusercontent.com/1065122/236220798-8fd04a9e-92d4-4885-9873-06820ddda0b8.png">

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 
| Browser          |  Yandex Browser, based on Chromium 110.0.5481.2318 (x86_64) 
| Operating System | macOS Version 13.1 (Build 22C65)

**Comment by LFDanLu** [comment] 2023-05-05 17:46
I can't seem to reproduce when zooming in/out with CMD+/- on the latest version of the Yandex browser, what were your exact steps to reproduce?

**Comment by LosYear** [comment] 2023-05-05 19:33
Have you tried with zoom gesture using touchpad?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1065122/236552854-0e17a6d5-c3ed-4632-a1d0-9986f4472d9e.gif)

**Comment by LFDanLu** [comment] 2023-05-05 21:05
Ah I see, thank you. This is a duplicate of https://github.com/adobe/react-spectrum/issues/2700 then, going to close this out in favor of that one.

**Closed** 2023-05-05 21:05 UTC
