### ISSUE TITLE
Documentation for testing in jsdom environments

### ISSUE THREAD

**Issue by bmingles** [adobe/react-spectrum#6146] opened 2024-04-03 21:28 UTC
### 🙋 Documentation Request

I recently ran into an issue where unit tests were failing after a certain threshold of items was added to a Spectrum ListView component. The underlying issue turned out to be that [`useVirtualizerItem` depends on `scrollHeight`](https://github.com/adobe/react-spectrum/blob/0b2a838b36ad6d86eee13abaf68b7e4d2b4ada6c/packages/%40react-aria/virtualizer/src/useVirtualizerItem.ts#L49C3-L49C60) which always returns `0` in a `jsdom` testing environment. This was causing "Maximum update depth exceeded" errors in tests. I was able to resolve it by mocking `HTMLElement.prototype.scrollHeight`, but it took some time to figure out what the underlying issue was.

It would be helpful for the testing docs (https://react-spectrum.adobe.com/react-spectrum/testing.html) to include additional details of any limitations / workarounds that might exist for such cases.

**Comment by reidbarber** [comment] 2024-04-03 21:30
In progress @ https://github.com/adobe/react-spectrum/issues/6146. Preview [here](https://reactspectrum.blob.core.windows.net/reactspectrum/726a5e8f0ed50fc8d98e39c74bd6dfeb3660fbdf/docs/react-spectrum/testing.html).

**Comment by bmingles** [comment] 2024-04-03 21:47
Great, looks like the [#virtualized-components](https://reactspectrum.blob.core.windows.net/reactspectrum/726a5e8f0ed50fc8d98e39c74bd6dfeb3660fbdf/docs/react-spectrum/testing.html#virtualized-components) section was exactly what I needed.

**Comment by reidbarber** [comment] 2024-04-03 21:49
Great! Closing as a duplicate of https://github.com/adobe/react-spectrum/issues/3703

**Closed by reidbarber** 2024-04-03 21:50 UTC
