### ISSUE TITLE
useSelect - Mac Voiceover cuts off reading highlighted option

### ISSUE THREAD

**Issue by kaplantm** [adobe/react-spectrum#2779] opened 2022-01-27 17:33 UTC
# 🐛 Bug Report 

When using Mac OS voiceover (Big Sur, 11.1, Chrome 97.0.4692.71), the selected value of the dropdown is read each time the user changes the highlighted option, audibly cutting off the reading of the highlighted option.

https://user-images.githubusercontent.com/13424028/151412218-64d8c587-c62a-4527-a6e7-c21125ad3764.mov

## 🤔 Expected Behavior

The selected value of the dropdown is not read each time the user changes the highlighted option. User should clearly hear the option they now have highlighted. 

## 💻 Code Sample

The example built into the [useSelect docs.](https://react-spectrum.adobe.com/react-aria/useSelect.html)

Also the styled examples ([tailwind](https://codesandbox.io/s/hardcore-moon-xzc4r?file=/src/ComboBox.tsx), [styled components ](https://codesandbox.io/s/sharp-sun-e3fgd?file=/src/Select.tsx)).
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          | Chrome 97.0.4692.71
| Operating System | Big Sur, 11.1

**Comment by snowystinger** [comment] 2022-01-29 01:24
Hey! thanks for reporting this, it's definitely frustrating.
Unfortunately it's a chrome + VO bug. Our accessibility team found this:

> I am able to reproduce this bug using the WAI-ARIA Select-Only ComboBox example: https://www.w3.org/TR/wai-aria-practices-1.2/examples/combobox/combobox-select-only.html, and this multi-select list box example: https://www.w3.org/TR/wai-aria-practices-1.2/examples/listbox/listbox-rearrangeable.html#ex2_label, when only one item has been selected. With the multi-select example, it seems to depend on whether more than one item has been selected. When more than one item is selected, VoiceOver in Chrome does an ok job distinguishing between selected and unselected items in the listbox. But, with only one item selected, it seems that Chrome is forcing VoiceOver to announce the selected item whenever the user navigates, but once I multi-select, things seem to work as expected, even after deselecting so that only one item remains selected.

You can read this explanation on why Chrome + VO is the way it is, https://stackoverflow.com/questions/54139306/does-mac-voiceover-limit-its-functionality-on-chrome-firefox/54147459 it has some good links explaining accessibility support

**Comment by yihuiliao** [comment] 2024-08-22 21:21
Closing since unable to reproduce in MacOS 13.5.2 and Chrome v127. Seems like this has been fixed in newer versions.

**Closed by yihuiliao** 2024-08-22 21:21 UTC
Labels: browser bug
