### ISSUE TITLE
Tooltip seems to only work with certain components

### ISSUE THREAD

**Issue by literalpie** [adobe/react-spectrum#7282] opened 2024-10-29 16:22 UTC
### Provide a general summary of the issue here

I would expect to be able to use a Tooltip with any component or element, but it seems to be inconsistent.

### 🤔 Expected Behavior?

A tooltip should show if the children of TooltipTrigger are hovered or focused, regardless of what the children are. If there are requirements (eg. the children must be react-aria components or must have a ref attribute), this should be clearly documented.

### 😯 Current Behavior

The tooltip shows if there is a react-aria button in the TooltipTrigger, but not for divs or native browser buttons.

### 🖥️ Steps to Reproduce

See [this stackblitz](https://stackblitz.com/edit/vitejs-vite-dve6ze?file=package.json,src%2FApp.tsx&terminal=dev). hover or focus each element in the example.

### Version

react-aria-components 1.4.1

### What browsers are you seeing the problem on?

Chrome, Safari

### What operating system are you using?

MacOS

**Comment by yihuiliao** [comment] 2024-10-29 19:11
I think this is a dupe of https://github.com/adobe/react-spectrum/issues/6142

**Closed** 2024-10-29 20:46 UTC
