### ISSUE TITLE
Button not working for all vendors that control onClick handler with delegated events

### ISSUE THREAD

**Issue by 7iomka** [adobe/react-spectrum#2869] opened 2022-02-18 01:57 UTC
# 🐛 Bug Report 

## 🤔 Expected Behavior
Button works with delegated events like onClick

## 😯 Current Behavior

Button prevent or not receive onClick handler from delegated event.

## 💁 Possible Solution
Manually handle `onClick` prop and call it alongside with `onClick` prop generated from hook.

## 🔦 Context

I try to use [Fancybox](https://fancyapps.com/docs/ui/fancybox/react)
It add global click event handler for all `[data-fancybox]` (or user custom selector) elements.
If I add this attribute to react-spectrum button - nothing happens, modal is not opening when I click.
If I do this for simple div or button - anything works fine.

## 💻 Code Sample
https://codesandbox.io/s/nervous-lamport-2mo5yh

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | latest
| Browser          | Chrome
| Operating System | MacOS

**Comment by snowystinger** [comment] 2022-02-18 02:29
Hey, I get that it can be frustrating that something doesn't just work. It'd be nice if FancyBox provided some context or something to make it a little easier to use with a third party library.

However, you can do something like this https://codesandbox.io/s/cool-sky-798lx1?file=/src/App.js

And this is actually better for accessibility because we normalize how buttons work across browsers/devices/input modes. See https://react-spectrum.adobe.com/blog/building-a-button-part-1.html

**Comment by 7iomka** [comment] 2022-02-18 09:47
> Hey, I get that it can be frustrating that something doesn't just work. It'd be nice if FancyBox provided some context or something to make it a little easier to use with a third party library.
> 
> However, you can do something like this https://codesandbox.io/s/cool-sky-798lx1?file=/src/App.js
> 
> And this is actually better for accessibility because we normalize how buttons work across browsers/devices/input modes. See https://react-spectrum.adobe.com/blog/building-a-button-part-1.html

Interesting, thanks for that idea.
However, I opened your demo from mobile device and when I press on button I see unexpected result - modal open and close in the same time.
I think that is because of inner logic of onPress event, that fire twice - onKeydown and onTouchend? Strange case :( Maybe you have an idea how to fix that? I aldready see that behavior, but I don't find a way to fix that. Thanks!

**Comment by snowystinger** [comment] 2022-02-23 23:11
That's interesting, what device and os are you using?
I'm not seeing the behavior you're describing on my iPhone 15.3.1

It's a bit hard to tell in the video, but I do a quick tap on the button, it brings up the FancyBox, then I tapped the 'x' button. Then I tried a long press on the button, it brings up FancyBox again, then I tap the 'x' button again.

https://user-images.githubusercontent.com/698229/155425021-de24ff5c-bef2-4173-9af8-514391dc30a0.MP4

**Comment by 7iomka** [comment] 2022-02-25 17:15
@snowystinger
Sorry for delay in reply.
I have android smartphone, Xiaomi Redme Note 7 Pro, Chrome browser (all other browsers works the same)
Video recorded directly from my device:

https://user-images.githubusercontent.com/18473137/155757785-2d6e53a1-d76a-4b9f-8998-54eaae281f50.mp4

 
How you see, standard click (tap) trigger two similar events, and that is case why modal is open and closes.
But, the long press triggers one single event and modal is opened as I expect.

Same behavior you will see if open chrome devtools, change device to mobile device and reload codesandbox (in new tab) demo.

How to figure out? 
I need any workaround))
Thanks.

**Comment by snowystinger** [comment] 2022-03-03 02:27
Ah, this appears to be this browser bug
https://bugzilla.mozilla.org/show_bug.cgi?id=1692033

We don't fire extra events. The issue is that the fancy box is opened before all the events complete and Chrome/FF both decide that the newly added element should receive the click event instead of the original target.

You can see this in the codesandbox I originally added by adding an on click listener during the onPress callback to the document body and logging out it's target.

You can solve it in this way
https://codesandbox.io/s/peaceful-bird-05xh7g

as recommended here https://github.com/adobe/react-spectrum/issues/1513 along with extra information about what is actually happening

**Comment by snowystinger** [comment] 2022-03-05 00:16
Closing now, feel free to reopen if you still have issues

**Closed by snowystinger** 2022-03-05 00:16 UTC

**Comment by 7iomka** [comment] 2022-03-05 11:48
> Closing now, feel free to reopen if you still have issues

Thanks for the workaround.
It works, but it creates the need to create wrappers every time on the elements that contain the button.
Tell me your opinion, are there any problems in the next refactoring of the button source code?


```tsx
const { onClick } = props;

  const { onClick: generatedOnClick, ...restP } = {
    ...mergeProps(buttonProps, hoverProps, { onClick }),
  };

  const handleOnClick = useCallback(() => {
    generatedOnClick?.();
    onClick?.();
  }, [onClick, generatedOnClick]);

<button
      onClick={handleOnClick}
      {...restP}
    >
```

With this kind of workaround we support both click handlers - one from your hook, another from delegated/user events if their exists. Of course, user will use onPress instead of onClick, but he no have problems with one that I described here.

**Comment by snowystinger** [comment] 2022-03-05 17:06
We do want to solve this generally, but we haven't come up a solution we like yet. I'll look more at your code next week. Thanks!

**Comment by snowystinger** [comment] 2022-03-09 23:06
While working on this, it's come to our attention that canceling touchEnd may be the more appropriate solution. You can see that in this codesandbox, which shows how this works with buttons that aren't the React Spectrum buttons
https://codesandbox.io/s/quirky-williamson-lwtpv0?file=/src/App.js

Otherwise you need to put touch-actions: none on the button so that the browser doesn't think that touchstart is a scrolling event, this is something we already have on the RSP buttons and why touchstart appeared to work as intended.

Hopefully will have more updates on solving this in our code, but for now, this is the best workaround I can provide.
