### ISSUE TITLE
Popover not closing in Select RAC when tabbed out of focus

### ISSUE THREAD

**Issue by binaryartifex** [adobe/react-spectrum#5626] opened 2023-12-23 00:35 UTC
### Provide a general summary of the issue here

The Select RAC does not close its popover when tabbed out of focus - This is occurring in storybook and also my Nextjs application. (I initially thought it was only storybook)

### 🤔 Expected Behavior?

The Select RAC should close its popover when the user tabs out of focus from a currently focused item in the list.

### 😯 Current Behavior

Using the keyboard, with an item focused, the Select RAC does not close its popover when tabbed out of the list of items.

### 💁 Possible Solution

Controlling the Select's open status via setting a callback on the Listbox onFocusChange prop fixes it, however it still leaves the issue of why its doing it in the first place.

### 🖥️ Steps to Reproduce

1. Download react-aria provided storybook referenced in their docs [here](https://react-spectrum.adobe.com/react-aria/getting-started.html).
2. Proceed to the Select story and choose the Example story (the Docs section seems to work just fine funnily enough)
3. Using keyboard navigation focus an item from the list without selecting it
4. Now attempt to tab out of the list.

### Version

1.0.0 (RAC)

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows 11

**Comment by snowystinger** [comment] 2023-12-23 01:35
This is probably due to there being nothing focusable after it inside the storybook iframe. So focus leaves the iframe which can cause this odd behavior. If you put another element after it or view the story in a new tab it should work as expected which is why the docs work.

I think we have a duplicate of this issue somewhere. I'll look when I have a computer in front of me again.

**Comment by binaryartifex** [comment] 2023-12-23 02:24
@snowystinger ahh yeah fair enough, i mean im now controlling the `isOpen` and passing the same setState to `onOpenChange` on the Select itself and another `onFocusChange` on the Listbox which seems to have done the trick for the moment.

**Comment by snowystinger** [comment] 2024-01-02 17:34
Ok, we only talked about it internally. Here's the note we have of the behavior https://github.com/adobe/react-spectrum/pull/4931#pullrequestreview-1583533804
Unless you think the Next app is still a bug, I think we can close this as working as intended.

**Closed** 2024-01-07 09:05 UTC
