### ISSUE TITLE
Dismissable Modal/Dialog is dismissed when clicking on other portals

### ISSUE THREAD

**Issue by kylemh** [adobe/react-spectrum#5949] opened 2024-02-26 17:20 UTC
### Provide a general summary of the issue here

When using react-aria-component's Modal with a custom ModalOverlay and its contents include an element that also portals, the dialog is dismissed when the OTHER portals are clicked. I'm guessing this is because those 3rd party tools don't stop propogation of their click events, but I don't have control over that...

### 🤔 Expected Behavior?

I'd expect that the Dialog/Modal will only dismiss if the click event _starts_ on the `ModalOverlay`.

### 😯 Current Behavior

Any click event on a portal _above_ ModalOverlay in context causes the dismissal of the opened modal.

### 🔦 Context

I'm attempting to improve accessibility in the codebase by introducing `react-aria`; however, it's been a frustrating experience because it feels like it's all or nothing. For example, unrelated to this issue, `onPress` vs. `onClick` makes types a pain in the neck and I basically need to use `usePress` or `useButton` all over the codebase. In this scenario, there are multiple form elements which portal from MUI and any interaction causes them to get dismissed 😭 

### 🖥️ Steps to Reproduce

https://stackblitz.com/edit/react-ts-rewjnk?file=Modal.tsx

### Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you using?

MacOS

**Comment by snowystinger** [comment] 2024-02-27 06:38
Going to close as dupe of https://github.com/adobe/react-spectrum/issues/5916
Please continue the discussion in that issue.

**Closed by snowystinger** 2024-02-27 06:38 UTC
