### ISSUE TITLE
ListView is not rendering items correctly in NextJS

### ISSUE THREAD

**Issue by BengtHagemeister** [adobe/react-spectrum#2511] opened 2021-10-29 11:09 UTC
# 🐛 Bug Report 

As soon as there is a useEffect in place that sets some state (does not matter if useState is used or some react-aria state lists) ListViewItems will not render on first load. Only resizing the window will make them appear. Removing the useEffect will resolve this problem.

```JSX
import { ListView } from "../components/ListView";
import { Item } from "@react-stately/collections";
import { useEffect, useState } from "react";

export default function Index() {
  const [set, setSomething] = useState<Array<string>>([]);

  /**
   * UNCOMMENT THIS USEEFFECT TO SEE THE BUG IN ACTION
   *
   */

  // useEffect(() => {
  //   setSomething(["hello"]);
  // }, []);

  return (
    <div style={{ height: "200px", backgroundColor: "red" }}>
      <ListView items={[{ key: 1 }, { key: 2 }]}>
        {(item) => <Item key={item.key}>Hello World</Item>}
      </ListView>
    </div>
  );
}
```

## 🤔 Expected Behavior

All Items should render on initial page load.

## 😯 Current Behavior

Using useEffect in combination with state has the side effect that items are not rendered correctly.

## 🔦 Context

I was not able to use the prepackaged ListView Items from react-spectrum as they include css and can therefore not be used in NextJS. The provided component is a clone of the original @react-spectrum/list package excluding any css or other blocking things. 

## 💻 Code Sample

https://codesandbox.io/s/mystifying-chihiro-1fri1?file=/pages/index.tsx

The error can be reproduced with an empty nextjs project. Resizing the window will have the items reappear. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.0.0
| Browser          | Chrome
| Operating System | MacOS Big Sur

**Comment by snowystinger** [comment] 2021-11-03 00:31
Hey! I saw you had a note about the CSS not working, have you had a chance to go through this documentation? https://react-spectrum.adobe.com/react-spectrum/ssr.html#nextjs it seems to have resolved the issue for a number of people.

As for your issue with useEffect, I think it's because you aren't using the `SSRProvider` https://react-spectrum.adobe.com/react-aria/SSRProvider.html can you verify if that fixes your issue?

**Comment by BengtHagemeister** [comment] 2021-11-03 08:35
Hi. Thanks for your answer. About the CSS it was never my intention to use the packages including CSS, I maybe miss wrote that a little bit in the Context. 

I'm using the `SSRProvider` in my own app already, I just forgot to add it the CodeSandbox. I did now and it's also not working, so unfortunately its not that.

**Comment by reidbarber** [comment] 2021-11-03 16:45
I just tried React Spectrum's ListView in a Next.js app and it worked without issues, so that might help us isolate the problem.

For reference, I did:

```jsx
...
import {ListView, Item} from '@react-spectrum/list';
...

export default function Home() {
  const [something, setSomething] = React.useState('');

    React.useEffect(() => {
        setSomething('test');
    }, []);

  return (
    <React.StrictMode>
      <SSRProvider>
        <Provider theme={defaultTheme}>
          <ListView width="250px">
              <Item textValue="row 1">{something}</Item>
              <Item textValue="row 2">{something}</Item>
              <Item textValue="row 3">{something}</Item>
          </ListView>
        </Provider>
      </SSRProvider>
    </React.StrictMode>
  );
}
```
and added `"@react-spectrum/list"` to `next-transpile-modules` in next.js.config.

**Comment by BengtHagemeister** [comment] 2021-11-04 12:28
@reidbarber If you change your example to the dynamic version, exactly the same bug will appear also in the `"@react-spectrum/list"` package. So I think it has something todo with the virtualizer?

```JSX
...
import {ListView, Item} from '@react-spectrum/list';
...

export default function Home() {
  const [something, setSomething] = React.useState('');

    React.useEffect(() => {
        setSomething('test');
    }, []);

  const items = [{ key: 1 }, { key: 2 }];

  return (
    <React.StrictMode>
      <SSRProvider>
        <Provider theme={defaultTheme}>
          <ListView width="250px" items={items}>
               {(item) => <Item textValue="row 1">{item.key}</Item>}
          </ListView>
        </Provider>
      </SSRProvider>
    </React.StrictMode>
  );
}
```

**Comment by reidbarber** [comment] 2021-11-04 14:58
I just tried that example as well and it worked without issues. That was with versions:
```json
  "dependencies": {
    "@adobe/react-spectrum": "^3.13.0",
    "@react-spectrum/list": "^3.0.0-alpha.3",
    "@spectrum-icons/illustrations": "nightly",
    "next": "^11.1.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@zeit/next-css": "^1.0.1",
    "next-transpile-modules": "^8.0.0"
  }
```

**Comment by BengtHagemeister** [comment] 2021-11-08 14:06
I don't know what I'm doing wrong then. I have used the same dependencies as you and always get this behaviour. Here is another codesandbox with next 11: https://codesandbox.io/s/serene-nash-n8r5c?file=/pages/index.js:291-350

I also made a small screen recording:

https://user-images.githubusercontent.com/30391176/140755641-b6e6c372-8be2-4f09-8a8b-e7ab621c2a31.mov

I'm getting also a "Type Error" which I can not reproduce in my own app, so I ignored it for this example.

**Comment by reidbarber** [comment] 2021-11-08 17:22
I'm getting inconsistent results, as it seems to be working fine here: https://codesandbox.io/s/listview-with-next-js-dss7t?file=/pages/index.js

Re-arranging the imports fixed your example for me, but I'm getting generally finicky results in codesandbox with Next.js anyway. I'll see if I can reproduce locally and try to dig a little deeper.

**Comment by dannify** [comment] 2024-07-17 00:18
Closing: could not reproduce. Please reopen with a new example if this issue still exists.

**Closed by dannify** 2024-07-17 00:18 UTC
