### ISSUE TITLE
Picker - Misalignment of dropdown list with react-18

### ISSUE THREAD

**Issue by Mayuri66** [adobe/react-spectrum#3923] opened 2023-01-17 09:23 UTC
# 🐛 Bug Report 

With react 18 upgrade in our code base, we have found that Picker dropdown alignment is not as expected.
I have verified the react-spectrum storybook to check if the same issue is here or not and found that its working properly here because spectrum is using react 16.
**Issue is only happening for react 18 version.**

I have tried to replicate the issue with react-16 and react-18.
Please find the sandbox link below for both.
**React 16** : https://codesandbox.io/s/react-spectrum-picker-react16-n0bob7?file=/src/App.js
**React 18** : https://codesandbox.io/s/react-spectrum-picker-react18-gx7lrg?file=/src/App.js

**Steps to replicate :**
1. Minimise the screen size or click on toggle responsive preview (top-right)
![image](https://user-images.githubusercontent.com/61056882/212862233-9a3779fc-40c1-4fb4-87a6-2112bd4b89f1.png)
2. Click on choose frequency dropdown.
3. With react-16 version , dropdown menu list is adjusting its space in available viewport. But with react-18 , dropdown menu list alignment is always downward, so it is hiding behind the view port.

**Expected behaviour :**
<img width="318" alt="image" src="https://user-images.githubusercontent.com/61056882/212859151-4338deb2-05fc-4088-890d-b4e46a3e44eb.png">

**Current behaviour:**
<img width="321" alt="image" src="https://user-images.githubusercontent.com/61056882/212859310-1ca7b57c-1ab8-4a9a-9684-282dc6fcbd64.png">

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

Adobe Journey Optimizer

**Comment by reidbarber** [comment] 2023-01-17 16:26
The sandboxes you linked use `@adobe/react-spectrum` version `3.3.0`. If you update it to latest `3.24.1`, it works as expected.

**Comment by Mayuri66** [comment] 2023-01-18 09:37
@reidbarber , We have upgraded the @adobe/rect-spectrum version to 3.24.1, but still the same issue. Please find the sandbox link - https://codesandbox.io/s/react-spectrum-picker-react18-gx7lrg?file=/src/App.js&resolutionWidth=320&resolutionHeight=665

**Comment by reidbarber** [comment] 2023-01-18 15:57
It does look like an issue when you adjust the screen height.

**Comment by LFDanLu** [comment] 2023-02-02 01:41
Did some digging, the last time this worked on iPad was d264e8e17f556e661cde86bb3893ff2f93164f8c it seems.

**Comment by LFDanLu** [comment] 2024-08-23 20:28
I unable to reproduce anymore on latest using https://codesandbox.io/p/sandbox/eloquent-mcclintock-jnphdy?file=%2Fsrc%2FApp.js%3A8%2C62 nor in docs in iPad closing. Feel free to reopen if you are still experiencing issues.

**Closed by LFDanLu** 2024-08-23 20:29 UTC
Labels: bug, needs investigation
